### ISSUE TITLE
backend not work in digital ocean cent os 9 

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#10]
![ddd](https://user-images.githubusercontent.com/123809903/215263615-751c3f0a-4f97-4dc8-9052-717015dda25f.png)

**Comment by mohammadoaaakd** [comment]
also in debian 11 digital ocean xmplus 8 log not work

**Comment by mohammadoaaakd** [comment]
another bug is for get ssl in backend ... i change 10 server in hetzner to get ssl but v2board not need ssl

**Comment by xcode75** [comment]
this is not backend issue, your server not able to donwload from github. You need to check the error look at the error in red color
