### ISSUE TITLE
sign up page has bug in RTL

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#100]
hi
sign up page has bug in email field when email limit is on
In a right-handed language, the email domain should be on the right and the email name on the left, but now it is the other way around and users get confused.

I am sending you a screenshot of this bug here

so tnx for your good support
![photo_2023-03-12_01-50-03](https://user-images.githubusercontent.com/124066783/224514191-83ee9db8-cf5f-4e99-b2e5-cd85052c53c0.jpg)

**Comment by xcode75** [comment]
Noted
