### ISSUE TITLE
Detect Rules

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XManagerPlus#101]
Is it possible to make a "Detect rules" for XMPlus frontend panel as an example? Because everything I did didn't work!

**Comment by xcode75** [comment]
Detect rules are for blocking, each rule must have just one rule. Example: google.com . Rule can be written using regex format.  Eg,  to block torrents, 
 (torrent|.torrent|peer_id=|info_hash|get_peers|find_node|BitTorrent|announce_peer|announce.php?passkey=)


To block 360 website or 360 antivirus software

(.*\.||)(360|360safe|so|360totalsecurity|qihoo|qhimg)\.(cn|com)
