### ISSUE TITLE
eror payment

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#102]
hello i have problem until i want to pay give tihs eror

![aa](https://user-images.githubusercontent.com/123809903/224672871-5a2c055c-6aee-41af-8b05-cad575bfffe1.png)

**Comment by mohammadoaaakd** [comment]
[debug eror.txt](https://github.com/xcode75/XManagerPlus/files/10956168/debug.eror.txt)


debug eror log

**Comment by mohammadoaaakd** [comment]
error":{"type":"Whoops\\Exception\\ErrorException","message":"Undefined index: currency","code":8,"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Repository\/Payments\/Zarinpal.php","line":0,"trace":[{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Repository\/Payments\/Zarinpal.php","line":0,"function":null,"class":"Whoops\\Exception\\ErrorException","args":["Undefined index: currency"]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Repository\/Payments\/Zarinpal.php","line":0,"function":"handleError","class":"Whoops\\Run","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Services\/PaymentService.php","line":0,"function":"pay","class":"App\\Repository\\Payments\\Zarinpal","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Http\/Controllers\/User\/OrderController.php","line":0,"function":"pay","class":"App\\Services\\PaymentService","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php","line":43,"function":"checkout","class":"App\\Http\\Controllers\\User\\OrderController","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":384,"function":"__invoke","class":"Slim\\Handlers\\Strategies\\RequestResponse","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/app\/Http\/Middleware\/UserAuth.php","line":53,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"App\\Http\\Middleware\\UserAuth","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:294$afe7","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":341,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php","line":84,"function":"run","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/bryanjhv\/slim-session\/src\/Slim\/Middleware\/Session.php","line":82,"function":"handle","class":"Slim\\Routing\\RouteRunner","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"Slim\\Middleware\\Session","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php","line":68,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:294$afe7","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\BodyParsingMiddleware","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php","line":59,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$afe5","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\RoutingMiddleware","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/selective\/basepath\/src\/BasePathMiddleware.php","line":52,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$afe5","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":209,"function":"process","class":"Selective\\BasePath\\BasePathMiddleware","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/middlewares\/whoops\/src\/Whoops.php","line":104,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:167$afe6","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Middlewares\\Whoops","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php","line":107,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$afe5","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\ErrorMiddleware","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$afe5","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/App.php","line":215,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/vendor\/slim\/slim\/Slim\/App.php","line":199,"function":"handle","class":"Slim\\App","args":[]},{"file":"\/www\/wwwroot\/pcgamesonline.xyz\/public\/index.php","line":0,"function":"run","class":"Slim\\App","args":[]}]}}

**Comment by m0000hamad** [comment]
yes i have same problem from today

**Comment by beprivateonline** [comment]
The very same Here.

**Comment by beprivateonline** [comment]
Anyone has any update? @m0000hamad @mohammadoaaakd 
@xcode75 is not answering soon.

**Comment by xcode75** [comment]
It seems exchange rate api no longer support IRR, it has nothing to do with update. Have to wait for me to find a replcement that support IRR and is free. You can an api name here.

**Comment by prooshani** [comment]
Seems like the problem gone as of now, maybe by itself or the API started to convert IRR again.


> It seems exchange rate api no longer support IRR, it has nothing to do with update. Have to wait for me to find a replcement that support IRR and is free. You can post an api name here.

For IRR itself I don't see any usage of currency conversion at all!
it can work stand alone without any currency conversion.

**Comment by beprivateonline** [comment]
Seems like the problem gone as of now, maybe by itself or the API started to convert IRR again.

It seems exchange rate api no longer support IRR, it has nothing to do with update. Have to wait for me to find a replcement that support IRR and is free. You can post an api name here.

For IRR itself I don't see any usage of currency conversion at all!
it can work stand alone without any currency conversion.

**Comment by mohammadoaaakd** [comment]
problem was be solved i craete new getway


![adsd](https://user-images.githubusercontent.com/123809903/224946282-e637cc82-372e-4c23-82f9-216acbd1ca42.png)

**Comment by mohammadoaaakd** [comment]
ty all

**Comment by m0000hamad** [comment]
من کاری نکردم خودش درست شد

**Comment by m0000hamad** [comment]
> It seems exchange rate api no longer support IRR, it has nothing to do with update. Have to wait for me to find a replcement that support IRR and is free. You can post an api name here.

For now, the problem has been solved
