### ISSUE TITLE
multiple mail notifications

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#103]
When users data is over, the system is sending multiple emails to let them know instead of one! 
![image](https://user-images.githubusercontent.com/35190548/224752778-d33cd066-cb62-459c-ad77-1333b850690a.png)

**Comment by amihos** [comment]
I checked further and I noticed, at some intervals (which looks like random, 12 mintues, 10 mintues, 8 minutes etc)  the system is sending AGAIN to all whose traffic got over and <were sent an email before> another email!

**Comment by xcode75** [comment]
Noted

**Comment by amihos** [comment]
Update: I think this is happening with everytime the server is making backups and send them via email/and/or telegram. I am seeing that the mail notifications are being sent to users as well.
