### ISSUE TITLE
dashboard stats are not being updated

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#112]
after latest update: v20230324
The main admin dashboard's data stats are not being updated. Unless I press refresh on the page
![image](https://user-images.githubusercontent.com/35190548/227631849-d943c605-3115-45e3-b580-2f3f70a2d0c9.png)

**Comment by xcode75** [comment]
Yes, removed realtime dasboard stats updates causing cpu and high memory usage.
