### ISSUE TITLE
i cannot find bind telegram button or link

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#114]
hi dear 
i cannot find bind telegram button or link on user setting 
so i want to know how can i bind telegram account to site account
![Screenshot (71)](https://user-images.githubusercontent.com/124066783/227654988-dc52ff7e-62be-40fd-a41d-769d2fda51c4.png)

**Comment by xcode75** [comment]
a minor error, will update tomorrow
