### ISSUE TITLE
After update v20230324

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#115]
Almost all bugs are fixed 🙏

There is only 4 bug

1) There is only one way to connect to the Telegram bot by activating the account verification option in the settings section
When you register, you can connect to the Telegram bot
If the account was created through the Admin management panel or by the Unbind Telegram option in the settings section
Deactivate, it is no longer possible to connect to the Telegram bot

This option was there in the previous updates, but it seems that it has been removed in this update

![Bug](https://user-images.githubusercontent.com/38170923/227720939-0dbc1bae-907a-473e-849e-ecdc2a030c63.png)

Also, if possible, add change the Telegram ID in the Admin management panel

![bb](https://user-images.githubusercontent.com/38170923/227720957-6e5e2892-6bf2-4009-9d44-d20f41db45a2.png)

2) Also, in section Knowledgebase -----> App Setup and others, all the writings get the following error after opening

![Bug 2](https://user-images.githubusercontent.com/38170923/227724154-2878cf8d-c04f-47d5-8ccc-5c2033aa2f69.png)

3) Also by clicking on the server section
The barcode containing the connection settings is not displayed
Also, the existing connection Trojan WS in this section will not be executed after copying and transferring to the software V2rayNG
which is due to the addition of flow=none in the config content

![Bug 3](https://user-images.githubusercontent.com/38170923/227726155-22decb16-33c6-4a6d-89cc-9c3add82a913.png)

4) In the section to copy the connection link of the programs FairVPN and Shadowrocket
There is a connection error
Due to not adding these parts &host=x.tld.com&path=%2Fxmplus in the subscription content
Connection = Trojan WebSocket

Thanks for your hard work in solving the problems 🌹🙏

**Comment by seyyed1332** [comment]
[sh1375](https://github.com/sh1375) 

All same Issuse

**Comment by shadow-vpn** [comment]
Yes, all these problems exist for me too
