### ISSUE TITLE
(URGENT) Site is not usable on mobile any more 

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#117]
Today I noticed that I can not add data to a user from mobile and I got this message saying that I do not have a valid licence and I need to contact @xcode75 
![image](https://user-images.githubusercontent.com/35190548/227769993-c26666ed-e83e-4308-ba4f-4e3ce9e73e59.png)

Then one of the users also complained that they could not register using invite link either on mobile:
![image](https://user-images.githubusercontent.com/35190548/227770185-47b2717a-91ff-4384-8759-e8fc23d89d41.png)

I confirm that everything is working on pc thought!

On the side note, I also noticed today when I woke up that my admin user had got suspended! I could recover it by changing its status in the database. I do not know if this is related to the above issues or not but just to mention it.

**Comment by lostsoul6** [comment]
this product is not free . you need to buy the license . it's free for 30 users and 10 servers .

https://xcode75.github.io/XMPlusDocs/usage/license.html

**Comment by xcode75** [comment]
are you sure you visited the site on the domain you paid for?

**Comment by amihos** [comment]
No I did not. Since my main domain got banned I started to use another CNAME domain.  However, this issue was not happening before the update. 

I have another website that also is connected to another CNAME domain which is not yet updated to the recent version. I confirm that there is no such issue when I visit via CNAME domain.

**Comment by amihos** [comment]
update: I was wrong. The same issue is true for pc. I was not paying attention to the domain I was using. So I confirm that if you use any other domain than the registered domain this happens. 

However the not yet updated site does not have this issue.

**Comment by xcode75** [comment]
> update: I was wrong. The same issue is true for pc. I was not paying attention to the domain I was using. So I confirm that if you use any other domain than the registered domain this happens.
> 
> However the not yet updated site does not have this issue.

was a bug in previous version that allow non authorized domains to be used. Bug was fixed in latest update.
