### ISSUE TITLE
Update Cronjob command not working

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#118]
hi
Update Cronjob command not working and i get the fallowing error
-bash: ./update_cron.sh: /usr/bin/bash^M: bad interpreter: No such file or directory

also i tried to Manually update Cronjob by ssh but thats not working for me 

please help me to fix this issue

**Comment by amihos** [comment]
I had the same issue: This fixed my issue:
https://t.me/XManagerPlus/237

**Comment by ca3tiel** [comment]
thanks @amihos 
i did replace new update_cron.sh file from telegram and try to update cron again and the resalts message is:

:3: bad hour
errors in crontab file, can't install.
Cron updated

error message is changed to new error
plz help me to fix this issue

**Comment by amihos** [comment]
Ok, in this case @xcode75 should help as I have no clue how to fix it.

**Comment by xcode75** [comment]
> thanks @amihos i did replace new update_cron.sh file from telegram and try to update cron again and the resalts message is:
> 
> :3: bad hour errors in crontab file, can't install. Cron updated
> 
> error message is changed to new error plz help me to fix this issue

if you read the update info you will know there is a manually entry using ssh if update_cron.sh is not working for you.  crontab -e
