### ISSUE TITLE
Slim Application Error at knowledgebase section

### ISSUE THREAD

**Issue by letmefind** [xcode75/XManagerPlus#127]
Getting error message if open article under  knowledgebase >> App Setup >> titles 
```
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

```
![slim error](https://user-images.githubusercontent.com/127405150/228640356-49cfdb1e-859c-43fb-9a2b-30a31e0341ba.png)

**Comment by sh1375** [comment]
> Getting error message if open article under knowledgebase >> App Setup >> titles
> 
> ```
> Slim Application Error
> A website error has occurred. Sorry for the temporary inconvenience.
> ```
> 
> ![slim error](https://user-images.githubusercontent.com/127405150/228640356-49cfdb1e-859c-43fb-9a2b-30a31e0341ba.png)

Update to v20230329 will be resolved
