### ISSUE TITLE
LanceX  client

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#128]
knowledgebase   > not show post
IRR to usdt  >  x10 Convert  

please add LanceX client for ios   (lanceX  use  shadowrocket=1)  It works well
Add local time to UI panel

**Comment by payeh** [comment]
Emali Message doesn't support RTL

**Comment by ca3tiel** [comment]
lance X is not free application and its 3$...shadowrocket is the best if u want pay

**Comment by payeh** [comment]
> lance X is not free application and its 3$...shadowrocket is the best if u want pay

LanceX ui  is better than Shadowrocket

**Comment by ca3tiel** [comment]
@payeh 
don't be upset.. its just a suggestion and i didn't use lanceX ...i just read some users comments and they are say shadowrocket have stable connection and just try to share this data whit you

**Comment by xcode75** [comment]
app\Repository\Clients

you can add a client in that folder

**Comment by payeh** [comment]
how to change ?shadowrocket=1 to  ?lancex=1   or add new config link
With all the characteristics of a shadowrocket link
