### ISSUE TITLE
question about change link address

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#132]
hi @xcode75 
i have a question about fallowing section 

# Invitation address
$_ENV['InviteUrl']    = ""; #Invitation link address, default is set to current site address. https://www.xyz.dev

# Subscription address
$_ENV['SubUrl']     = ""; #Subscription link address, default is set to current site address. https://www.xyz.dev

# Subscription route
$_ENV['SubRoute']     = "/link"; # Subscription link route. You can replace this route but must start with /. eg, /web/config

Can we use this section to send subscription links from another domain instead of default domain?
Since our main domain may be filtered and users cannot update their subscriptions without VPN, can we use this section to provide users with subscription links from another domain?
Please guide me on the process
thanks

**Comment by xcode75** [comment]
yes can
