### ISSUE TITLE
Question : Daylight Saving Time (DST)

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#133]
Hello. Due to the fact that summer time is no longer active in Iran, now the panel clock is set 1 hour ahead. But the server clock displays the correct time. How can the time difference problem be solved?

![Screenshot 2023-04-01 150347](https://user-images.githubusercontent.com/30972110/229285042-26bef793-8f43-4c10-9f3b-f49adffc8e63.jpg)

**Comment by banxter** [comment]
As far as i figured out, it has nothing to do with your server time.. it is completely related to the user's device time,, if you change your device's time manually, some apps no longer work,,

so, you cannot change your client's device time manually, because of fixing the time problem,, if you change the time manually (1 hour or just 1 minute, no difference..) client app don't work anymore...

for now, you can just pick up another time zone or just live with the wrong time zone and wait for the Iran's time zone to update automatically..

**Comment by matador7495** [comment]
> As far as i figured out, it has nothing to do with your server time.. it is completely related to the user's device time,, if you change your device's time manually, some apps no longer work,,
> 
> so, you cannot change your client's device time manually, because of fixing the time problem,, if you change the time manually (1 hour or just 1 minute, no difference..) client app don't work anymore...
> 
> for now, you can just pick up another time zone or just live with the wrong time zone and wait for the Iran's time zone to update automatically..

Dear friend, you did not understand my question correctly. No one has anything to do with the time zone of the user's device, because by changing it to manual mode, some software will be disturbed.

Also, when we change the time zone of the server from aapanel to Tehran, it works correctly and shows the correct time. The problem is the time zone section in the config file that I sent a photo of. This section is related to the time registration of invoices and reports, etc., which stores 1 hour ahead in the database.

It looks like it is calling the time zone from a separate api.

I asked @xcode75  how to make it use the time zone server that displays the correct time.

**Comment by xcode75** [comment]
> Hello. Due to the fact that summer time is no longer active in Iran, now the panel clock is set 1 hour ahead. But the server clock displays the correct time. How can the time difference problem be solved?
> 
> ![Screenshot 2023-04-01 150347](https://user-images.githubusercontent.com/30972110/229285042-26bef793-8f43-4c10-9f3b-f49adffc8e63.jpg)

you can try $_ENV['timeZone'] 	= "Etc/GMT-3";

**Comment by matador7495** [comment]
Does not work.

@xcode75

**Comment by payeh** [comment]
Does not work.

@xcode75

**Comment by xcode75** [comment]
Tesed and it work, if you thing is wrong, you can adjust there timezone yourself.
