### ISSUE TITLE
use nobitex api  for IRR to usdt and trx

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#139]
**Nobitex exchange is the largest cryptocurrency exchange in Iran**
![image](https://user-images.githubusercontent.com/28225346/229386053-59f0cecd-f09d-403b-ada4-030d2b2b03ef.png)

_- You can use the following api for exact IRR conversion
- The exchange is stable and very old
- The use of this api does not include restrictions
-_ 
**api [use bestSell price] :**
usdt 
`https://api.nobitex.ir/market/stats?srcCurrency=usdt&dstCurrency=rls`
trx
`https://api.nobitex.ir/market/stats?srcCurrency=trx&dstCurrency=rls`
other coins
`https://api.nobitex.ir/market/stats?srcCurrency=**[EnterCoin]**&dstCurrency=rls`

@xcode75

**Comment by ArashPersian** [comment]
سلام دوست عزیز .
خودمون میتونیم این api رو جایگذاری کنیم یا سازنده این کار رو بایستی انجام بده .؟
و اگر خودمون میتونیم کجا بایستی جایگذاری کنیم.؟

**Comment by payeh** [comment]
> سلام دوست عزیز . خودمون میتونیم این api رو جایگذاری کنیم یا سازنده این کار رو بایستی انجام بده .؟ و اگر خودمون میتونیم کجا بایستی جایگذاری کنیم.؟
سلام متأسفانه سورس رمزنگاری شده باید توسط سازنده این کار صورت بگیره

**Comment by payeh** [comment]
> سلام دوست عزیز . خودمون میتونیم این api رو جایگذاری کنیم یا سازنده این کار رو بایستی انجام بده .؟ و اگر خودمون میتونیم کجا بایستی جایگذاری کنیم.؟

سلام متأسفانه سورس رمزنگاری شده باید توسط سازنده این کار صورت بگیره
