### ISSUE TITLE
Cloudflare CDN Setup

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XManagerPlus#14]
Hi,
I tried to use Cloudflare CDN from the [docs](https://xcode75.github.io/XMPlusDocs/servers/cdn.html) but I could not connect at all. What I did was I made a server like screenshots I attached to this ticket but I can't connect with it at all! There is no error on the XMPlus log.
![xmplus01](https://user-images.githubusercontent.com/88386604/215361289-945b44b5-5b78-4912-ac9f-1d93adafbc90.jpg)

Host is same as Server address
![xmplus02](https://user-images.githubusercontent.com/88386604/215361297-bf64ee2f-cad3-4c7e-9654-66db058449a4.jpg)

Servername is same as Server address
![xmplus03](https://user-images.githubusercontent.com/88386604/215361299-b97c062d-8504-414b-8d23-f3e621e1cb07.jpg)

And this is what I set for cdn.conf file:
server {
    listen 443 ssl http2  so_keepalive=on;
    listen [::]:443 ssl http2; 
    server_name my.server.name;

    index index.html;
    root /var/www/html;

    ssl_certificate /your/cert/my.server.name.crt;
    ssl_certificate_key /your/key/my.server.name.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    client_header_timeout 52w;
    keepalive_timeout 52w;

    location / { 
          if ($http_upgrade != "websocket") {
              return 404;
        }
          proxy_redirect off;
          proxy_pass http://127.0.0.1:2053; #proxy_pass http://127.0.0.1:5500
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }    
}

If I set port number as 2053 in "listen 443 SSL http2  so_keepalive=on;" and "listen [::]:443 SSL http2;" so Nginx does not run because of the port using confliction.

**Comment by xcode75** [comment]
Server settings, server port must be nginx port 443

**Comment by dadashali61** [comment]
Sorry, but I didn't get where you mentioned "Server settings" and cert that must be changed to "off". May you explain more clearly, please?

**Comment by dadashali61** [comment]
I just list all ports that I think needed to be set. May you tell me which one is right or which one must change?
Also, where I  must yo change cert off?
Server port: 443
Listen port: 443
listen 443 ssl http2 so_keepalive=on;
listen [::]:443 ssl http2;
proxy_pass http://127.0.0.1:2053;

**Comment by xcode75** [comment]
> Hi, I tried to use Cloudflare CDN from the [docs](https://xcode75.github.io/XMPlusDocs/servers/cdn.html) but I could not connect at all. What I did was I made a server like screenshots I attached to this ticket but I can't connect with it at all! There is no error on the XMPlus log. ![xmplus01](https://user-images.githubusercontent.com/88386604/215361289-945b44b5-5b78-4912-ac9f-1d93adafbc90.jpg)
> 
> Host is same as Server address ![xmplus02](https://user-images.githubusercontent.com/88386604/215361297-bf64ee2f-cad3-4c7e-9654-66db058449a4.jpg)
> 
> Servername is same as Server address ![xmplus03](https://user-images.githubusercontent.com/88386604/215361299-b97c062d-8504-414b-8d23-f3e621e1cb07.jpg)
> 
> And this is what I set for cdn.conf file: server { listen 443 ssl http2 so_keepalive=on; listen [::]:443 ssl http2; server_name my.server.name;
> 
> ```
> index index.html;
> root /var/www/html;
> 
> ssl_certificate /your/cert/my.server.name.crt;
> ssl_certificate_key /your/key/my.server.name.key;
> ssl_protocols TLSv1.2 TLSv1.3;
> ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
> 
> client_header_timeout 52w;
> keepalive_timeout 52w;
> 
> location / { 
>       if ($http_upgrade != "websocket") {
>           return 404;
>     }
>       proxy_redirect off;
>       proxy_pass http://127.0.0.1:2053; #proxy_pass http://127.0.0.1:5500
>       proxy_http_version 1.1;
>       proxy_set_header Upgrade $http_upgrade;
>       proxy_set_header Connection "upgrade";
>       proxy_set_header Host $host;
>       proxy_set_header X-Real-IP $remote_addr;
>       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> }    
> ```
> 
> }
> 
> If I set port number as 2053 in "listen 443 SSL http2 so_keepalive=on;" and "listen [::]:443 SSL http2;" so Nginx does not run because of the port using confliction.

your server port must be 443 the nginx port and cert mode none read the documentation well

**Comment by dadashali61** [comment]
I read the doc and while I couldn't find the solution so I asked you here. How may I set the Nginx port and cert mode as none?
May you show me like the example that I sent you?

**Comment by Zo0oX** [comment]
i have same problem, its cerificate problem
in /etc/XMPlus i see cert folder, buy i cant see insde the folder key and cert
what is the location for this files ?
ssl_certificate /your/cert/x.tld.com.crt;
ssl_certificate_key /your/key/x.tld.com.key;
