### ISSUE TITLE
coupons code issue

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#140]
copun code not work 
![asasewwwq](https://user-images.githubusercontent.com/123809903/229747750-536b1e24-0e60-4072-827d-691e2a9a22ca.png)

![aasas](https://user-images.githubusercontent.com/123809903/229747792-5c266ea8-715b-4e5f-8691-83ef5c010105.png)

**Comment by payeh** [comment]
> copun code not work ![asasewwwq](https://user-images.githubusercontent.com/123809903/229747750-536b1e24-0e60-4072-827d-691e2a9a22ca.png)
> 
> ![aasas](https://user-images.githubusercontent.com/123809903/229747792-5c266ea8-715b-4e5f-8691-83ef5c010105.png)

Change the user limit value to 0 and try again
`User Limit = 0`

**Comment by mohammadoaaakd** [comment]
User Limit = 0

![arac](https://user-images.githubusercontent.com/123809903/229778096-9ee8cb66-2b53-4f85-8af4-ff52064afafc.png)

**Comment by payeh** [comment]
> User Limit = 0
> 
> ![arac](https://user-images.githubusercontent.com/123809903/229778096-9ee8cb66-2b53-4f85-8af4-ff52064afafc.png)
![image](https://user-images.githubusercontent.com/28225346/229782334-cefd7bf3-a104-4c4d-9145-dc26c0044405.png)

billing cycle not checked

**Comment by mohammadoaaakd** [comment]
ty
