### ISSUE TITLE
Create a user

### ISSUE THREAD

**Issue by kanganpishgaman** [xcode75/XManagerPlus#141]
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email_verify' in 'field list' (SQL: insert into `user` (`username`, `email`, `passwd`, `uuid`, `currency`, `t`, `u`, `d`, `transfer_enable`, `afflink`, `tg_token`, `money`, `reg_date`, `reg_ip`, `token`, `ga`, `ga_status`, `role`, `email_verify`, `ref_by`, `iplimit`, `speedlimit`, `expire_in`, `server_group`, `notification`) values (ahmadkousari, ahmadkousari@gmail.com, 26fa3ebe21340e4e62f4a260877095092eff5f4a619ce7a60ee57a355aa4adfb, aba1ce34-dfe6-4541-81b9-42620d12c88d, IRR, 0, 0, 0, 0, K9jcMsf1uH, vBsfxeuRKKURGPUP, 0, 2023-04-05 12:32:07, 185.120.198.36, edLmMzJ9VS5ynT1YQ6YK, URR6G3GWTOXSOMQJ, 0, 0, 1, 1, 0, 100, 2023-04-05 12:32:07, 1, {\"sendnotices\":\"0\",\"dataused\":\"0\",\"dataexpire\":\"0\",\"loginnotify\":\"1\"}))","code":"42S22","file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":671,"trace":[{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":671,"function":null,"class":"Illuminate\\Database\\QueryException","args":["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email_verify' in 'field list' (SQL: insert into `user` (`username`, `email`, `passwd`, `uuid`, `currency`, `t`, `u`, `d`, `transfer_enable`, `afflink`, `tg_token`, `money`, `reg_date`, `reg_ip`, `token`, `ga`, `ga_status`, `role`, `email_verify`, `ref_by`, `iplimit`, `speedlimit`, `expire_in`, `server_group`, `notification`) values (ahmadkousari, ahmadkousari@gmail.com, 26fa3ebe21340e4e62f4a260877095092eff5f4a619ce7a60ee57a355aa4adfb, aba1ce34-dfe6-4541-81b9-42620d12c88d, IRR, 0, 0, 0, 0, K9jcMsf1uH, vBsfxeuRKKURGPUP, 0, 2023-04-05 12:32:07, 185.120.198.36, edLmMzJ9VS5ynT1YQ6YK, URR6G3GWTOXSOMQJ, 0, 0, 1, 1, 0, 100, 2023-04-05 12:32:07, 1, {\"sendnotices\":\"0\",\"dataused\":\"0\",\"dataexpire\":\"0\",\"loginnotify\":\"1\"}))"]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Services\/UserService.php","line":0,"function":"save","class":"Illuminate\\Database\\Eloquent\\Model","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Http\/Controllers\/Admin\/UserController.php","line":0,"function":"create","class":"App\\Services\\UserService","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Http\/Middleware\/AdminMiddleware.php","line":0,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/public\/index.php","line":0,"function":"run","class":"Slim\\App","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":458,"function":null,"class":"PDOException","args":["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email_verify' in 'field list'"]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":458,"function":"prepare","class":"PDO","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":664,"function":"Illuminate\\Database\\{closure}","class":"Illuminate\\Database\\Connection","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":631,"function":"runQueryCallback","class":"Illuminate\\Database\\Connection","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":465,"function":"run","class":"Illuminate\\Database\\Connection","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Connection.php","line":417,"function":"statement","class":"Illuminate\\Database\\Connection","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Query\/Processors\/Processor.php","line":32,"function":"insert","class":"Illuminate\\Database\\Connection","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Query\/Builder.php","line":2839,"function":"processInsertGetId","class":"Illuminate\\Database\\Query\\Processors\\Processor","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Eloquent\/Builder.php","line":1422,"function":"insertGetId","class":"Illuminate\\Database\\Query\\Builder","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Eloquent\/Model.php","line":902,"function":"__call","class":"Illuminate\\Database\\Eloquent\\Builder","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Eloquent\/Model.php","line":867,"function":"insertAndSetId","class":"Illuminate\\Database\\Eloquent\\Model","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/illuminate\/database\/Eloquent\/Model.php","line":730,"function":"performInsert","class":"Illuminate\\Database\\Eloquent\\Model","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Services\/UserService.php","line":0,"function":"save","class":"Illuminate\\Database\\Eloquent\\Model","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Http\/Controllers\/Admin\/UserController.php","line":0,"function":"create","class":"App\\Services\\UserService","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php","line":43,"function":"save","class":"App\\Http\\Controllers\\Admin\\UserController","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":384,"function":"__invoke","class":"Slim\\Handlers\\Strategies\\RequestResponse","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/app\/Http\/Middleware\/AdminMiddleware.php","line":0,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"App\\Http\\Middleware\\AdminMiddleware","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:294$1522a6","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":341,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php","line":84,"function":"run","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/bryanjhv\/slim-session\/src\/Slim\/Middleware\/Session.php","line":82,"function":"handle","class":"Slim\\Routing\\RouteRunner","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"Slim\\Middleware\\Session","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php","line":68,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:294$1522a6","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\BodyParsingMiddleware","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php","line":59,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$1522a4","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\RoutingMiddleware","args":[]},

{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/selective\/basepath\/src\/BasePathMiddleware.php","line":52,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$1522a4","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":209,"function":"process","class":"Selective\\BasePath\\BasePathMiddleware","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/middlewares\/whoops\/src\/Whoops.php","line":104,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:167$1522a5","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Middlewares\\Whoops","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php","line":107,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$1522a4","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\\Middleware\\ErrorMiddleware","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:128$1522a4","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/App.php","line":215,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/vendor\/slim\/slim\/Slim\/App.php","line":199,"function":"handle","class":"Slim\\App","args":[]},{"file":"\/www\/wwwroot\/ciscokangan.click\/public\/index.php","line":0,"function":"run","class":"Slim\\App","args":[]}]}}

Hello, this warning is given when creating a user

**Comment by xcode75** [comment]
you skipped an update that is why. Manually import database file in v202303024 update to your database
