### ISSUE TITLE
TRX Gateways

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#142]
I tested the Tron payment gateway twice, but it gives the error bad gateway.

![image](https://user-images.githubusercontent.com/30972110/230050636-88fcef7d-d42c-4523-afaa-c81d1226e642.png)

**Comment by xcode75** [comment]
Issue with your server  reboot and see

**Comment by matador7495** [comment]
The payment gateway has a problem, the server has been restarted several times, but the problem is not solved. The Tether payment gateway works without problems, but Tron gives error 502.

@xcode75
