### ISSUE TITLE
Big Requests: Add ssr to XMPLUS

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#143]
hi @xcode75 
Currently we only use Xray which requires a domain and use cloudflare and currently there is severe disruption on cloudflare and domains are quickly filtered out in this way. But ssr does not have these problems, and in the tests I did, the speed and stability were excellent. its secure and work better than Xray
Please add ssr to XMPLUS .
I ask other friends to express their opinion

**Comment by xcode75** [comment]
SSR will not be added
