### ISSUE TITLE
Ability to move servers

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#145]
hello sir
![ssad](https://user-images.githubusercontent.com/123809903/230564447-00fc3693-76cb-41d0-afe4-3d6bb072b591.png)

If possible, add the ability to move the servers so that we can arrange them, thank you

**Comment by amihos** [comment]
@mohammadoaaakd if you want to arrange them for the users, just use server "sort" field. Give them numbers and they will be sorted based on them.

**Comment by mohammadoaaakd** [comment]
> 

I don't understand what you mean, if you can explain more

**Comment by HamrahVIP** [comment]
i'm looking for a way to change node id of servers from panel
it's possible?
