### ISSUE TITLE
request for new app 

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#147]
hello 
this app is like v2rayng .if this good pls add in xmplus

![sdsa](https://user-images.githubusercontent.com/123809903/230616365-39a4be70-e8f1-4014-8756-64b17eb44026.png)

**Comment by payeh** [comment]
https://github.com/xcode75/XManagerPlus/issues/128

**Comment by mohammadoaaakd** [comment]
thanks
