### ISSUE TITLE
sub not worcked

### ISSUE THREAD

**Issue by rezaziyai** [xcode75/XManagerPlus#148]
after install new panel 
There is no subscription field
Also, the subscription link does not work on the phone
![xm](https://user-images.githubusercontent.com/127259418/230714732-86a0c331-5432-452d-905e-57cbd6526860.png)

**Comment by xcode75** [comment]
Refere to updates notice from v20230324

**Comment by rezaziyai** [comment]
There is the same problem in this version
v20230324
