### ISSUE TITLE
account balance

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#149]
hello 
gift card in site works
but in site we cant buy with account balance or add money in balance 

![969](https://user-images.githubusercontent.com/123809903/230716097-a641e0d0-3773-4933-901b-f5db34dea82e.png)

2-we cant delete gift card

![sadsad](https://user-images.githubusercontent.com/123809903/230716145-2ca05a6f-fd68-46f8-b1e1-d1ae884bfbb6.png)

**Comment by xcode75** [comment]
There is no issue, just disable it
