### ISSUE TITLE
All in one config if it possible

### ISSUE THREAD

**Issue by malikshi** [xcode75/XManagerPlus#15]
https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx
I think most people want to ask about this one and how  to configure with xmangerplus. If maintener add more details would be great. I did try but end up with Websocket and grpc transport. When I tried to setup trojan gfw(tcp+tls) fallback to websocket and grpc won't work or can't get the real ip of client.
Tldr: I had 2 vps, one for website/panel then 1 vps as node with running websocket+grpc transport.

**Comment by xcode75** [comment]
> https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx I think most people want to ask about this one and how to configure with xmangerplus. If maintener add more details would be great. I did try but end up with Websocket and grpc transport. When I tried to setup trojan gfw(tcp+tls) fallback to websocket and grpc won't work or can't get the real ip of client. Tldr: I had 2 vps, one for website/panel then 1 vps as node with running websocket+grpc transport.

You have to setup multiple nodes and use nginx for the fallbacks, enable fallbacks in node settings in panel.
