### ISSUE TITLE
[Bug] All subscribe links are broken and Clash subscription is invalid

### ISSUE THREAD

**Issue by JobberRT** [xcode75/XManagerPlus#153]
By default, all applicaitons' subscription link are differed by `clash=1` or `shadowrocket=1`, rather than `?clash=1` or `?shadowrocket=1`.

This behavior makes the full subscription link are joined by the application identifier, such as `https://example.com/sub/exampleUserTokenclash=1` and cause a Invalid Token error. Admin can manually change their identifier though.

Clash config file line 32 are broken(Don't know if there's more invalid synatx), `proxies` should be array of maps, rather than map

**Comment by xcode75** [comment]
There is nothing wrong with links, if you havr read update notice of v20230324 you would have known. There is no issue with new installation either.

**Comment by JobberRT** [comment]
I'm using fresh install with latest version from wiki page, otherwise I should submit this issue right after V0324 update.

And what about the Clash config file format incorrect?

**Comment by Dev-l0p** [comment]
Hello,
Read carefully:

`NOTE:

Add a question mark (?) to all your app settings Config (eg, ?clash=1) in admin Applications or leave blank for auto detect config for app. This may not work for every app, if that happens for the app you are using add the config link parameter for the app. eg, ?clash=1`

**Comment by JobberRT** [comment]
Thanks, I will follow the release note and try to solve this, if that doesn't work I think I should paste my config and debug log.
