### ISSUE TITLE
UX issue in users registration section

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#155]
User registration is the most important part of any system.
In the registration section, the field related to email is displayed as a drop-down , which is not correct from UX point of view and has confused many users. ( because users enter @gmail.com in this field and they get error for registration)  
![Screenshot 2023-04-11 150418](https://user-images.githubusercontent.com/57295411/231137718-c0bc8b78-d0b6-417e-bf6b-7a9899dc002f.png)

Due to the existence of the free test section, it is very important to activate the use of valid emails such as Google.
For this reason, in order to standardize this matter, please remove the e-mail from the drop-down mode in the registration, and if user want to use fake e-mails, only one notification will appear and ask the user for a valid e-mail.
change drop-down mode in users registration section like user login section
![Screenshot 2023-04-11 150541](https://user-images.githubusercontent.com/57295411/231139973-1cb39836-befe-486f-81cf-848f4c176275.png)

**Comment by xcode75** [comment]
you can disable email restriction in admin settings.

**Comment by matador7495** [comment]
> User registration is the most important part of any system. In the registration section, the field related to email is displayed as a drop-down , which is not correct from UX point of view and has confused many users. ( because users enter @gmail.com in this field and they get error for registration) ![Screenshot 2023-04-11 150418](https://user-images.githubusercontent.com/57295411/231137718-c0bc8b78-d0b6-417e-bf6b-7a9899dc002f.png)
> 
> Due to the existence of the free test section, it is very important to activate the use of valid emails such as Google. For this reason, in order to standardize this matter, please remove the e-mail from the drop-down mode in the registration, and if user want to use fake e-mails, only one notification will appear and ask the user for a valid e-mail. change drop-down mode in users registration section like user login section ![Screenshot 2023-04-11 150541](https://user-images.githubusercontent.com/57295411/231139973-1cb39836-befe-486f-81cf-848f4c176275.png)




No, removing the drop down menu is not a good suggestion. It is better to change the UI of this section and improve the width of the registration section to make the registration boxes more readable.
The dropdown menu can be changed to the bottom of the email address field.

**Comment by matador7495** [comment]
No, removing the drop down menu is not a good suggestion. It is better to change the UI of this section and improve the width of the registration section to make the registration boxes more readable.
The dropdown menu can be changed to the bottom of the email address field.


@ca3tiel @xcode75
