### ISSUE TITLE
add RealityObject to backend and frontend

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#156]
please add RealityObject to backend and frontend
its new
the reference page is here :
https://xtls.github.io/Xray-docs-next/config/transport.html#realityobject

**Comment by lostsoul6** [comment]
Hello . I'm also looking for this . We manage all our clients using XMplus backend and frontend . There are other panels that support reality but we can't have 2 separate panels . Please kindly add reality ASAP . My friends and I are willing to donate some dollars if you can manage this quickly . One panel that has added support for this is the following :
https://github.com/FranzKafkaYu/x-ui
obviously the above panel is an x-ui fork and nowhere near the quality of xmplus .
Please make it happen .

**Comment by lostsoul6** [comment]
Update : I have spoken with the developer about adding reality to xmplus . He said that it will be added but we have to wait for it . Other panels like x-ui use the xray-core api to calculate stats but XMplus has different mechanism . The developer said he has to find the best way to generate the private key first without official xray-core compiled files and once he achieves that , we are good .

دوستان با برنامه نویس صحبت کردم بابت اضافه کردن reality به اسکریپت . گفتش که اضافه میشه ولی باید صبر کرد چون xmplus مثل x-ui از api اصلی xray-core برای محاسبه ترافیک کاربرا استفاده نمیکنه . گفتش که وقتی بتونه بهترین راه برای ایجاد private key بدون استفاده از هسته اصلی xray رو پیدا کنه ، reality رو اضافه میکنه .
