### ISSUE TITLE
Some problems and questions

### ISSUE THREAD

**Issue by Dev-l0p** [xcode75/XManagerPlus#157]
Hello @xcode75 ,
Thank you in advance for paying attention to these four ISSUEs:

### 1. TelegramBOT not work:

After I update to latest version of XManagerPlus, TelegramBot not working currectly and /start not work.
How can I fix this problem?

### 2. Problem installing XrayR core:

I can't install XrayR core in backend server.
I install it several times in several server but not working while xmplus core install simply.
Which Core do you suggest I install? If XrayR, Please post the relevant tutorial.

### 3. Customer service role permissions:

This role have several permissions that It does not need to have these permissions.
Please add a feature where we can restrict access or learn us how to do this.

### 4. Customize First Trojan Config, _TOTAL USED Expire_:

How can I change this config from trojan to wmess _(trojan not support in some applications)_ and add every UserID to remark?

> Example :`#42`  , Traffic:45.5/100GB, Expire: 2023/05/24

`#42` is the userID in XMplusManager.

**Comment by matador7495** [comment]
1- Telegram bot has no problems. Make sure that ssl is enabled, and you have entered the admin user ID and token correctly in the settings, and finally don't forget the webhook set.

2- I use this version in Ubuntu 20 and there is no problem. 

https://xcode75.github.io/XMPlusDocs/install/xmplus.html
