### ISSUE TITLE
notices section error

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#158]
I checked the notices section again and saw this error

p
2023 © Example
v20230402

{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Undefined index: sendmail","code":8,"file":"\/www\/wwwroot\/Example.com\/app\/Http\/Controllers\/Admin\/NoticeController.php","line":0,"trace":[{"file":"\/www\/wwwroot\/Example.com\/app\/Http\/Controllers\/Admin\/NoticeController.php","line":0,"function":null,"class":"Whoops\\Exception\\ErrorException","args":["Undefined index: sendmail"]},{"file":"\/www\/wwwroot\/Example.com\/app\/Http\/Controllers\/Admin\/NoticeController.php","line":0,"function":"handleError","class":"Whoops\\Run","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php","line":38,"function":"save","class":"App\\Http\\Controllers\\Admin\\NoticeController","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":358,"function":"__invoke","class":"Slim\\Handlers\\Strategies\\RequestResponse","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/Example.com\/app\/Http\/Middleware\/Admin.php","line":50,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":269,"function":"__invoke","class":"App\\Http\\Middleware\\Admin","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:250$229d62","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":315,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php","line":68,"function":"run","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/bryanjhv\/slim-session\/src\/Slim\/Middleware\/Session.php","line":82,"function":"handle","class":"Slim\\Routing\\RouteRunner","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":269,"function":"__invoke","class":"Slim\\Middleware\\Session","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php","line":64,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:250$229d62","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\BodyParsingMiddleware","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php","line":45,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$229d60","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\RoutingMiddleware","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/selective\/basepath\/src\/BasePathMiddleware.php","line":52,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$229d60","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":168,"function":"process","class":"Selective\\BasePath\\BasePathMiddleware","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/middlewares\/whoops\/src\/Whoops.php","line":104,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:138$229d61","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Middlewares\\Whoops","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php","line":76,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$229d60","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\ErrorMiddleware","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$229d60","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/App.php","line":199,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/Example.com\/vendor\/slim\/slim\/Slim\/App.php","line":183,"function":"handle","class":"Slim\\App","args":[]},{"file":"\/www\/wwwroot\/Example.com\/public\/index.php","line":0,"function":"run","class":"Slim\\App","args":[]}]}}

**Comment by matador7495** [comment]
![image](https://user-images.githubusercontent.com/30972110/232024210-bee8a6db-09a7-42c8-8d75-5357aa580602.png)

Make sure that the permissions of the folders are set to 755.
If the problem is not solved, make a backup of the database and file for the Knowledgebase section if you have one. Then delete the site and reinstall it.

**Comment by ca3tiel** [comment]
thanks @matador7495 
i checked permissions of the folders and all of them is 755
i was reinstall it before and the issue was solved and i make notice but now after some days i cant change or edit notices because of this issue.
i have some user and i worry about loosing them..so i cant reinstall it...
do u think this error comes from database ?!
