### ISSUE TITLE
gift card bug

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#159]
hello gift card have bug 
![222](https://user-images.githubusercontent.com/123809903/231425527-db0d5730-521f-4945-bf48-57f61560f098.png)
![sss](https://user-images.githubusercontent.com/123809903/231425541-53935381-8979-4f6d-a21c-66b1eab2efe1.png)

**Comment by xcode75** [comment]
There is no bug. Do not open an issue claiming there is a bug when you do not know that for sure. You have set user Limit to 1 and saying there is a bug.
