### ISSUE TITLE
WS/gRPC & SNI through CDN (Cloudflare)

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XManagerPlus#16]
To cover "server IP" we use CDN like Cloudflare. If we use a different server address than SNI that uses Cloudflare like "discord.com" also we can cover the "server address" from the filtering system too!
In the XMPlus frontend panel, we can't set a different server address than SNI (server name in security settings) while Cloudflare DNS and Cloudflare CDN are "enable" so there is an error "Cloudflare: Cloudflare Zone not found" because the address that we want to use for cover is not set in CF zones and there must set it manually to a third-party app that we want to connect through them like v2rayN or Nekoray or etc. With that manual change, we can get connected through profiles that are made by the X-UI panel.

I tried to set a different server address than SNI with and without CDN manually in third-party apps and I got the results below:
- gRPC+TLS+SNI+with CDN: does not work
- gRPC+TLS+SNI+without CDN: does not work
- WS+TLS+SNI+with CDN: works!

+ How is it possible to make a different server address than SNI in gRPC+TLS+SNI+with CDN config like what is happening in WS+TLS+SNI+with CDN?
+ Is it possible to add an option about using a different server address than SNI through CDN to cover address filtering chance?

**Comment by dadashali61** [comment]
I must mention in gRPC+TLS+SNI+without CDN config that is possible to enter a different server address than SNI but it does not work.

**Comment by xcode75** [comment]
You need to set rejectunknownsni to false, and maybe allowinsecure to true

**Comment by xcode75** [comment]
Yes can use different server address, i use cpanel.com

**Comment by dadashali61** [comment]
I set "rejectunknownsni to false" and  "allowinsecure to true" and server address to "cpanel.com"but I got error again "Cloudflare: Cloudflare Zone not found."
The matter will be ignored if I set both Cloudflare DNS and CDN to "disable".
