### ISSUE TITLE
User search 

### ISSUE THREAD

**Issue by mimuala** [xcode75/XManagerPlus#160]
The user search section is sensitive to uppercase and lowercase letters, this makes it difficult for the user to search 
![Uploading Screenshot_20230414-102627~2.png…]()

**Comment by HamrahVIP** [comment]
Another problem with the search is that the user's full name must be written in order to find the user

**Comment by matador7495** [comment]
Yes, unfortunately, the search section should be a little smarter and with better features.

**Comment by mohammadoaaakd** [comment]
also When logging in, the user must also be careful to enter the email in upper and lower case letters

**Comment by bahramini** [comment]
same problem

**Comment by xcode75** [comment]
fixed
