### ISSUE TITLE
help me to fix error :((

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#161]
![image](https://user-images.githubusercontent.com/28225346/232326955-8b884a0c-cbf0-480c-9749-3cb471b9d299.png)

**Comment by subzero9319** [comment]
after upgrade to v20230416 all new user got EOF error

**Comment by ca3tiel** [comment]
@subzero9319
hi
1. check your TLS certificate file first
2. check your devices date/time.. that's just happened to user from iran

**Comment by subzero9319** [comment]
> @subzero9319 hi
> 
> 1. check your TLS certificate file first
> 2. check your devices date/time.. that's just happened to user from iran

solved after update to v20230417
my backend is XrayR

**Comment by payeh** [comment]
`app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://mci.ircf.space/xmplus):  > dial tcp: lookup mcih3.sitebaz.top: operation was canceled] > common/retry: all retry attempts failed`

**Comment by payeh** [comment]
`2023/04/18 04:04:04 [Warning] [4155160602] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:64219: wsasend: An established connection was aborted by the software in your host machine.`

**Comment by payeh** [comment]
> @subzero9319 hi
> 
> 1. check your TLS certificate file first
> 2. check your devices date/time.. that's just happened to user from iran

help me
