### ISSUE TITLE
Issue with config file when u add your domain 

### ISSUE THREAD

**Issue by BroF01** [xcode75/XManagerPlus#162]
Hello there after I add my domain and doing the necessary Chages, I need to change the conf file in conf folder but there is no web site address to modify and when I add the line and do the rest of configure in the seating u can't find URL site option!

**Comment by xcode75** [comment]
config.php SubUrl

**Comment by BroF01** [comment]
he there i did config the suburl as u mention but still i dont get the site url in xmplus panel 
![pic xmplus](https://user-images.githubusercontent.com/130934169/233218782-6addfe01-4e3b-4095-8628-52b077b22093.PNG)
![pic 2](https://user-images.githubusercontent.com/130934169/233218784-fd8321c8-246d-489b-b1e2-b4be7ef8d75e.PNG)

**Comment by BroF01** [comment]
i have add my domain in the  sub suburl like this "https://domain.com"; and still i got nothing after when i want use the xmplus as u see in the pic
