### ISSUE TITLE
notifications problem

### ISSUE THREAD

**Issue by m0000hamad** [xcode75/XManagerPlus#164]
hello

Notifications for users by e-mail or telegram are problematic
For example, the invoice is not sent to the user after the purchase.
Or,  if the user login notification was active,Reminder of expiration date or subscription traffic, neither  will be sent  notified in user Telegram or email.

I downgraded to version v20230301 for testing and this problem was solved.
my panel is v20230417

Please check these items

**Comment by localroot4** [comment]
I have the same problem

**Comment by xcode75** [comment]
> hello
> 
> Notifications for users by e-mail or telegram are problematic For example, the invoice is not sent to the user after the purchase. Or, if the user login notification was active,Reminder of expiration date or subscription traffic, neither will be sent notified in user Telegram or email.
> 
> I downgraded to version v20230301 for testing and this problem was solved. my panel is v20230417
> 
> Please check these items

Did you read and update when v20230324 was release if not go and check the update notice

**Comment by m0000hamad** [comment]
i 

> > hello
> > Notifications for users by e-mail or telegram are problematic For example, the invoice is not sent to the user after the purchase. Or, if the user login notification was active,Reminder of expiration date or subscription traffic, neither will be sent notified in user Telegram or email.
> > I downgraded to version v20230301 for testing and this problem was solved. my panel is v20230417
> > Please check these items
> 
> Did you read and update when v20230324 was release if not go and check the update notice

I installed the latest version on another Linux server from the beginning. Do I need to edit the codes again?
