### ISSUE TITLE
روش تانل زدن سرور های ایران به ایکس ام پلاس

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#166]
چطور با روش اصولی میشه سرور های ایران تانل زد به ایکس ام پلاس در این خصوص دوستان روشی که جواب بده رو با توضیحات کامل بش اشتراک بزارین ممنون میشم 
 به امید آزادی

**Comment by mimuala** [comment]
توی داکیومنت بهش اشاره شده

Backend Transit(Relay) Client -> Node A -> Node B -> Destination(www.google.com)
NOTE:

To use transit both servers must be working normally and be able to connect directly.

Node B cannot use nginx reverse proxy and lsitening ip 127.0.0.1

Node A and B must have the XMPlus backend installed

Node A -> Transit Type -> XMPlus backend

Node A -> Transit Server -> select target Node B

**Comment by mimuala** [comment]
دو سرور ایران و خارج رو باید کانفیگ کنید
بعد در بخش ترانزیت سرور ایران ،سرور خارج رو انتخاب کنید

![Picsart_23-04-18_16-25-45-822](https://user-images.githubusercontent.com/23650020/232784209-f2c509a2-f482-42bf-a6dc-04394cfb7c99.jpg)

**Comment by xcode75** [comment]
Only english language allowed
