### ISSUE TITLE
Telegram group for Iranians (unofficial)

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#169]
With permission from the XMPLUS owner @xcode75 
I am planning to start a Telegram group for Iranians who use XMPLUS, so that problems and questions can be solved there with the help of each other, as well as knowledge transfer.
Dear friends, please note that this group is completely unofficial and is not managed by the XMPLUS owner @xcode75 .
This group has strict rules to maintain security.
Rules:
1- Your Telegram account must be completely anonymous and your identity information must remain hidden.
2- No one should post their server configuration in the group.
3- Don't disrespect other members.
4- Avoid sending inappropriate messages.
5- Having basic knowledge of starting XMPLUS
Things that will be discussed in this group:
1- Exchange of opinions about the best XMPLUS settings and methods that work in Iran.
2- Problems that are not related to XMPLUS programming and were only observed in your panel. (Items related to programming will be tracked through GitHub)

I ask the manufacturer not to close this item for a while.

The address of the XMPLUS Persian Telegram group:
https://t.me/+iIdlRaK90tY5MTlk

با کسب اجازه از سازنده @xcode75 
من قصد دارم یک گروه تلگرامی برای ایرانیانی که از XMPLUS استفاده می کنند راه اندازی کنم تا در آنجا با کمک یکدیگر به مشکلات و سوالات و همچنین انتقال دانش پرداخته شود.
دوستان عزیز توجه فرمایید این گروه کاملا غیر رسمی بوده و از طرف سازنده مدیریت نمی شود.
این گروه برای حفظ امنیت قوانین سخت گیرانه ای دارد .
قوانین:
۱- اکانت تلگرام شما باید کاملا ناشناس باشد و اطلات هویتی شما باید مخفی بماند.
۲- هیچ کس نباید در گروه کانفیگ سرور خود را ارسال کند.
۳- بی احترامی به دیگر اعضا انجام نشود.
۴- از ارسال پیام های غیر مرطبت پرهیز شود.
۵- داشتن دانش ابتدایی راه اندازی XMPLUS
مواردی که در این گروه راجب آنها صحبت خواهد شد:
۱- تبادل نظر در مورد بهترین تنظیمات و روش های ایکس که در ایران کار می کند.
۲- مشکلاتی که مربوط به برنامه نویسی XMPLUS نیست و فقط در پنل شما مشاهده شده است. ( مواردی که مربوط به برنامه نویسی هستند از طریق گیت هاب پیگیری خواهند شد)

از سازنده خواهشمندم این مورد را برای یک مدت نبندد.

آدرس گروه تلگرامی XMPLUS فارسی:
https://t.me/+iIdlRaK90tY5MTlk

**Comment by xcode75** [comment]
Sorry, ads not allowed here.
