### ISSUE TITLE
Like the Proxifier

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XManagerPlus#17]
Is it possible to limit users to only tunneled for specified softwares (in windows) similar to what the Proxifier does?
Or limit to specified IPs? Or limit to domains?

**Comment by xcode75** [comment]
Limited by IPs connected

**Comment by dadashali61** [comment]
I see but i mean the source IP not users IP who connect to server. Anyway you can ignore that IP option. How about limitation by software and domains?

**Comment by xcode75** [comment]
no does not support
