### ISSUE TITLE
Please add tutorial about Fallback Config

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#173]
hi every one
please explain and add tutorial about fallback config
when we need to use fallback?
and how to config it?
Thanks
![Screenshot](https://user-images.githubusercontent.com/122527892/233858303-9f0e6df8-b5fa-452b-a886-9b0a6913c4d8.png)

**Comment by JobberRT** [comment]
https://xtls.github.io/en/config/features/fallback.html#fallbackobject

Here's Project X official document for Fallback, XManagerPlus is the same configuration except it change json to a form
