### ISSUE TITLE
The issues and problems of the panel

### ISSUE THREAD

**Issue by mhosseint** [xcode75/XManagerPlus#174]
Hello there,
The issues and problems of the panel are as follows:

1- If possible, please put a background image for the login page. And the color of the forgotten password link should be black. Also, please make the appearance of the user login page the same as the admin login page.

2- Please add this feature so that we can change the color of the panel and sidebar.

3- Please change the font of the software title in the user panel to make it more beautiful. Also, change the font of small titles such as link copy and gift card. In the following screenshots I specified:
https://s8.uupload.ir/files/screenshot_2023-04-24_at_1.06.31_pm_0nzf.png
https://s8.uupload.ir/files/screenshot-2023-04-27-at-1.05.13-am_vw8y.png

4- Please add this option so that it is possible to change the profile picture for admin and user. And if this is not possible, please set the default profile picture to a dummy photo.

5- Please make it possible to display the title of the user group in the list of users.

6- Please write a message to the user when the server page is empty that there is no server to display. And please write a message to the user when the subscription page is empty that there is no subscription to display. And please add this option so that we can show a custom message to the user if the subscription page is empty.

7- There are two very important bugs. In the panel of a user who does not have admin access, when he clicks on the servers, the qr code is not displayed. Also, when the user's traffic limit or expiration date ends, the user's connection will not be disconnected and it will remain connected forever for the user as long as he is connected. And this is very dangerous because the user may exceed the defined limit for usage. The user should be disconnected immediately and even if we disable the user manually, the connection should be disconnected instantly. Please fix it.

8- Please fix the additional traffic function. When a user purchases additional traffic, the amount must be added to their original subscription. And his plan will not change. And the user can buy as much additional traffic as he wants and it does not include the Reset Days of the original subscription unless he has additional Reset Days traffic. And after the end of the main subscription period, his additional traffic will also run out and he needs to renew or change the main subscription plan again. Also, the subscription change button in the user panel does not work and nothing happens when clicking on it.

9- And most importantly, when we set the price of the subscription plans to zero, instead of displaying the number, write the subscription price for free. And it is also possible that we can hide the subscription from the user's view and only add it manually for the user.

10- Please add this feature so that admin and support can send tickets to specific users.

11- Please add this option so that we can send notifications to specific groups. And it is also possible to send to everyone. And please put the possibility of displaying the title of the notice in the admin and user panel. Please write a message to the user when the notices page is empty that there is no notice to display. And please fix the problem of the date and notice text sticking to the beginning of the icon in the user panel.
https://s8.uupload.ir/files/screenshot_2023-04-25_at_12.30.10_pm_78dy.png

12- Please change the title of these two pages to (حفظ حریم خصوصی) and (شرایط استفاده از خدمات) in the Farsi language in the admin and user panels. And also, please fix the problem of the appearance of the separator in the user panel. In the following screenshot I specified:
https://s8.uupload.ir/files/screenshot_2023-04-25_at_1.17.18_pm_gzge.jpg

13- Please, when we choose the currency and payment for Iran, it is possible to choose Toman currency. In Iran, the Toman currency is used more because it is more convenient. Also, please remove the decimal numbers.

14- Please add the ability to select Iran's solar date for Farsi language. Also, please have the option to change the clock to the country time.

15- Please add this feature in the panel settings so that it is possible to hide the menus that we do not use in the admin panel.

16- In the accounts section, when we want to delete a shared account, the deletion confirmation is not translated in different languages, and in Farsi it is still English. Please write a message for the user when the shared account page is empty, that there is no shared account to display.

17- Please change the title of the menus in the user panel in Farsi to Farsi. In the following screenshot I specified:
https://s8.uupload.ir/files/screenshot_2023-04-24_at_1.07.22_pm_bvlo.png

18- Please develop the invitation feature for different languages. And please add the possibility to write Payout Note for different languages. Also, for Iranian users, please add the possibility of receiving a bank card number for depositing money.

19- Please add this option in the panel settings so that it is possible to place a separate copyright text. And it is also possible to place the logo for the login page and inside the panel separately.

20- Please add this option on the servers page so that we can choose whether the ping is taken from the address or from the IP. Because we may use the domain that CDN has for the server address and not see the server during the main ping.

Thanks.

**Comment by mohammadoaaakd** [comment]
this is 60$ panel not 500$

**Comment by mhosseint** [comment]
The things I posted are just bugs and minor problems. I did not submit any customization requests outside of the panel facilities.

**Comment by xcode75** [comment]
okay, i will check which has a bug and fix them. Thanks

**Comment by matador7495** [comment]
دوست عزیز بخشی از عملکرد ها و درخواست های شما الان در حال حاضر به درستی کار می کند اما بخشی هم کاملا حق با شماست .
مثل بهبود UI صفحه ثبت نام و لاگین - تغییر رنگ پس زمینه و آیتم ها - ارسال اطلاعیه با قابلیت شخصی سازی 

اما بخش ترافیک اضافه من تست کردم مجدد تاریخ و ترافیک مصرفی ریست نمی شود بلکه ترافیک خریداری شده به ترافیک کل اضافه می شود .

اشتراک رایگان در بخش تنظیمات وجود دارد و نیاز نیست اشتراک با قیمت 0 ایجاد کرد.

بخش یادداشت به زبان های مختلف برای پلن ها وجود دارد  و همچنین در همان بخش شماره کارت هم می توانید قرار بدید ، استعلام واریز کارت به کارت که امکان پذیر نیست تا نیاز باشه یک پلاگین جدا نوشته بشه در همان بخش توضیحات اشتراک شماره کارت را ثبت کنید.

عبارت های حریم خصوصی و شرایط استفاده کاملا درست هست از نظر اصول نوشتاری فقط / جدا کننده مشکل دارد.

در صفحه کاربر در بخش سرور ها بارکد به درستی نمایش داده می شود و مشکلی هم نداشت.
لوگو صفحه لاگین و داشبورد هم از همان تنظیمات قابل تغییر، شما 2 عکس متفاوت انتخاب کنید متوجه میشید.

و خیلی از درخواست ها دیگه واقعا بومی سازی بود.

-----------------------------
Dear friend, some of your functions and requests are currently working correctly, but you are completely right.
Such as improving the UI of the registration and login page - changing the color of the background and items - sending notifications with the ability to personalize

But I tested the additional traffic section, the date and traffic consumption is not reset, but the purchased traffic is added to the total traffic.

There is a free subscription in the settings section and there is no need to create a subscription with a price of 0.

There is a note section in different languages for the plans, and you can also put the card number in the same section, a card-to-card deposit inquiry that is not possible, so a separate plugin needs to be written in the same section to register the card number. do.

The terms of privacy and terms of use are completely correct in terms of written principles, only / separator has a problem.

On the user page in the servers section, the barcode is displayed correctly and there was no problem.
The logo of the login page and the dashboard can be changed from the same settings, you can choose 2 different photos and you will understand.

And many other requests were really localization.

**Comment by mhosseint** [comment]
Apparently, you didn't read the submitted items carefully or you didn't test the panel carefully.
I tested the items several times one by one in several different ways and modes and finally prepared this list.
The function of additional traffic is not correct and by purchasing additional traffic, it changes the user's original subscription and the user will not be able to purchase additional traffic again.
In the panel of a user who does not have admin access, when he clicks on the servers, the qr code is not displayed.

**Comment by matador7495** [comment]
Yes you are right
