### ISSUE TITLE
subscribe links

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#176]
![image](https://user-images.githubusercontent.com/30972110/234512095-9e5e4c1e-b920-472e-8f48-68395da313f3.png)

For some customers, the sub link does not work in any of the software and gives this error. What is the cause and how can it be fixed?

(v20230402)

**Comment by xcode75** [comment]
enable debug, copy link to browser and will see error log and paste here

**Comment by matador7495** [comment]
![image](https://user-images.githubusercontent.com/30972110/234533521-4d723276-fe2d-453f-8969-31ead17e1b2b.png)

According to the error that occurred, I guess the problem is with the email, what is the solution?

**Comment by xcode75** [comment]
Alter batabase table for subscribe_log with below command in sql

![image](https://user-images.githubusercontent.com/87862554/234544631-ad641e7b-676a-44cc-afc1-48ec7be4d275.png)


ALTER TABLE `subscribe_log` CHANGE `email` `email` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
