### ISSUE TITLE
TRX

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#177]
![image](https://user-images.githubusercontent.com/30972110/234559210-9dde0e1e-abd7-4fd3-b645-0574d346e497.png)

After 15 minutes, nothing happened and the transaction was cancelled.
I reported this problem last time.
What is the solution?

**Comment by matador7495** [comment]
![image](https://user-images.githubusercontent.com/30972110/234712966-0d96b516-15d7-45b6-a60f-f57047f1e8d7.png)

I enabled ENV['debug'] and opened the NotifyURL link in the browser and got this error.

**Comment by ArashPersian** [comment]
درود برای این روش شما باید از کیف پولتون چک بکنید و به صورت دستی تائید کنید.

**Comment by matador7495** [comment]
عزیز دستی چیه دیگه این روش اتوماتیک هست من قبلا چند نسخه قبل برای تتر استفاده میکردم الان هیچ تفاوت خاصی ایجاد نشده

**Comment by ArashPersian** [comment]
من آدرس ولتم رو داخلش گذاشتم و هیچوقت اتومات تائید نمیشد و همیشه بایستی به صورت دستی تائیدش میکردم اگه اتومات بشه که عالیه .
عزیز ایرادی نداره آیدی تلگرامتون رو داشته باشم ی سوال در مورد nginx داشتم من از خیلی وقت پیش که پاسخ دادین هنوز درگیرشم .

> عزیز دستی چیه دیگه این روش اتوماتیک هست من قبلا چند نسخه قبل برای تتر استفاده میکردم الان هیچ تفاوت خاصی ایجاد نشده

**Comment by xcode75** [comment]
fixed
