### ISSUE TITLE
Trojan Problem

### ISSUE THREAD

**Issue by ArashPersian** [xcode75/XManagerPlus#184]
hello friends
I have three node trojans on my first server and they work correctly, but on my second server, when I tried to create a trojan, I can't connect without any error from the server side, and it throws a 503 error in the program. Does anyone know a solution?

I have exactly the same problem in nginx and it does not connect from the server side without an error.

**Comment by subzero9319** [comment]
Check your nginx .conf file

**Comment by ArashPersian** [comment]
> Check your nginx .conf file
سلام داداش طبق اون تاپیک قبلی که باز کرده بودم و راهنمایی کرده بودی فرمتش دستم اومد و کامل مثل همون درست کردم هیچ اروری هم نگرفتم اما باز کانکت نشد الان حتی مثل کانفینگای قبلی رو سرور جدید که  تروجان درست میکنم اونم کانکت نمیشه فکر کنم باگی چیزیه حتی پورت و اسم و همه چیشم عوض کردم که اختلال بینشون پیش نیاد.

Hi bro, according to the previous thread that I had opened and you gave me the advice, I got the format and I made it completely like the same, I didn't get any error, but it didn't connect again, now even like the previous Confinga, I make a new server that has a Trojan, and it doesn't connect, I think it's a bug. I even changed the port, name and everything so that there is no disturbance between them.

**Comment by ArashPersian** [comment]
> Check your nginx .conf file
#56

ی سری عکس هم دیروز از کانفینگ nginx ام تو این تاپیک گذاشتم  آخراشه .
