### ISSUE TITLE
all of the servers goes down

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#185]
hi dear
when i upgrade my panel tp version v20230504 all of the configs goes down and ping test in clash is timeout 

so now i downgrade panel version but iwant to need how can i solve this problem on v20230504 version of panel?

**Comment by lostsoul6** [comment]
my configs are working after upgrade however , my online users number has gone down from 70 to 20 . I'm worried something is wrong that I don't know about it .

**Comment by subzero9319** [comment]
New update will be release tomorrow
Don't be worry

**Comment by lostsoul6** [comment]
@subzero9319 you facing issues as well ? did you talk to the coder ?

**Comment by subzero9319** [comment]
> @subzero9319 you facing issues as well ? did you talk to the coder ?

Yeah
I encountered some issues
But I downgraded it to v20230417
Wait until tomorrow

**Comment by xcode75** [comment]
> hi dear when i upgrade my panel tp version v20230504 all of the configs goes down and ping test in clash is timeout
> 
> so now i downgrade panel version but iwant to need how can i solve this problem on v20230504 version of panel?

you have to manually change in database, settings table  version

**Comment by shadow-vpn** [comment]
> > @subzero9319 you facing issues as well ? did you talk to the coder ?
> 
> Yeah I encountered some issues But I downgraded it to v20230417 Wait until tomorrow

hi
can u solve problem on panel version v20230505?

**Comment by subzero9319** [comment]
> > > @subzero9319 you facing issues as well ? did you talk to the coder ?
> > 
> > 
> > Yeah I encountered some issues But I downgraded it to v20230417 Wait until tomorrow
> 
> hi can u solve problem on panel version v20230505?

Not yet bro
Nodes are not even connected in admin account
But the account of some users works without problems

**Comment by subzero9319** [comment]
i have to downgrade v20230329
now it's ok
