### ISSUE TITLE
Frontend error after updating

### ISSUE THREAD

**Issue by amahdevar** [xcode75/XManagerPlus#186]
Hi, after updating to v20230504 i get this issue when trying to load settings and dashboard on admin page. PS: v20230505  didn't solve this neither  "php xmplus telegram delete". 
![error](https://user-images.githubusercontent.com/110831292/236459977-6b6c9791-7740-4b79-ba5f-a27fa1a96bc7.png)

**Comment by xcode75** [comment]
you skipped some updates and just updated tp latest version, that is your fault and not blame update.  Is a missing database entry. you can manually insert in database-> settings table  telegram_url, it should be yout site hrrps address
