### ISSUE TITLE
server offline / online notifications on telegram every 5 minutes

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#187]
Since I updated to v20230505, exactly every 5 minutes I am getting random notifications on telegram bot about some servers that went offline and some that went online!
any one else?
![image](https://user-images.githubusercontent.com/35190548/236588942-568e9ed4-039b-41b0-835d-73394c061f5d.png)

**Comment by amihos** [comment]
I just noticed that these thigns are also hapening in the servers section of the admin panel:

some servers suddenly show that there are 0  people online:
![image](https://user-images.githubusercontent.com/35190548/236614909-82feaedd-bf9e-4523-a414-6b66dc19bff9.png)

and then some servers are shown red (disconnected)
![image](https://user-images.githubusercontent.com/35190548/236614969-ad78d28d-2dab-4b00-9c23-af76ce60c42a.png)

these are also totally random. If you refresh the page then most probably these get fixed and some other servers become like this.

**Comment by Zo0oX** [comment]
and  for me after last update same problem

> Since I updated to v20230505, exactly every 5 minutes I am getting random notifications on telegram bot about some servers that went offline and some that went online! any one else? ![image](https://user-images.githubusercontent.com/35190548/236588942-568e9ed4-039b-41b0-835d-73394c061f5d.png)

**Comment by Zo0oX** [comment]
any one  here can fix this problem ?

**Comment by lostsoul6** [comment]
+1

I have same issues . servers suddenly show offline status . it's random . a refresh of page sometimes fixes it .

**Comment by Zo0oX** [comment]
just go to each server and update xmplus from ssh

**Comment by matador7495** [comment]
Hi, I haven't updated yet, does anyone still have this problem?
Friends who updated, did you also update the XMPlus backend? Because it is mandatory.

**Comment by Zo0oX** [comment]
> Hi, I haven't updated yet, does anyone still have this problem? Friends who updated, did you also update the XMPlus backend? Because it is mandatory.

after update xmplus must to update XMPlus backend to fix this problem

**Comment by amihos** [comment]
Update: I confirm that after updating the backend to the latest version, the issue got fixed. Therefore I close this issue.
