### ISSUE TITLE
nowpayment problem

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#19]
@xcode75 
hi
 nowpayment portal has a problem and that problem is that it does not allow payment less than 32 dollars
I talked to their support and they told me that you need to fix this in API
But the API was not available for me. Thank you for doing this in an update
![Untitled](https://user-images.githubusercontent.com/124066783/215796909-3cffd8d8-3fd9-4c64-abb0-37208139fa34.jpg)

**Comment by xcode75** [comment]
Not a problem, mean you amount too small for nowpayment to allow payment

**Comment by shadow-vpn** [comment]
Thank you for your response
