### ISSUE TITLE
Bulk changes for user subscriptions

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#191]
Please add the ability to add traffic to total traffic and time to time expiration in bulk for batch or total users.

**Comment by subzero9319** [comment]
> Please add the ability to add traffic to total traffic and time to time expiration in bulk for batch or total users.
yes
in this situation we have to add time and traffic to all user

**Comment by ca3tiel** [comment]
yes..as i Sayed meny times ago and my post closed whiteout any answer [#93](https://github.com/xcode75/XManagerPlus/issues/93)

**Comment by bahramini** [comment]
you can define a free plan with desired traffic and time

**Comment by matador7495** [comment]
> you can define a free plan with desired traffic and time

فک کنم بصورت کامل متوجه درخواست بنده نشدید ساخت پلن رایگان چه ارتباطی به موضوع ما داره ؟

**Comment by bahramini** [comment]
بله شاید ۱۰۰ درصد چیزی که میخواین رو انجام نده و یه مشکلاتی داره.
مثلا میخواین به همه کاربرها ۲۰ گیگ اضافه بشه. میتونید یه پلن رایگان ۲۰ گیگ به صورت «ترافیک اضافه» تعریف کنید و بگین کاربرها برن اون اشتراک رو فعال کنن.

**Comment by subzero9319** [comment]
اره
اینو حتما پیگیری کنیم
من خودم از دیتا بیس مستقیم تاریخ اضافه کردم بهشون

**Comment by matador7495** [comment]
> اره اینو حتما پیگیری کنیم من خودم از دیتا بیس مستقیم تاریخ اضافه کردم بهشون

به چه روشی؟

**Comment by subzero9319** [comment]
> > اره اینو حتما پیگیری کنیم من خودم از دیتا بیس مستقیم تاریخ اضافه کردم بهشون
> 
> به چه روشی؟

مجبورا از داخل دیتا بیس به تاریخ ها دو روز اضافه کردم
از phpmyadmin
