### ISSUE TITLE
Repeated : UX issue in users registration section

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#192]
according to issue No.[#155](https://github.com/xcode75/XManagerPlus/issues/155)
dear @xcode75 
you was answered me : disable email restriction in admin settings. 
but i need restriction email and i cant disable that's. because : i want give my user free test account for 2 days' and if i disable restriction email they are use fake mail and never buy subscription so its impossible

why [#155](https://github.com/xcode75/XManagerPlus/issues/155) is so important?!
because is an UX issue and i never seen any website registration to use a drop down menu to restriction email and every day at least 2 new users send me messages and say that there was a problem with our email during the registration process and we cannot register (when i say 2 users send me this message, definitely many user have this problem and don't message and drop registration) and the error displayed in this case doesn't clearly explain that the error is because you used @gmail.com and you should not type that's and just select that's from drop down menu .

**Comment by kamrava** [comment]
@xcode75 We also have the same issue. Please fix this issue. We are receiving too many tickets from our users which they can not register in our website!

**Comment by ArashPersian** [comment]
> according to issue No.[#155](https://github.com/xcode75/XManagerPlus/issues/155) dear @xcode75 you was answered me : disable email restriction in admin settings. but i need restriction email and i cant disable that's. because : i want give my user free test account for 2 days' and if i disable restriction email they are use fake mail and never buy subscription so its impossible
> 
> why [#155](https://github.com/xcode75/XManagerPlus/issues/155) is so important?! because is an UX issue and i never seen any website registration to use a drop down menu to restriction email and every day at least 2 new users send me messages and say that there was a problem with our email during the registration process and we cannot register (when i say 2 users send me this message, definitely many user have this problem and don't message and drop registration) and the error displayed in this case doesn't clearly explain that the error is because you used @gmail.com and you should not type that's and just select that's from drop down menu .

yes i agree .
i have same problem with my user.
