### ISSUE TITLE
Transit Not work after update To v20230505

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#194]
Hi Dear @xcode75
After update To v20230505 And XmPlus V2.1.2 All Of My Transit Nodes Goes Down. 
And When i Returned to v20230417 Transit Nodes Works Again. 
Transit Node Type is: Vless-WS

**Comment by xcode75** [comment]
tested and works

**Comment by HamrahVIP** [comment]
> tested and works

bro there is problem in new updates, for transit, nodeA and nodeB should be on same group. if nodeA from group vip1 and nodeB from group vip2 transit not work

and all nodes shows for Admin in clinet app. but only can connect to nodes from admin's group and can not connect to nodes of other groups
