### ISSUE TITLE
can't find Toman currency in v20230505

### ISSUE THREAD

**Issue by atbax** [xcode75/XManagerPlus#200]
Hello
I updated to the latest version, but I could not find the Toman currency, and the default currency is still Rial and cannot be changed to Toman.
I also noticed that the currency section was removed from the menu.
Can you advise how to change the currency to Toman?

<img width="1440" alt="Screenshot 2023-05-13 at 02 12 38" src="https://github.com/xcode75/XManagerPlus/assets/66557955/071c6976-82f5-42cd-99d5-fdf3da8ca193">
<img width="1440" alt="Screenshot 2023-05-13 at 02 13 16" src="https://github.com/xcode75/XManagerPlus/assets/66557955/6817fd93-cbaf-4d4d-8826-2680696f13d2">

**Comment by xcode75** [comment]
toman is use in calculation in background.

**Comment by atbax** [comment]
What is the reason for toman to be calculated in the background? When all amounts are displayed in Rials in the user panel and management panel, and even when directed to the payment portal, all amounts are in Rials.
If your intention is to add Tomans, all amounts must be divided by ten in the user panel and management panel, and when directed to the payment portal, it must be multiplied by ten so that only the Riyal amount is displayed to the user in the payment portal, and in In other places, the user and administrator can see Toman
