### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by mosafa** [xcode75/XManagerPlus#206]
Dear XMPlus Developer,

I am writing to bring to your attention a problem that I have encountered recently. After updating the version of the program from v20230209 to v20230505, I found that the SSL license in Aapanel had expired. I renewed the SSL license, but I have been encountering an err_ssl_protocol_error error every time I try to connect to the internet.

It is worth noting that the configuration I had made before updating and SSL re-licensing from within Aapanel is working perfectly fine, and I am not encountering any issues. The current version I am using is v20230505, the PHP version is PHP-7.4, and the XMPlus version is the latest (although I am not sure which version it is).

I wanted to reach out to you to see if you had any suggestions on how to resolve this issue. I have been using your program for a while now, and it has been a huge help to me. I appreciate any guidance you can provide in this matter.

Thank you for your hard work and dedication in developing this program.

Sincerely,
![IMG_8497](https://github.com/xcode75/XManagerPlus/assets/13524830/476ece0e-573f-45db-82bb-7ab121e06aa1)

**Comment by xcode75** [comment]
has nothing to do with xmplus panel, issue with aapanel
