### ISSUE TITLE
Add client that support Reality for macOS and add clash.Meta config

### ISSUE THREAD

**Issue by JobberRT** [xcode75/XManagerPlus#207]
In recent update, Reality support was added. But for macOS or IOS, none of existed application support. Please add application that support clash.Meta core and its config generation. So we can subscribe config.

Client recommend:
macOS(support clash.meta): [clash-verge](https://github.com/zzzgydi/clash-verge) 
IOS(free software with paid feature): [wing-x](https://apps.apple.com/app/wings-x/id6446119727)

**Comment by JobberRT** [comment]
Looking into `/www/wwwroot/xmplus/app/Http/Controllers/User/SubController.php`
I found that XManagerPlus already support Clash.Meta config sub. But it seems that dev didn't  metion it on the wiki.

Thanks for the fanatisc project anyway, hope WiKi could update soon!

**Comment by JobberRT** [comment]
Sorry for re-opening the issue, but I found that meta config only support vless, but not reality(seems like vision is supported), I will try to implement the reality part, but my php is so bad and please add it officially

**Comment by JobberRT** [comment]
Here's working example for clash.meta(reality supported) example:

### Code
```php
 case 'vless':
                if (!in_array($item['net'], array('ws','tcp','grpc'))) {
                    break;
                }
                $return = [
                    'name'    => $item['remark'],
                    'type'    => 'vless',
                    'server'  => $item['add'],
                    'port'    => (int)$item['port'],
                    'uuid'    => $item['id'],
                    'servername'  => $item['sni'],
                    'network' => $return['network'],
                    'udp'     => true,
                    'tfo' => false,
                ];
				if (!empty($item['flow']) && $item['net'] == 'tcp') {
					$return['flow'] = $item['flow'];
				}	
		
				if(!empty($item['fingerprint'])) {
				    $return['client-fingerprint'] = $item['fingerprint'];
				}
				
				if ($item['tls'] == 'tls' || $item['tls'] == 'reality') {
                    $return['tls'] = true;    
                }
                if ($item['net'] == 'ws') {
					$return['servername'] = $item['sni'];
                    $return['ws-opts']['path']= $item['path'];
                    $return['ws-opts']['headers']['Host'] = ($item['host'] != '' ? $item['host'] : "");
                }
				if ($item['net'] == 'grpc') {
					$return['servername'] = $item['sni'];
					$return['grpc-opts']['grpc-service-name'] = $item['serviceName'];
				}
				if (!empty($item['shortid'])) {
				    $return['reality-opts']['short-id'] = $item['shortid'];
				}
				$return['skip-cert-verify'] =  ($item['verify_cert'] ? true : false);
				$return['reality-opts']['public-key'] = $item['publickey'];
                break;
```

1. Download Clash.Meta Software(such as ClashX.Meta or clash-verge) to `/www/wwwroot/YOURSITE/public/downloads`
2. Change the download url in admin panel to new installer file relative path
3. Change the subscribe indicator from `?clash=1` to `?meta=1`
4. (OPTIONAL) Update the icon HTML code with something like this: `<span class='xxx'></span>Meta Version`
5. Use this code as example(modify yourself, only test with tcp+vision+reality) in `/www/wwwroot/YOURSITE/app.Http/Schema/ClashMeta.php(case vless)`
6. (OPTINAL) If your software doesn't support `.yml` file(ClashX.Meta for example), change `/www/wwwroot/YOURSITE/Http/Controllers/User/SubController.php(line#94, where 'meta' condition is true)` from `$filename =  (new Settings)->get('SubName').'.yml';` to `$filename =  (new Settings)->get('SubName').'.yaml';`

**Comment by JobberRT** [comment]
Of course you need to restart php and nginx after fishined all the steps

**Comment by aliafshany** [comment]
Hi @JobberRT 

Would you mind telling me how I should modify this code? I mean, I know how to edit it, but I don't know which lines should be edited. 
Isn't this a template? Should I simply copy and paste it to the designated path?

**Comment by JobberRT** [comment]
@aliafshany 

Below the information could be wrong or outdated, I'm staying on older version and some of the var name has changed to my own. Updating XMPlus will override all the file you modified.

1. Go to root directory of your website and the `app/Http/Schema` inside it, for example`/www/wwwroot/YOUR_SITE/app/Http/Schema`. And open ClashMeta.php(I don't know if this file still exist)
2. Go to the `switch` code block inside `build(array $item)` function
3. Go to the `case 'vless':` code block inside `switch`
4. Edit the code logic according to my example code
5. Save the file
6. Go to `./app/Http/Controllers/User` of your website root directory and open `SubController.php`
7. Go to `getMeta($user, $opt)` function, and merge some meta-only config to `$Conf`(Code below)
8. (OPTIONAL) Inside `getMeta($user, $opt)` function, you could edit the group of clash config yaml. Just edit the `foreach ($nodes_raw as $server)` code block for node grouping.
9. Reference my last answer to see if you need any more customization.
```php
$meta = [
            'mixed-port' => 7890,
            'allow-lan' => false,
            'mode' => 'rule',
            'ipv6' => true,
            'log-level' => 'warning',
            'external-controller' => '0.0.0.0:9090',
			'dns' => [
			    'ipv6' => false,
				'enable'        => false,
				'listen'        => '0.0.0.0:53',
				'default-nameserver' => [
					'1.1.1.1',
					'8.8.8.8',
					'8.8.4.4'
				],	
				'enhanced-mode' => 'fake-ip',
				'fake-ip-range' => '198.18.0.1/16'
			],
			'proxies' => $nodes,
        ];
$Conf = [Yaml::dump(\array_merge($meta, $meta_config), 4, 1)];
```
