### ISSUE TITLE
After Update v20230515

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#208]
Hello Friend
After installing this version, the bug still appeared in the settings section of the user dashboard

![2023-05-15_17-06-38](https://github.com/xcode75/XManagerPlus/assets/38170923/bc1086d0-24d0-4d5f-b01d-a4e42219d0ac)

I also use these versions in Aapanel  6.9.69 

![2023-05-15_17-12-14](https://github.com/xcode75/XManagerPlus/assets/38170923/ad9df1dd-ea56-4ac5-8833-8e43e434c2a2)

**Comment by matador7495** [comment]
Hello, make a backup of the database and files that you have in the training section and install them from the beginning.

**Comment by sh1375** [comment]
Hi, I did this several times
I even created a new database
I think there is a problem with this version of Nginx 1.24.0
I hope it will be investigated further

**Comment by matador7495** [comment]
I have always used these versions and had no problems and even yesterday I installed the panel on a new server and it works without problems.

![Screenshot 2023-05-16 000854](https://github.com/xcode75/XManagerPlus/assets/30972110/7d31fd68-430a-4a88-9fea-28c124a82164)

**Comment by matador7495** [comment]
He is right. I tested version 1.23 and 1.24 of Nginx. When you click on settings in the user page, you get an error. But there is no problem in version 1.21 and 1.22.

@xcode75

**Comment by xcode75** [comment]
how is that related to code? is issue with nginx then

**Comment by sh1375** [comment]
> how is that related to code? is issue with nginx then

Considering that Nginx versions 1.21 and 1.22 are without problems and only in Nginx versions 1.23 and 1.24 this case is seen, I said that maybe in the related codes in the settings section of the user panel, The codes are not compatible with this version (1.23 and 1.24)
If it is possible to solve the problem with this version (1.23 and 1.24), it will be very good because the new versions of nginix have many advantages, which you can see in the link below.

http://nginx.org/en/CHANGES-1.24
