### ISSUE TITLE
problem in connecting to CDN

### ISSUE THREAD

**Issue by ehsan0github** [xcode75/XManagerPlus#21]
when I want to connect to CDN this error appears, while if I don't use CDN, I can connect.
when I use my domain address:
[Error] transport/internet/websocket: failed to dial to mydomain.domain:443 > read tcp 192.168.3.19:11528->172.67.200.145:443: wsarecv: An existing connection was forcibly closed by the remote host.
![Screenshot 2023-02-03 192229](https://user-images.githubusercontent.com/123427867/216664187-8a59d1c6-5464-483d-a0cf-cc21804085e0.jpg)

when I use direct IP's Cloudflare:
[Error] transport/internet/websocket: failed to dial to 190.93.245.213:443 > read tcp 192.168.3.19:4957->190.93.245.213:443: wsarecv: An existing connection was forcibly closed by the remote host.
![Screenshot 2023-02-03 192207](https://user-images.githubusercontent.com/123427867/216664224-e5671413-1b73-4a9a-860a-1cbeebd7ed24.jpg)
I should mention that xmplus log shows nothing and every things are OK.

**Comment by ehsan0github** [comment]
192.168.3.19
I think this IP is my problem.
![Screenshot 2023-02-03 192904](https://user-images.githubusercontent.com/123427867/216666802-86c86c4b-4399-44f9-a03d-87b4d44acd62.jpg)
![Screenshot 2023-02-03 192952](https://user-images.githubusercontent.com/123427867/216666869-88fc9ab0-3b39-4927-a937-47749ce24760.jpg)
![Screenshot 2023-02-03 193027](https://user-images.githubusercontent.com/123427867/216666914-d8368e5d-ca45-4d65-b0ad-ad5ac11e2740.jpg)
![Uploading Screenshot 2023-02-03 193132.jpg…]()

**Comment by ehsan0github** [comment]
192.168.3.19
I think this IP is my problem.
![Screenshot 2023-02-03 192904](https://user-images.githubusercontent.com/123427867/216666802-86c86c4b-4399-44f9-a03d-87b4d44acd62.jpg)
![Screenshot 2023-02-03 192952](https://user-images.githubusercontent.com/123427867/216666869-88fc9ab0-3b39-4927-a937-47749ce24760.jpg)
![Screenshot 2023-02-03 193027](https://user-images.githubusercontent.com/123427867/216666914-d8368e5d-ca45-4d65-b0ad-ad5ac11e2740.jpg)
![Screenshot 2023-02-03 193132](https://user-images.githubusercontent.com/123427867/216666949-953aa076-aaa8-4f71-93ef-3f9eaec69899.jpg)

**Comment by ehsan0github** [comment]
If CDN is different between the forend and Backend, does this problem occur?

**Comment by matador7495** [comment]
I use cdn cloudflare on vmess ws mode there is no problem in MCI isp
