### ISSUE TITLE
after update v 20230515 only persian menu in internet browser 

### ISSUE THREAD

**Issue by sasanbozorg** [xcode75/XManagerPlus#211]
Hello
After the update of version 20230515, this problem appeared in the browser and in the persian menu.
There is no problem in Google Chrome
In Android 9 and below, even with Google Chrome, only a white screen is show
![photo_2023-05-17_06-36-24](https://github.com/xcode75/XManagerPlus/assets/36858831/5938ef60-a317-44c8-94ba-edec57f428cd)
![photo_2023-05-17_06-47-54 (2)](https://github.com/xcode75/XManagerPlus/assets/36858831/f87321e2-f4e6-4477-9f82-444f1d20b6ec)
![photo_2023-05-17_06-47-54](https://github.com/xcode75/XManagerPlus/assets/36858831/78de5190-e07e-481f-97e8-4e940efa3201)

**Comment by atbax** [comment]
I have related problem too
