### ISSUE TITLE
Incorrect display of the number of online IPs [BUG]

### ISSUE THREAD

**Issue by atbax** [xcode75/XManagerPlus#220]
![IMG_5867](https://github.com/xcode75/XManagerPlus/assets/66557955/82719023-3451-4d37-b825-b2d3d5fda312)
![IMG_5868](https://github.com/xcode75/XManagerPlus/assets/66557955/a63c7ea7-853a-45f4-9396-b557546db89a)

PHP version: 7.4
   
DB version:  5.7.40
  
Panel Version:  20230515

I monitored the servers for 9 hours and connected to a server with both my phone and laptop, and during the 9 hours I refreshed, the number of this server that I posted a screenshot of was 0 and there was no change.
By the way, before my online IPs were 300 per day, but after the update, it has decreased in a very suspicious manner, because the number of my active users has not changed, and I suspect that this problem is for all servers.
Also, with each refresh, a significant number of IPs are changed in different servers
For example, a server that displays 20 IPs shows 10 IPs after refreshing and displays 20 IPs again with the next refresh.

**Comment by lostsoul6** [comment]
Are you sure you are using the latest version of the backend ( XMplus V2.1.3) ?

**Comment by atbax** [comment]
yes i'm sure . all of my server runs xmplus v2.1.3 on backend and i'm using last version of xmplus(v20230521) too
