### ISSUE TITLE
add singbox to backend and frontend [Feature Request] 

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#222]
**Feature**
please add singbox
https://sing-box.sagernet.org/
https://github.com/SagerNet/sing-box
Describe the feature you want.

**Comment by malikshi** [comment]
https://github.com/SagerNet/sing-box/issues/486#issuecomment-1496600653
Some features would be missing since can't parsing log properly. Also xmanager based on x-rayR backend

Idk if maintainer xm will support it.

**Comment by xcode75** [comment]
> **Feature** please add singbox https://sing-box.sagernet.org/ https://github.com/SagerNet/sing-box Describe the feature you want.

I do not have the time to do that, you are welcome to develope a backend that run on singbox. XMPlus is solely for xray-core features.
