### ISSUE TITLE
XMplus backend CPU usage full 100%

### ISSUE THREAD

**Issue by lostsoul6** [xcode75/XManagerPlus#226]
Hello Sir ,

I have the latest version of XMplus backend on all my servers and all of them have this problem . CPU usage on the server is 100% with only 5 clients connected ! What is the problem ? It's not on one server only . I have 10+ servers and all of them have the same problem .
See the picture : 
https://pasteboard.co/GIf6cBaazSwN.png
از دوستان اگر کسی از بک اند XMplus استفاده میکنه روی سرور لطفا با دستور top مصرف cpu رو چک کنه . اگر مشکل من که سی پی یو همیشه روی 100 درصد هست رو دارید اطلاع بدید .

**Comment by peter2186668355** [comment]
same problem

**Comment by lostsoul6** [comment]
@xcode75 any ideas on what the problem is?

**Comment by ca3tiel** [comment]
i have same issue

**Comment by lostsoul6** [comment]
anyone found the reason ?
