### ISSUE TITLE
change data and Expire limit for new register users

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#230]
hi
when new users register an accent they are get a free account for test but data limit for this default accounts is according GB and  Expire limit is according "day" but i want give them less than 1 GB and 1 day for tests
please change data limit to MB and Expire limit to hour.

note: a lot of user making account and use our service and its make servers slow and i have issue with hosting's about high bandwidth
so i want control new users 

![Screenshot 2023-06-13 235312](https://github.com/xcode75/XManagerPlus/assets/57295411/d855da76-f962-4295-9382-be0600100142)

**Comment by HamrahVIP** [comment]
you can disable register and then nobody can register and use your servers
