### ISSUE TITLE
[enhancement] Request: Deleting expired users  

### ISSUE THREAD

**Issue by letmefind** [xcode75/XManagerPlus#231]
The user list rising over time and going to make searching/finding users tough.
In order to make a lighter DB size, deleting expired users can be an option which are we doing every day now.
It'd be ideal if there was an option to "**_Delete Expired Users_**" who are expired or older in the span time.
as a workaround we run a SQL Query to fix in atm:

Exp:
`DELETE FROM `user` WHERE `expire_in` <= '2023-05-31 23:58:39' AND `data_expire_cron` = 1`

**Comment by atbax** [comment]
@letmefind can you please provide a solution to attract re-subscriptions ?
deleting is not best solution

**Comment by Dev-l0p** [comment]
This is very good
Of course, it should be an option to activate this option.
For example: 20 days after Expire user account, Delete the user.
