### ISSUE TITLE
[BUG] v20230625

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#236]
After updating to this update, I got a sql error
Unfortunately, neither the site loads nor the commands
php xmplus

Error:

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xmplus.currency' doesn't exist in /www/wwwroot/xmplus.com/vendor/illuminate/database/Connection.php:336 Stack trace: #0 /www/wwwroot/xmplus.com/vendor/illuminate/database/Connection.php(336): PDOStatement->execute() #1 /www/wwwroot/xmplus.com/vendor/illuminate/database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}() #2 /www/wwwroot/xmplus.com/vendor/illuminate/database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback() #3

**Comment by HamrahVIP** [comment]
same problem

**Comment by letmefind** [comment]
Same Problem !!!!!

**Comment by letmefind** [comment]
Is there any way to downgrade? A couple of thousands of users have been impacted

**Comment by xcode75** [comment]
Did you read the update info before updating? Manually update the database with update.sql from Update.zip

**Comment by letmefind** [comment]
Correct! Fixed now. 

The way of updating was through instructions above the site header which was not included the manual SQL update.


For who still have issue ,

1. [ Check Here](https://github.com/xcode75/XManagerPlus/releases/tag/v20230625) 
2. Second, Download the [Update.zip ](https://github.com/xcode75/XManagerPlus/releases/download/v20230625/Update.zip)and extract.
3. Go to aapanel>DataBaase (or directly open Database panel with root access).
4. Import > upload the update.sql then import .

You would be fine!

**Comment by HamrahVIP** [comment]
PHP Notice:  Undefined variable: DB in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52

Notice: Undefined variable: DB in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52
PHP Notice:  Trying to access array offset on value of type null in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52

Notice: Trying to access array offset on value of type null in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52
PHP Notice:  Undefined variable: DB in /www/wwwroot/com/app/Jobs/UpdateJob.php on line 52

Notice: Undefined variable: DB in /www/wwwroot//app/Jobs/UpdateJob.php on line 52
PHP Notice:  Trying to access array offset on value of type null in /www/wwwroot/com/app/Jobs/UpdateJob.php on line 52

Notice: Trying to access array offset on value of type null in /www/wwwroot/com/app/Jobs/UpdateJob.php on line 52
PHP Notice:  Undefined variable: DB in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52

Notice: Undefined variable: DB in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52
PHP Notice:  Trying to access array offset on value of type null in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52

Notice: Trying to access array offset on value of type null in /www/wwwroot/.com/app/Jobs/UpdateJob.php on line 52
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
- Starting Update
v20230625 - Update Successful

**Comment by letmefind** [comment]
@xcode75 
Also noticed **_Currencies_** not get update as expected . Fields `code` &   `status` were missed form update.sql file.

Manually added to fix. 

```
CREATE TABLE `currency` 
  `currency` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` text COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
```

**Comment by xcode75** [comment]
> @xcode75 Also noticed **_Currencies_** not get update as expected . Fields `code` & `status` were missed form update.sql file.
> 
> Manually added to fix.
> 
> ```
> CREATE TABLE `currency` 
>   `currency` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
>   `status` text COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
> ```

noted

**Comment by HamrahVIP** [comment]
@xcode75 
 
how to fix this error:

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1060 (42S21) at line 1: Duplicate column name 'user_group'

**Comment by poonehsabzi** [comment]
i update and after that import sql but the error still there

**Comment by sh1375** [comment]
@xcode75 

Please give more detailed advice to solve the problem

We also did a manual update
But the problem still exists

**Comment by letmefind** [comment]
Another Bug just captured.
Switch to the User page by Admins returns: "_**You do not have the permission create or make changes.**_" 
Also not able to create a default user through Users > Add users. trying to add a User Group for non-admin users also it's not an option. it's only available for admin roles.

**Comment by mimuala** [comment]
![image](https://github.com/xcode75/XManagerPlus/assets/23650020/efae227f-b0fc-4cc1-aba1-cdf9dabaebdf)

after update and import SQL file i cant access to panel , i see this

**Comment by xcode75** [comment]
![image](https://github.com/xcode75/XManagerPlus/assets/87862554/05b99cb4-f504-4683-84e4-fa406227f076)

Manually download and import update.sql to your database, should you get a duplicate column , just delete that line from the update.sql and try again. Meaning already added to database.

https://github.com/xcode75/XManagerPlus/releases/download/v20230625/update.sql

**Comment by xcode75** [comment]
> Another Bug just captured. Switch to the User page by Default Admin (sysadmin) returns: "_**You do not have the permission create or make changes.**_" (Admins defined by sysadmin can switch to the user page) Also not able to create a default user through Users > Add users. trying to add a User Group for non-admin users also it's not an option. it's only available for admin roles.
> 
> Update: ~As a workaround just added a User group with an "access to none of the permission" fix the issue atm.~ Not working
> 
> Bug+: (Crucial)
> 
> All new Users getting administrator roles either by invite registration link or by admins
> 
> Bug++: (Crucial): Any change/edit in user account such info/Money/rebat ended up to turning user to Administrator from User.
> 
> Bug+++: Online plan purchases getting errors, not sure it's related to the latest Update as it has been seen a while ago. `Warning: A non-numeric value encountered in /www/wwwroot/panel.XXXXX.com/app/Http/Controllers/User/OrderController.php on line 0`
> 
> <img alt="Screenshot 2023-06-25 at 21 41 21" width="953" src="https://user-images.githubusercontent.com/127405150/248583445-8a7be25f-3c8d-43d1-a4df-9411ec86f544.png">

if you had read the update info you would have known. that account you are using to create the user do not have user group permission. You need to allow permission by yourself.

**Comment by localroot4** [comment]
Most of the users become admin and it doesn't change in any way. What's the solution? It can't be done from the database either.

**Comment by localroot4** [comment]
![image](https://github.com/xcode75/XManagerPlus/assets/43405486/eb561bbc-365b-4ded-988f-bf527bbd73f5)
Why do most users become ADMINISTRATOR? And why can't you select a normal user group when creating a new user?
