### ISSUE TITLE
[BUG] Slim Application Error

### ISSUE THREAD

**Issue by ali-frm** [xcode75/XManagerPlus#237]
hi , After updating to the latest version, the panel settings page displays the following error

**Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

[Go Back]**

**Comment by malekjani** [comment]
سلام اگر روی صفحه داشبورد این خطا رو می گیری این تریک رو بزن فعلاً کارت راه میفته
https://example.com/admin/users

**Comment by xcode75** [comment]
https://github.com/xcode75/XManagerPlus/issues/236#issuecomment-1606835551
