### ISSUE TITLE
[BUG]error when accessing settings in admin 

### ISSUE THREAD

**Issue by dvsteam** [xcode75/XManagerPlus#238]
no access error is installed in admin

![Screenshot_2023-06-25-23-38-43-680_com android chrome-edit](https://github.com/xcode75/XManagerPlus/assets/91702958/88611d6c-633c-4541-8c7b-c8cd35888fc9)

**Comment by ali-frm** [comment]
same problem

**Comment by xcode75** [comment]
https://github.com/xcode75/XManagerPlus/issues/236#issuecomment-1606835551
