### ISSUE TITLE
[BUG] ZarinPal Gateway error after update to v20230625

### ISSUE THREAD

**Issue by banxter** [xcode75/XManagerPlus#239]
OS:  CentOS 9
  
PHP version: 7.4

Enabled Debug.

**Bug Info**

I fixed the database update issue and added missing Currency columns.
But after update, panel can't redirect to zarinpal payment gateway, and it shows error after click on Pay button.
The error is:  Zarinpal**: -9 - The input params invalid, validation error**

![photo_2023-06-26_11-44-37](https://github.com/xcode75/XManagerPlus/assets/5660024/506ef23e-e028-4d49-9080-268f0c4845dc)

I Enabled the debug in config.php, But there were no logs about this, in /www/wwwlogs/myDomain.log and /www/wwwlogs/myDomain.error.log
Am i right about the log's path?

**Comment by xcode75** [comment]
your Merchant ID maybe wrong

**Comment by banxter** [comment]
> your Merchant ID maybe wrong

i downgraded to a version before and it worked again, it just happens with the latest version v20230625.
and i checked merchand ID it was ok..

I also noticed that after update, in Admin Dashboard, sales and income numbers will be corrupted after update.

![Screenshot 2023-06-26 215745](https://github.com/xcode75/XManagerPlus/assets/5660024/968a6aae-1df5-4a6d-867a-8bf50f350ae0)

Do you or anybody know where the problem should be from or how to fix it?

**Comment by banxter** [comment]
I updated your DB update SQL code to this, and updated it manually.
is it correct?

![DB Changes](https://github.com/xcode75/XManagerPlus/assets/5660024/b9b9cb0a-424e-49a2-bc5f-e3c4748b7f0e)

**Comment by banxter** [comment]
After installing the fix v20230627, Admin Dashboard total sales numbers fixed:

![Screenshot 2023-06-27 191604](https://github.com/xcode75/XManagerPlus/assets/5660024/42acf57c-4459-4c0a-a32d-f158f07793e1)

But My main issue, the Zarrinpal Gateway error is still the same, 
My DB update code is correct?

**Comment by dashti75mo** [comment]
go to transactions>Currencies
update rates
all rates should be 0.00
and if you use iran rial >  IRR value should be 1
