### ISSUE TITLE
registeration and add new user issue

### ISSUE THREAD

**Issue by appweareonline** [xcode75/XManagerPlus#24]
When I want to create a new user or register a new user, this message shows me:
A website error has occurred: Sorry for the temporary inconvenience.
In addition, I have a license
I had no problem before

**Comment by appweareonline** [comment]
![Screenshot 2023-02-05 134005](https://user-images.githubusercontent.com/124491081/216814066-beb86380-db5a-44b3-9859-2b6ca37ceb41.jpg)

**Comment by xcode75** [comment]
enable debug in config.php and try again, then send error screenshot

**Comment by appweareonline** [comment]
![123](https://user-images.githubusercontent.com/124491081/216825748-18318029-7980-476a-9d15-b5543495ebc2.jpg)

**Comment by appweareonline** [comment]
![123](https://user-images.githubusercontent.com/124491081/216825795-affe064f-ff4b-47a6-9304-5e3395ba87a2.jpg)

**Comment by xcode75** [comment]
I suggest you delete database and use sql database from new package  v20230204, if issue still persist go to admin settings and save all settings one by one.
