### ISSUE TITLE
[BUG] v20230626

### ISSUE THREAD

**Issue by letmefind** [xcode75/XManagerPlus#240]
First of all, Thanks for new update. well done.

Just found out admins are not able to "Switch" to the user account page.  despite the necessary permission has been granted for Admin/Customer supports teams.
Basically, the User with full permission is not able to Switch to the customer page.

**Comment by xcode75** [comment]
This is not a bug, you just need to allow permission for that user group to switch to user account.

**Comment by letmefind** [comment]
Fair enough! Got that!

Reason of asking is neither Sysadmin nor Admins (administrator with full permission) can switch/move to the User Page!

 
![Screenshot 2023-06-27 at 11 19 44](https://github.com/xcode75/XManagerPlus/assets/127405150/a66878e3-6bf2-47c2-a5a1-8b5147768eee)

**_SWITCH_** button!!! not working 

![Screenshot 2023-06-27 at 11 27 36](https://github.com/xcode75/XManagerPlus/assets/127405150/1cf32fb3-1313-40ee-9dee-a866a0d56faf)
