### ISSUE TITLE
[BUG] registers order error 

### ISSUE THREAD

**Issue by mimuala** [xcode75/XManagerPlus#241]
**Environment**

Panel Version:    v20230626

**Bug Info**

When the admin registers an order, the order is registered, but an error fills page and no notification is sent to the Telegram bot.

------------

{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Trying to get property 'name' of non-object","code":8,"file":"\/www\/wwwroot\/panel.******.com\/app\/Services\/TelegramService.php","line":0,"trace":[{"file":"\/www\/wwwroot\/panel.******.com\/app\/Services\/TelegramService.php","line":0,"function":null,"class":"Whoops\\Exception\\ErrorException","args":["Trying to get property 'name' of non-object"]},{"file":"\/www\/wwwroot\/panel.******.com\/app\/Services\/TelegramService.php","line":0,"function":"handleError","class":"Whoops\\Run","args":[]},{"file":"\/www\/wwwroot .....

**Comment by xcode75** [comment]
Tested and there is no issue, either you telegram not bind well, re bind telegram bot.

**Comment by mimuala** [comment]
![image](https://github.com/xcode75/XManagerPlus/assets/23650020/f21b525e-08f5-48e8-b393-9fc058e472bc)
 
The bot is usable, I get the backup correctly, I even re bind it but still the problem persists

**Comment by atbax** [comment]
same problem

**Comment by atbax** [comment]
this issue was solved after off debug mode

**Comment by mimuala** [comment]
> this issue was solved after off debug mode
solved!
thank you for help
