### ISSUE TITLE
Error in update v20230627

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#242]
hi
everything is ok in update update v20230625 but i get fallowing php error after update v20230626  in user dashboard>>plan section>> select plan
Undefined property: stdClass::$symbol
![Screenshot 2023-06-29 131438](https://github.com/xcode75/XManagerPlus/assets/57295411/77bb28d9-e186-43ff-8535-e592bb8702a3)

also the fallowing error in admin dashboard>>transactions>>plans>>edit plans
 
![Screenshot 2023-06-29 133923](https://github.com/xcode75/XManagerPlus/assets/57295411/c5e86893-bacb-4e83-a1b2-583eda4a2444)

and fallowing error in admin dashboard>>transactions>>plans>>add plans
![Screenshot 2023-06-29 134424](https://github.com/xcode75/XManagerPlus/assets/57295411/6e63ce28-437d-4e2a-a21b-66063f5ecee1)

also i send currency and currencies table screen shot
 
![Screenshot 2023-06-29 132028](https://github.com/xcode75/XManagerPlus/assets/57295411/9dbc5e0c-68a2-4c3d-b52d-c17ffd95d791)
![Screenshot 2023-06-29 132132](https://github.com/xcode75/XManagerPlus/assets/57295411/6b4f81d7-ba6c-4101-8296-93f235ab5f38)

please help me to fix this

**Comment by atbax** [comment]
hi
turn off debug mode and this problem will be solve

**Comment by ca3tiel** [comment]
yes..its solve but TRX getaway doesn't work and show this message :  { "message": "Slim Application Error" }

**Comment by xcode75** [comment]
> yes..its solve but TRX getaway doesn't work and show this message : { "message": "Slim Application Error" }

remove, check update notice
