### ISSUE TITLE
[BUG] Total traffic changes to zero

### ISSUE THREAD

**Issue by Dev-l0p** [xcode75/XManagerPlus#246]
Hello @xcode75 ,
It has been a long time since there is an annoying bug in the system and the user's total traffic is automatically changed to zero and the user cannot connect to the servers.
Please check this issue.

Special thanks

**Comment by mimuala** [comment]
same problem in One time Plan orders

**Comment by xcode75** [comment]
There is no bug, do not open an issue if you cannot provide good explanation. Of course user traffic will reset to 0 once purchase expire.

**Comment by Dev-l0p** [comment]
No, Purchase not expired but traffic reset to 0
