### ISSUE TITLE
[BUG] daily traffic used

### ISSUE THREAD

**Issue by ali-frm** [xcode75/XManagerPlus#247]
hi
In the latest version، the daily traffic of users is shown equal to the total traffic.
![IMG_20230708_005654_119](https://github.com/xcode75/XManagerPlus/assets/44420340/629bdbca-5dad-454a-a84d-85d8c6e28de1)

**Comment by xcode75** [comment]
not a bug, a cronjob mistake by me , just run ssh command: crontab -e

add `cd `to your cron script.

example,  * * * * * cd /www/wwwroot/tld.com && /usr/bin/php xmplus job:run >> /dev/null 2>&1

**Comment by ali-frm** [comment]
In the last version of today's presentation، this is essential.?
