### ISSUE TITLE
[BUG] I cannot add or modify node information after updating to  v20230708

### ISSUE THREAD

**Issue by Bigbrother84844** [xcode75/XManagerPlus#249]
Panel Version:    v20230708

**Bug Info**

Help, I cannot add or modify node information after updating to  v20230708. I clicked the save button to save the server configuration, but it didn't work.

**Comment by stuxnxt** [comment]
> Panel Version: v20230708
> 
> **Bug Info**
> 
> Help, I cannot add or modify node information after updating to v20230708. I clicked the save button to save the server configuration, but it didn't work.

Same issue, In 'add server' tab, save button doesn't work

**Comment by xcode75** [comment]
updated
