### ISSUE TITLE
zarinpal peyment bug 

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#25]
There is no problem with the first purchase

But when the gig volume runs out

To buy again
This gives an error
![aaa](https://user-images.githubusercontent.com/123809903/216837584-379ef09e-db41-4edc-8543-1813d86bf157.png)
![bbb](https://user-images.githubusercontent.com/123809903/216837589-ef8026db-ca2b-40a2-a4aa-b30381543660.png)

**Comment by mohammadoaaakd** [comment]
for renew payment is successful and not have any problem

![22](https://user-images.githubusercontent.com/123809903/216961738-8987fb7e-96ae-457f-9674-36bb9c120724.png)

but when i want to {disable active plan} and im Payment is made given eror 

![33](https://user-images.githubusercontent.com/123809903/216962482-df97e651-d889-4234-ab7b-4e987c9a4cb4.png)

**Comment by xcode75** [comment]
noted

**Comment by mohammadoaaakd** [comment]
confirm plan manual bug my member cant active plan for eror and i cant active plan for manual bug
![asdsd](https://user-images.githubusercontent.com/123809903/217344451-ebdb553f-cde7-4133-9601-94b2056fe096.png)


![saxzx](https://user-images.githubusercontent.com/123809903/217344497-d2fbd612-310a-4372-abb8-c4e0294ab878.png)

**Comment by mohammadoaaakd** [comment]
thank you for update
