### ISSUE TITLE
[BUG] Update v20230710 and Suggestions for Permissions User Group

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#252]
Hi Friend
Thanks for the recent updates that fixed many problems🙏🌹
In the last update, I noticed a bug about using user traffic
The amount of daily traffic consumption is very high and also when you sort it, it is not sorted properly

![image](https://github.com/xcode75/XManagerPlus/assets/38170923/bf512bd2-742e-434e-97c5-a00676e3af28)

I also reinstalled the panel and ran into some problems
First, the automatic backup system does not send backup files via email or telegram
Secondly if you have any advice please tell me that MySQL service is automatically disabled in Aapnel and the server needs to be restarted to start the service.

Suggestions for User Group:
1)
Also, in the User Group section, there is no option to specify access to shared accounts in
User Group --> Edit User Group --> Permissions  --> please add admin-shared accounts
2)
in the User Group section, if the admin-dashboard option is unchecked, it is no longer possible to see other sections
3)
if there is a special access for users in each Server Group in the User Group Permissions section, it will be much more useful, So that there is no access, including: viewing information or editing and deleting for users of other server groups

**Comment by ali-frm** [comment]
For about 48 hours, I have same problem sending a backup to the Telegram bot.

**Comment by xcode75** [comment]
> Hi Friend Thanks for the recent updates that fixed many problems🙏🌹 In the last update, I noticed a bug about using user traffic The amount of daily traffic consumption is very high and also when you sort it, it is not sorted properly
> 
> ![image](https://user-images.githubusercontent.com/38170923/252160358-bf512bd2-742e-434e-97c5-a00676e3af28.png)
> 
> I also reinstalled the panel and ran into some problems First, the automatic backup system does not send backup files via email or telegram Secondly if you have any advice please tell me that MySQL service is automatically disabled in Aapnel and the server needs to be restarted to start the service.
> 
> Suggestions for User Group: 1) Also, in the User Group section, there is no option to specify access to shared accounts in User Group --> Edit User Group --> Permissions --> please add admin-shared accounts 2) in the User Group section, if the admin-dashboard option is unchecked, it is no longer possible to see other sections 3) if there is a special access for users in each Server Group in the User Group Permissions section, it will be much more useful, So that there is no access, including: viewing information or editing and deleting for users of other server groups

check your cron script there maybe an issue with it, daily used traffic not resetting   https://github.com/xcode75/XManagerPlus/issues/247#issuecomment-1627429406

**Comment by 0nec1ick** [comment]
> > Hi Friend Thanks for the recent updates that fixed many problems🙏🌹 In the last update, I noticed a bug about using user traffic The amount of daily traffic consumption is very high and also when you sort it, it is not sorted properly
> > ![image](https://user-images.githubusercontent.com/38170923/252160358-bf512bd2-742e-434e-97c5-a00676e3af28.png)
> > I also reinstalled the panel and ran into some problems First, the automatic backup system does not send backup files via email or telegram Secondly if you have any advice please tell me that MySQL service is automatically disabled in Aapnel and the server needs to be restarted to start the service.
> > Suggestions for User Group: 1) Also, in the User Group section, there is no option to specify access to shared accounts in User Group --> Edit User Group --> Permissions --> please add admin-shared accounts 2) in the User Group section, if the admin-dashboard option is unchecked, it is no longer possible to see other sections 3) if there is a special access for users in each Server Group in the User Group Permissions section, it will be much more useful, So that there is no access, including: viewing information or editing and deleting for users of other server groups
> 
> check your cron script there maybe an issue with it, daily used traffic not resetting [#247 (comment)](https://github.com/xcode75/XManagerPlus/issues/247#issuecomment-1627429406)

The cron service works perfectly

Redirecting to /bin/systemctl status crond.service
● crond.service - Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/crond.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-07-09 14:11:26 +0330; 2 days ago
 Main PID: 1221 (crond)
   CGroup: /system.slice/crond.service
           └─1221 /usr/sbin/crond -n
You have new mail in /var/spool/mail/root

**Comment by xcode75** [comment]
I never said check your cron service

**Comment by 0nec1ick** [comment]
> I never said check your cron service

I misunderstood what you meant
If possible, tell me what is meant by cron script
How should I check and fix the problem?

**Comment by xcode75** [comment]
> > I never said check your cron service
> 
> I misunderstood what you meant If possible, tell me what is meant by cron script How should I check and fix the problem?
> 
> I completely agree with you, as if the daily traffic is not reset

https://github.com/xcode75/XManagerPlus/issues/247#issuecomment-1627429406

**Comment by 0nec1ick** [comment]
> 

Thank you friend
Problem solved, just check why there is no cd command (cd /www/wwwroot/tld.com) at the beginning of crontab when installing new versions.

Steps to solve the problem:
1) Enter the crontab -e command, then press the A button on the keyboard to edit it, then edit the entered command.
Friends, note that this command is entered automatically and you must edit:
* * * * * /www/wwwroot/tld.com && /usr/bin/php xmplus job:run >> /dev/null 2>&1
2) The problem with was not that the word cd is a command at the beginning, if you edit it as follows, the problem is solved:
* * * * * cd /www/wwwroot/tld.com && /usr/bin/php xmplus job:run >> /dev/null 2>&1
3) Then press esc on the keyboard to exit the editing mode and save by writing :q
