### ISSUE TITLE
[Guide] [Safe Update] Update From Lowerversion than v20230625 to v20230709 & v20230710 

### ISSUE THREAD

**Issue by dashti75mo** [xcode75/XManagerPlus#253]
i have updated my XMPlus and i get many Errors Related To database and PHP and Other Components and im here to guide you for safe Update
First If your version is [v20230625] or Lower 
****(here for entering PHPMyAdmin you shoudl enter databse name and password, name  and password are clearly writed in databse section)********
1.go to aapanel database>DatabaseManager[php my admin] > Export>Export Method: Custom-Display all possible options and click go the end of page
*** it will give you an sql backup with size higher than 50 Mib you should zip and high compress it later for Import and restore if needed***
2.go to aapanel database>in front of your databse find backup button>and make backup and download it(not in PHP my Admin)
(this 2 steps just for security of your data(
3.download this [update.sql](https://github.com/xcode75/XManagerPlus/releases/download/v20230625/update.sql) 
uploaded by XMPlus In this [post](https://github.com/xcode75/XManagerPlus/issues/236#issuecomment-1606835551)
4.go to aapanel database>DatabaseManager[php my admin]>Import>import Downloaded File and click go the end of page.
5.open file manager go to  /www/wwwroot/  find your website directory for example /www/wwwroot/tld.com and dont open it simply rightclik on the folder and click compress.
6.when compress done you are ready to update
just follow this [release ](https://github.com/xcode75/XManagerPlus/releases/tag/v20230710) guide to update
7.after updaing users can not login into thier account (open your admin panel>Users>User Group>Add User Group>Name : کاربر & dont click on any permission just save it) Now users can log in.
**my panel default language was persian and i had now problem with Name: کاربر
**if your base language was english and (کاربر) not worked for you then you can try (User) or (user) and test it
**for updating and working without any problem if you using XMPlus Backend for Servers go and update them to latest else servers not responding latest now is 2.1.4
---------------------------
NOW WAYS TO ROLL BACK IF YOU GET ERRORS:
**Errors Related To Mysql Database:**
**Errors Related To Web***
1.aapanel >> Database>> "find your database" in front of its name in backup section restore your backup.
2.aapanel >> Database>> "find your database" in front of its name >> Click on Manager
(here for entering PHPMyAdmin you shoudl enter databse name and password, name  and password are clearly writed in databse section)
3.in PhpMyadmin on left side you have some options: new , information schema, "your database name"
4.click on your "database name"  then on the right side you see some tables: accounts,affilate,cache items,clients and other...
5.first table should be "accounts" watch its front and  search for a button named "Drop" with an icon shaped red and a negative in it. 
6.with pusing drop and accept it, accounts table will removing from database
7.you have localhost.sql backup from step 1 in start of this writing zip it with winrar and select winrar compression method to "Best" becuase your file should be smaller than 52mb
8.now you you should navigate to PHPmyAdmin>Import>Select Zipped File>Navigate down the page and Click on GO.
9.Navigate to File Manager>Right Click on Compressed file with your "domain name" for  Example "tld.com.tar.gz">and Click "Unzip"
10.Done you recovred your XMPlus to what it was before update

----------------------------
this XMPlus Ui is awesome but it can have a better Documention and Plugins, Thanks to Xcode75

**Comment by xcode75** [comment]
only user who did not upfate previous version may have issues. Also if you have updated all versions and still have database issue, check v20230625 and v20230626 updates, update database manually with the update.sql provided using phpmyadmin.
