### ISSUE TITLE
{ "message": "Slim Application Error" }[BUG]

### ISSUE THREAD

**Issue by ArashPersian** [xcode75/XManagerPlus#257]
![image](https://github.com/xcode75/XManagerPlus/assets/119868315/02bf80f5-1a46-4b84-b074-66e24d7fa08e)

![image](https://github.com/xcode75/XManagerPlus/assets/119868315/f1e5b485-55ff-4de5-b18d-d0e41b5611eb)

![image](https://github.com/xcode75/XManagerPlus/assets/119868315/4ac8cf12-81ff-4b4c-b66a-d5a759477dfe)

Hello friends, after the update, I encountered the problem of my site not opening, which was solved by importing the file, but then I encountered the error that I sent you in the first photo.
After seeing article #236, I tried to fix this error, but I ran into new problems. Please explain to me more precisely and simply what I should do to solve my problem, thank you.

**Comment by dashti75mo** [comment]
try this
go to transactions>Currencies
update rates
all rates should be 0.00
and if you use iran rial > IRR value should be 1

**Comment by xcode75** [comment]
> ![image](https://user-images.githubusercontent.com/119868315/253548572-02bf80f5-1a46-4b84-b074-66e24d7fa08e.png)
> 
> ![image](https://user-images.githubusercontent.com/119868315/253549398-f1e5b485-55ff-4de5-b18d-d0e41b5611eb.png)
> 
> ![image](https://user-images.githubusercontent.com/119868315/253551197-4ac8cf12-81ff-4b4c-b66a-d5a759477dfe.png)
> 
> Hello friends, after the update, I encountered the problem of my site not opening, which was solved by importing the file, but then I encountered the error that I sent you in the first photo. After seeing article #236, I tried to fix this error, but I ran into new problems. Please explain to me more precisely and simply what I should do to solve my problem, thank you.

Debug the issue, do not know how manytime i have to say this.

**Comment by ArashPersian** [comment]
> Debug the issue, do not know how manytime i have to say this.
![image](https://github.com/xcode75/XManagerPlus/assets/119868315/c7a16371-04f1-46ee-97bd-a3d9756b70d2)


here you are.
Did I send the information correctly?

**Comment by xcode75** [comment]
> > Debug the issue, do not know how manytime i have to say this.
> > ![image](https://user-images.githubusercontent.com/119868315/253798001-c7a16371-04f1-46ee-97bd-a3d9756b70d2.png)
> 
> here you are. Did I send the information correctly?

you need to update your database with update.sql in v20230625 and v20230625

**Comment by ArashPersian** [comment]
The Tron port had a bug, friends, that's why it was removed, the problem was solved.

Actually, for those friends who haven't updated yet or are having problems, they should import 2 update.sql, i.e. first version v20230625 and then v20230626.

My suggestion is to import and not copy and paste.

Usually, some parts give errors, delete those parts in Notepad and import again.
