### ISSUE TITLE
help for update fronted

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#259]
hello i want to update [v20230521] to [v20230710] but i have eror after update
![sasa](https://github.com/xcode75/XManagerPlus/assets/123809903/6af48ff9-7579-4ca2-8af7-f9daf15d2567)

![ssds](https://github.com/xcode75/XManagerPlus/assets/123809903/e887afe2-cf36-40f1-97f7-1148517a7e9f)

i dont know how to import pls help me

**Comment by ArashPersian** [comment]
سلام عزیز .
این فایل رو دانلود کن .
https://github.com/xcode75/XManagerPlus/releases/download/v20230625/update.sql

بعد با نوت پد بازش کن و محتویاتش رو کپی کنی و داخل اونجا پیست کن و go رو بزن .

**Comment by xcode75** [comment]
update database with  update.sql for v20230625 and v20230626

**Comment by mohammadoaaakd** [comment]
thank you
