### ISSUE TITLE
[BUG] Heavy volume of SQL backup

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#262]
Hi Dear @xcode75 

There is a problem in the "online_ip" and "trafficlog" tables, which causes the backup volume to become too large.
Is it possible to empty these two tables automatically?

![xm](https://github.com/xcode75/XManagerPlus/assets/122527892/70b6d8d2-605a-4510-a799-78531db4b1f9)

**Comment by xcode75** [comment]
noted

**Comment by xcode75** [comment]
> > noted
> 
> Thanks For Update There is one more small problem: All nodes are displayed on the client for admin But we can only connect to the nodes of the same admin group For example, if the admin is in group A, cannot connect to the nodes from group B

just create a group for only admin and add it to all servers, select that group for admin account, done
