### ISSUE TITLE
problem in set telegram bot

### ISSUE THREAD

**Issue by themealad** [xcode75/XManagerPlus#266]
**Environment**

OS:  CENTOS 7
  
Panel Version:     v20230627

after enter telegram bot and telegram HTTP API 
i go to server using ssh and enter  < php xmplus telegram set >
it returns :

**nvalid URL ProvidedYou have new mail in /var/spool/mail/root**

i cant set telegram bot on panel

please help

<a href="https://uplod.ir/zuz1knp6h7tg/telegram.JPG.htm" target=_blank><img src="https://s6.uplod.ir/i/01101/zuz1knp6h7tg_t.jpg" border=0></a>

**Comment by xcode75** [comment]
webhook url is your site address in https://tld.com  in admin setting telegram

**Comment by themealad** [comment]
thanks
this problem solved
now telegram and backup set done
using ( php xmplus backup ) backup will be created and send to telegram bot
but its not creat backup automaticly and send to telegram
what must i do?

**Comment by xcode75** [comment]
check your cron job using ssh command : `contab -e`  ,  see if script path is correct
