### ISSUE TITLE
Compress command error after update

### ISSUE THREAD

**Issue by Technomobile** [xcode75/XManagerPlus#268]
OS:  cent os 7

Panel Version:    20230718

After updating to version 20230718 and entering the compress command, I get an error

Script chmod -R 777 public handling the post-update-cmd event returned with error code 1
![photo_2023-07-22_04-30-59](https://github.com/xcode75/XManagerPlus/assets/53426164/ae0fb1c3-61dd-40a2-ac34-54334c0507ef)

**Comment by letmefind** [comment]
That might be due to an _immutable flag_ that prevents changing file permission even as a root.
try this (_modify the following directory where its "tld.com"_) :
```
sudo chattr +i /www/wwwroot/tld.com/public/.user.ini
```
then repeat :
```
php composer.phar update -n
 ```

**Comment by xcode75** [comment]
> OS: cent os 7
> 
> Panel Version: 20230718
> 
> After updating to version 20230718 and entering the compress command, I get an error
> 
> Script chmod -R 777 public handling the post-update-cmd event returned with error code 1 ![photo_2023-07-22_04-30-59](https://user-images.githubusercontent.com/53426164/255303925-ae0fb1c3-61dd-40a2-ac34-54334c0507ef.jpg)

`sudo chattr -i /www/wwwroot/tld.com/public/.user.ini `  to disable permission bbefore updating composer and enable back when done.  `sudo chattr +i /www/wwwroot/tld.com/public/.user.ini`
