### ISSUE TITLE
How can I set bandwidth to unlimited? 

### ISSUE THREAD

**Issue by SinaPhilip** [xcode75/XManagerPlus#271]
Hi dear @xcode75

I want to know how can I set bandwidth to unlimited in plans section..

**Comment by letmefind** [comment]
Simply, Speedlimit=0 would be meant Unlimited.

**Comment by xcode75** [comment]
> Hi dear @xcode75
> 
> I want to know how can I set bandwidth to unlimited in plans section..

user or server bandwidth?
