### ISSUE TITLE
admin option

### ISSUE THREAD

**Issue by sh-vp** [xcode75/XManagerPlus#273]
hi 

can you add option for send email to expired users on admin panel ?

tnx

**Comment by m0000hamad** [comment]
> hi
> 
> can you add option for send email to expired users on admin panel ?
> 
> tnx

This option has already been considered. You must connect the email to the site according to the tutorial

**Comment by sh-vp** [comment]
> > hi
> > can you add option for send email to expired users on admin panel ?
> > tnx
> 
> This option has already been considered. You must connect the email to the site according to the tutorial

داداشم میخوام به کسایی که اشتراکشون تموم شده ایمیل بدم تخفیف بدم بیان خرید کنن . وصل کردن ایمیل به پنل رو بلدم
