### ISSUE TITLE
lots of server offline notification after update 

### ISSUE THREAD

**Issue by bahramini** [xcode75/XManagerPlus#275]
after update to v20230518 i recieve a lot of server offline & online notifications on tg bot. i have also update backends. seems that new version needs more cpu power.

**Comment by m0000hamad** [comment]
> after update to v20230518 i recieve a lot of server offline & online notifications on tg bot. i have also update backends. seems that new version needs more cpu power.

Update all backends and your problem will be solved

**Comment by bahramini** [comment]
i have already updated, but one of my noeds still has problem in peak times

**Comment by HamrahVIP** [comment]
same problem on some node servers

**Comment by xcode75** [comment]
That is what will happen when using old panel version and latest backend, update frontend till latest version
