### ISSUE TITLE
[BUG] Figures

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#277]
![1](https://github.com/xcode75/XManagerPlus/assets/123809903/5c74b459-c787-4cdc-ba93-979beb35414b)
![2](https://github.com/xcode75/XManagerPlus/assets/123809903/5515285f-d674-4e56-aeb1-2beb7fcfa71f)
![Uploading 3.png…]()

**Comment by mohammadoaaakd** [comment]
![888](https://github.com/xcode75/XManagerPlus/assets/123809903/a64eb7e4-b79f-481f-88a8-76efa2f9d83c)

**Comment by xcode75** [comment]
There is no bug , you have enter wrong exchange rate value causing excess zeros
