### ISSUE TITLE
eror for update  v20230718 tov20230813

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#278]
![54](https://github.com/xcode75/XManagerPlus/assets/123809903/23da2426-9459-435c-80f5-8f4a2d2fd1c1)

**Comment by mohammadoaaakd** [comment]
Script chmod -R 777 public handling the post-update-cmd event returned with error code 1

**Comment by sh-vp** [comment]
remove php.ini from public directory and problem is solved

**Comment by mohammadoaaakd** [comment]
> remove php.ini from public directory and problem is solved

i not found it
