### ISSUE TITLE
[BUG] mail sending not working after latest update

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#282]
**Environment**

OS:  centos 9
  
PHP version: 7.4
   
DB version:  5.7.40
  
Panel Version:    v20230817

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

After updating to the latest XMPlus frontend version (1.0 - v20230817), I noticed the email feature is no longer working properly. Here is my settings:
![image](https://github.com/xcode75/XManagerPlus/assets/35190548/f2f0df86-1f3b-403a-bf8d-7f3a42238039)

When I attempt to send an email to a user through the panel, it shows a message that the email was "successfully sent". However, the intended recipient does not actually receive the email.
![image](https://github.com/xcode75/XManagerPlus/assets/35190548/afa69da9-1748-4d0d-b561-092df2512e76)

I confirmed the email address itself works fine outside of XMPlus by sending and receiving test emails through a regular client. So the address itself does not seem to be the problem.

Additionally, I checked the "queue_messages" table in the database and saw that a record is no longer being created there when I hit send on an email. Previously, all outgoing emails would be logged in this table before sending.

This seems to indicate the issue is occurring somewhere between the frontend "Send" action and the backend email delivery process. Potential areas to troubleshoot further:

Email settings/configuration on the backend
Connectivity between front and backend
Queue worker process that sends emails from the queue
Email logs on the backend for any delivery errors
I wanted to document this in case others are running into similar problems after the latest update. Please let me know if any other details about the email sending failure would be helpful to diagnose the root cause. Hoping we can get the email feature working properly again soon.

**Comment by xcode75** [comment]
Just do not label issue as a bug just cos you have an issue. I have tested with sendgrid and gmail and no issue. That email successfully sent has nothing to do with queue.  Is sent directly to user without queue. Only expired, used or purchase plan are queued, thst depends if user has set to recieve them.

**Comment by amihos** [comment]
@xcode75 When I am facing an issue that starts happening after an update, how could I possibly know if it's a bug? or if it's happening only to me?

What do you suggest to do? 

What I saw was this: since I updated to the latest version my email system stopped working:
I did not receive any more backup emails, also when I am sending messages directly to users, they do not receive anything.

So how do you suggest to troubleshoot this? Will it help to reinstall everything from scratch the frontend?
