### ISSUE TITLE
help for update to v20230817

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#283]
hello guys pls help me to find "settings table" im blind
![11](https://github.com/xcode75/XManagerPlus/assets/123809903/46b8669d-96fb-4135-87e7-db21bfa2fa7f)

**Comment by aliafshany** [comment]
پایین تره

**Comment by mohammadoaaakd** [comment]
![eee](https://github.com/xcode75/XManagerPlus/assets/123809903/c6a32db2-b3b6-4d31-a9c7-e7dfb74ab911)

setteings is here but where is "settings table"

**Comment by aliafshany** [comment]
lets rephraes this way
"Settings" Table

these area tables for say:

fallbacks
giftcards
giftcard_ logs
group
knowledgebase
loginip

**Comment by mohammadoaaakd** [comment]
![1425](https://github.com/xcode75/XManagerPlus/assets/123809903/2f8b1112-7e21-4737-9c13-59afb1f22515)

توی تنظیمات اصلا گزینه ورژن رو پیدا نمیکنم

**Comment by aliafshany** [comment]
سطر های آخر هست
فک کنم ۱۳۰ اینا

باید از بالا بزنی تا row های بیشتری نشون بده

**Comment by mohammadoaaakd** [comment]
![ssdsd](https://github.com/xcode75/XManagerPlus/assets/123809903/26a1438f-bf69-4f9b-8c9f-19d7ddd7b968)

ممنون اوکی شد
