### ISSUE TITLE
[BUG] crisp chat shows previous chat history to new users

### ISSUE THREAD

**Issue by atbax** [xcode75/XManagerPlus#284]
OS:  Linux cenos8
  
PHP version: 7.4
     
Panel Version:  v20230710

when a new user open the login page , the crisp chat page opened automatically and users can see previous chat history.

it's bad experience to all users and also this is a security issue

**Comment by xcode75** [comment]
There is no issue with implementation, your crisp settings is the issue.

**Comment by atbax** [comment]
Dear friend, I bought a license from you twice and I have been using this product for at least 8 months
I report the problems and I shared my and my team's suggestions with you on Telegram
If you really think about the development of this product, then you should not close your eyes to the problems that occur because your product is going to be perfect because there are defects and you must accept the defects.
This is a problem reported by 700 users , so if you know the issue please share root cause for resolve the problem
We can give you access to check it yourself. In addition, in the Crisp settings section, 2 variables are needed, which were copied and pasted from the Crisp site, and we have been communicating with users through chat for 8 months.
