### ISSUE TITLE
Problem with Email/Telegram notifications [BUG]

### ISSUE THREAD

**Issue by atbax** [xcode75/XManagerPlus#285]
OS: Linux cenos8

PHP version: 7.4

Panel Version: v20230710

some transactional notifications has not sent from mail server, seems there is issue with mail and telegram setting Example :

send registration code (email) : work
send forgot password (email) : work
send Transaction arrival for admin in telegram bot : work
send notification for new ticket in TG bot : work
send backup to telegram/Email : does not work
send Transaction arrival for user in TG/Email : does not work
send reminder for subscription : does not work
send global notification in TG : work
send global notification in Email : does not work

i tested with many mail servers such as brevo , sendinblue , amazon SES , google mail and Cpanel mail server which on all of them The result was the same .

**Comment by xcode75** [comment]
There is no bug, i have tested myself, check your cronjob

**Comment by atbax** [comment]
please advise to how to check cronjob
