### ISSUE TITLE
User can't change uuid and sub link. Removed from settings

### ISSUE THREAD

**Issue by SinaPhilip** [xcode75/XManagerPlus#288]
Hi there

Recently I update to 817 and I found out users can't change their uuid or sub link.
I remembered there was such option in settings.

Also in user section, as an admin when I want to switch to other users's page. It returns error "you do not have the permission create or make change"

Regards,

**Comment by SinaPhilip** [comment]
The problem I, s if by mistake, uuid or sub link leaked, users can't change it nor me as admin

**Comment by xcode75** [comment]
Reset sublink and uuid will also reset. Just select all for Administrator under groups settings

**Comment by SinaPhilip** [comment]
It will change sub link not uuid
