### ISSUE TITLE
Starting date with the first user's connection

### ISSUE THREAD

**Issue by iPbaz** [xcode75/XManagerPlus#291]
Only one big thing remained to make this panel seamless. Please add the option in order to calculate the duedate from the first date of user's connection.

It should be something like this: Start after first use (Checkbox) + Expire days text field (e.g. 30 days) (See the attachment)

<img width="438" alt="first use" src="https://github.com/xcode75/XManagerPlus/assets/142832217/2831340a-4b28-401f-9f41-685b5e9ff48d">

**Comment by mimuala** [comment]
please  add this , we need this  Featur
