### ISSUE TITLE
[BUG] registration and invite only section in setting

### ISSUE THREAD

**Issue by SinaPhilip** [xcode75/XManagerPlus#293]
![Screenshot_20230824_151312](https://github.com/xcode75/XManagerPlus/assets/118199289/2521db04-a248-4525-bb89-2d4deb8b8f5f)

I found a bug in setting/registration section. Everything works fine and there is no big deal about this bug.

Registration and invite only section is active when disabled. And it is disabled when you set it to enable. Just change the dictation. 😉

As you see in the picture, the setting show enabled on both. But both are disabled actually. When I set to disable, both options works fine and will be enabled.

**Comment by xcode75** [comment]
There is no bug with that, when disabled user can still register with your invite link, when enable registration is by invite link only.
