### ISSUE TITLE
[BUG] ip limit 1 error eof

### ISSUE THREAD

**Issue by sinaf2000** [xcode75/XManagerPlus#295]
hi panel version1 bug ip limit 1 error eof node server not connected and not switch node server please fixed ip limit error EOF and can switch another node server in client thanks.

**Comment by xcode75** [comment]
There is no bug, you are using cdn for nodes without reverse proxy to get real online ip. Your online ips are cdn ips which are more than 1 when reported from backend to panel, so iplimit 1 will not work.
