### ISSUE TITLE
[BUG] Compose Version Error

### ISSUE THREAD

**Issue by amahdevar** [xcode75/XManagerPlus#297]
**Environment**

OS:  Ubuntu 22.04 LTS (fresh install)
  
PHP version: 8.1
   
DB version:  
  
Panel Version:    v20230822

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

php composer.phar install -n
Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.1.22) does not satisfy that requirement.
  Problem 2
    - irazasyed/telegram-bot-sdk v2.0.0 requires illuminate/support 5.0.*|5.1.*|5.2.* -> found illuminate/support[v5.0.0, ..., 5.2.x-dev] but it conflicts with your root composer.json require (7.30.6).
    - irazasyed/telegram-bot-sdk[v2.1.0, ..., v2.2.0] require illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (7.30.6).
    - irazasyed/telegram-bot-sdk v2.3.0 requires illuminate/support ^5.0 || ^6.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (7.30.6).
    - Root composer.json requires aws/aws-sdk-php 3.202.2 -> satisfiable by aws/aws-sdk-php[3.202.2].
    - Conclusion: don't install guzzlehttp/guzzle 6.3.3 (conflict analysis result)
    - Conclusion: don't install guzzlehttp/guzzle 6.5.2 (conflict analysis result)
    - Conclusion: don't install guzzlehttp/guzzle 6.5.3 (conflict analysis result)
    - Conclusion: don't install guzzlehttp/guzzle 6.5.4 (conflict analysis result)
    - Conclusion: don't install guzzlehttp/guzzle 6.5.7 (conflict analysis result)
    - Conclusion: don't install guzzlehttp/guzzle 6.5.8 (conflict analysis result)
    - Root composer.json requires irazasyed/telegram-bot-sdk ^2.0 -> satisfiable by irazasyed/telegram-bot-sdk[v2.0.0, ..., v2.3.0].
    - Root composer.json requires lokielse/omnipay-alipay v3.1.2 -> satisfiable by lokielse/omnipay-alipay[v3.1.2].
    - Root composer.json requires league/omnipay ^3 -> satisfiable by league/omnipay[v3.0-alpha.1, ..., 3.2.x-dev].
    - irazasyed/telegram-bot-sdk 2.0.x-dev requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev].
    - You can only install one version of a package, so only one of these can be installed: guzzlehttp/guzzle[5.3.3, 5.3.4, 5.3.x-dev, 6.0.0, ..., 6.5.x-dev, 7.0.0-beta.1, ..., 7.8.x-dev].
    - Conclusion: install guzzlehttp/guzzle 7.4.0 (conflict analysis result)
   

*** end of Bug Info ***

Describe the issue you run into.。

Hi, After unzipping XMplus.zip in site root, "php composer.phar install -n" returns above error and ends.

PS: Tried it with 4 different fresh installs of Ubuntu 22.04 LTS.

**Comment by xcode75** [comment]
PHP version 7.4
