### ISSUE TITLE
CPU usage on XMplus.

### ISSUE THREAD

**Issue by bahramini** [xcode75/XManagerPlus#299]
i had problem with high cpu usage on backends. installed XrayR instead of XMplus and as you can see cpu usage dramaticlly decreased.
![sshot-14](https://github.com/xcode75/XManagerPlus/assets/131149927/63f361d7-e7ad-4b3f-b83d-6ffa1c11aa68)

**Comment by xcode75** [comment]
xmplus is using a customized xray-core, possible will have higher cpu.

**Comment by aliafshany** [comment]
> xmplus is using a customized xray-core, possible will have higher cpu.

Is there any important difference between X-rayR and Xmplus One? It would be good if you could tell me the difference.
@xcode75

**Comment by bahramini** [comment]
xmplus is updated to xray-core 1.8.? but XrayR uses v1.7.5. also xmplus is little simpler to config.

**Comment by aliafshany** [comment]
@bahramini 
Thank you for your response
