### ISSUE TITLE
console.php doesn't work

### ISSUE THREAD

**Issue by amahdevar** [xcode75/XManagerPlus#30]
based on installation manual on CentOS 7 & 9:

1. [Frontend Installation - Frontend](https://xcode75.github.io/XMPlusDocs/install/aapanel.html)
2. Create an administrator account: php bin/console.php admin
3. result:

PHP Warning:  main(/www/wwwroot/tld.com/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/tld.com/bin/console.php on line 0

Warning: main(/www/wwwroot/tld.com/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/tld.com/bin/console.php on line 0
PHP Fatal error:  main(): Failed opening required '/www/wwwroot/tld.com/bin/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/tld.com/bin/console.php on line 0

Fatal error: main(): Failed opening required '/www/wwwroot/tld.com/bin/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/tld.com/bin/console.php on line 0

**Comment by Mobinoo1383** [comment]
I have the exact problem

**Comment by xcode75** [comment]
> based on installation manual on CentOS 7 & 9:
> 
> 1. [Frontend Installation - Frontend](https://xcode75.github.io/XMPlusDocs/install/aapanel.html)
> 2. Create an administrator account: php bin/console.php admin
> 3. result:
> 
> PHP Warning: main(/www/wwwroot/tld.com/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/tld.com/bin/console.php on line 0
> 
> Warning: main(/www/wwwroot/tld.com/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/tld.com/bin/console.php on line 0 PHP Fatal error: main(): Failed opening required '/www/wwwroot/tld.com/bin/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/tld.com/bin/console.php on line 0
> 
> Fatal error: main(): Failed opening required '/www/wwwroot/tld.com/bin/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/tld.com/bin/console.php on line 0

check XManager Telegram channel for latest  notices 
https://t.me/XManagerPlus
