### ISSUE TITLE
Gift Cards not usable for expired users

### ISSUE THREAD

**Issue by bahramini** [xcode75/XManagerPlus#300]
in recent update, expired users cannot access to gift card menu. we used gift cards as an option for users to charge their balance and buy subscription.

**Comment by xcode75** [comment]
I have no made any changed to giftcard , check well

**Comment by payeh** [comment]
I have the same problem please check

**Comment by payeh** [comment]
> in recent update, expired users cannot access to gift card menu. we used gift cards as an option for users to charge their balance and buy subscription.

مشکل رو حل نکردین
