### ISSUE TITLE
[BUG] Payments getaway issue 

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#301]
Hi
i get some issue using USDT TRC20 and TRX getaway. please help me to fix this.

![photo_2023-09-13_14-24-45](https://github.com/xcode75/XManagerPlus/assets/57295411/0d3b5c03-e547-49d6-9050-056113caeb9e)

**Comment by xcode75** [comment]
There is nothing wrong, you added token address are in use by other unpaid orders, until order is paid or has expired, address will not be available. There is no TRX payment was removed from i think previous 3 updates.
