### ISSUE TITLE
Updaing from previous versions

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#302]
Hello there. I have a very outdated panel and tried to update it directly to the latest version. However, now I am encountering an error:

`php xmplus update
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sql_tld.currency' doesn't exist in /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php:336
Stack trace:
#0 /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php(336): PDOStatement->execute()
#1 /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php(339): Illuminate\Database\Connection->run()
#4 /www/wwwroot/tld.com/vendor/illuminate/database/Query/Builder.php(2270): Illuminate\Database\Connection->select()
#5 /www/wwwroot/tld.com/vendor/illuminate/database/Query/Builder.php(2258): Illuminate\Database\Query\Builder->runSelect()
#6 /www/wwwroot/tld.com/vendor/illuminate in /www/wwwroot/tld.com/vendor/illuminate/database/Connection.php on line 671`

I have changed the URL and the database name here for privacy.

What should I do now? The site doesn't load at all.

**Comment by xcode75** [comment]
you must manually update database
