### ISSUE TITLE
Role-based Access Issue: User Sees Unauthorized Server Configurations

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#304]
I am using the latest version as of today: XMPlus 1.0 - v20230909.

When I assign a user's role to the customer's service, that user can see all the servers when they update the subscription link, even though their plan group has not changed.

For example, User1 has group A. When I add the customer's service role, User1 updates the link and can then see group A, B, and C configurations. However, User1 cannot connect to them, fortunately.

Is this a bug?

**Comment by stuxnxt** [comment]
Same problem. Even though users are not able to connect to the unauthorized servers in which users are not assigned to the related server group, Servers are still showing up in the client app

**Comment by xcode75** [comment]
noted
