### ISSUE TITLE
not show number of online users in frontend

### ISSUE THREAD

**Issue by bahramini** [xcode75/XManagerPlus#307]
one of my nodes doesnt show number of online users in frontend. backend counts number of online users correctly. even seems that it calculates traffic correctly. i have this issue with both xrayr and xmplus. and all are updated to latest version.
![sshot-4](https://github.com/xcode75/XManagerPlus/assets/131149927/a71312f7-972e-4330-b2e2-82f2bb4b61af)
![sshot-5](https://github.com/xcode75/XManagerPlus/assets/131149927/dd9b0724-9a4f-47cd-a71f-ad05287007f4)

**Comment by ali-frm** [comment]
same problem

**Comment by xcode75** [comment]
provide full backend config, i cannot know your issue from this scrrenshot.
