### ISSUE TITLE
i cant use wget code in my server 

### ISSUE THREAD

**Issue by arashAGH** [xcode75/XManagerPlus#31]
pls help!
 wget https://github.com/xcode75/XManagerPlus/releases/download/v2023020901/XMPlus.zip
--2023-02-10 20:15:57--  https://github.com/xcode75/XManagerPlus/releases/download/v2023020901/XMPlus.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-10 20:15:57 ERROR 404: Not Found.

**Comment by xcode75** [comment]
tag has been updated

**Comment by arashAGH** [comment]
tnx
