### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kanganpishgaman** [xcode75/XManagerPlus#310]
**Environment**

OS:  centos7
  
PHP version: 7.4
   
DB version:  
  
Panel Version:   v20231107 

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Trying to get property 'packageid' of non-object","code":8,"file":"\/www\/wwwroot\/bavinsoft.click\/storage\/smarty\/compile\/a875ee52e91031652d749c7f5088b7a49eb8d634_0.file.dashboard.tpl.php","line":303,"trace":[{"file":"\/www\/wwwroot\/bavinsoft.click\/storage\/smarty\/compile\/a875ee52e91031652d749c7f5088b7a49eb8d634_0.file.dashboard.tpl.php","line":303,"function":null,"class":"Whoops\\Exception\\ErrorException","args":["Trying to get property 'packageid' of non-object"]},{"file":"\/www\/wwwroot\/bavinsoft.click\/storage\/smarty\/compile\/a875ee52e91031652d749c7f5088b7a49eb8d634_0.file.dashboard.tpl.php","line":303,"function":"handleError","class":"Whoops\\Run","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/smarty\/smarty\/libs\/sysplugins\/smarty_template_resource_base.php","line":123,"function":"content_654e4bb8c7aa51_29444723","class":null,"args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/smarty\/smarty\/libs\/sysplugins\/smarty_template_compiled.php","line":114,"function":"getRenderedTemplateCode","class":"Smarty_Template_Resource_Base","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/smarty\/smarty\/libs\/sysplugins\/smarty_internal_template.php","line":217,"function":"render","class":"Smarty_Template_Compiled","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/smarty\/smarty\/libs\/sysplugins\/smarty_internal_templatebase.php","line":238,"function":"render","class":"Smarty_Internal_Template","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/smarty\/smarty\/libs\/sysplugins\/smarty_internal_templatebase.php","line":116,"function":"_execute","class":"Smarty_Internal_TemplateBase","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/app\/Http\/Controllers\/User\/IndexController.php","line":48,"function":"fetch","class":"Smarty_Internal_TemplateBase","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php","line":38,"function":"index","class":"App\\Http\\Controllers\\User\\IndexController","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":358,"function":"__invoke","class":"Slim\\Handlers\\Strategies\\RequestResponse","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/app\/Http\/Middleware\/UserAuth.php","line":48,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":269,"function":"__invoke","class":"App\\Http\\Middleware\\UserAuth","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:250$2355196","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Routing\/Route.php","line":315,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php","line":68,"function":"run","class":"Slim\\Routing\\Route","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/bryanjhv\/slim-session\/src\/Slim\/Middleware\/Session.php","line":82,"function":"handle","class":"Slim\\Routing\\RouteRunner","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":269,"function":"__invoke","class":"Slim\\Middleware\\Session","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php","line":64,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:250$2355196","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\BodyParsingMiddleware","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php","line":45,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$2355194","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\RoutingMiddleware","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/selective\/basepath\/src\/BasePathMiddleware.php","line":52,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$2355194","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":168,"function":"process","class":"Selective\\BasePath\\BasePathMiddleware","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/middlewares\/whoops\/src\/Whoops.php","line":104,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:138$2355195","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Middlewares\\Whoops","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php","line":76,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$2355194","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":121,"function":"process","class":"Slim\\Middleware\\ErrorMiddleware","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php","line":65,"function":"handle","class":"class@anonymous\u0000\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php:108$2355194","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/App.php","line":199,"function":"handle","class":"Slim\\MiddlewareDispatcher","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/vendor\/slim\/slim\/Slim\/App.php","line":183,"function":"handle","class":"Slim\\App","args":[]},{"file":"\/www\/wwwroot\/bavinsoft.click\/public\/index.php","line":31,"function":"run","class":"Slim\\App","args":[]}]}}
Describe the issue you run into.。
Hello
In the user section, the switch user option that I click displays this warning
![problem](https://github.com/xcode75/XManagerPlus/assets/126580383/b9480b1c-cc4a-4cb2-8d98-ac1f9474fd14)

**Comment by xcode75** [comment]
okay, but disable debug and switch again and see
