### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sohrabp72** [xcode75/XManagerPlus#311]
**Environment**

OS:  
  Ubuntu 22.04LTS
PHP version: 
   
DB version:  
  
Panel Version:    
XMPlus 1.0 - v20231107
Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

Describe the issue you run into.。

warp in installed and licensed and listening on port 40000 and works fine, in the route file I added 
` {
      "type": "field",
      "outboundTag": "socks5-warp",
      "domain": [
         "geosite:google"
      ]
    }`
and in outbound.json file:
`{
    "tag": "socks5-warp",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 40000
        }
      ]
    }
  }`
still google ain't route through warp.

**Comment by aliafshany** [comment]
@sohrabp72 
مشکل چی بود؟ چطوری حل کردیش؟

**Comment by sohrabp72** [comment]
باید تو فایل config.yaml هشتگ # جلوی outbound و route رو ور میداشتم.
