### ISSUE TITLE
DataTables warning: table id=datatable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### ISSUE THREAD

**Issue by ArashPersian** [xcode75/XManagerPlus#314]
hello guys i have xmplus v2 after update i have this proble 

![image](https://github.com/xcode75/XManagerPlus/assets/119868315/c6f23332-885b-4adc-a783-bfcab873229d)
when true debug

Unfortunately, I cannot change any of the settings and none of the settings can be saved

And user can,t reset password

**Comment by xcode75** [comment]
You did not update database in v20231227 or you skipped That update all together. Not v20231227_2
