### ISSUE TITLE
[LOGIN  BUG]

### ISSUE THREAD

**Issue by panthex-ray** [xcode75/XManagerPlus#315]
OS:  centos 7
  
PHP version: 7-4
    
Panel Version:    the newest V (2023-7-... iguess)

Modifying the config.php file for debugging purposes has not made any difference.

Hi, I'm encountering a significant issue with the XMPLUS panel. After completing the installation, I'm able to log in successfully, but the panel immediately logs me out of the user/admin menu.

I believe the issue stems from the page refreshing instead of maintaining my logged-in state. A similar behavior occurs when I attempt to change the language—the page simply refreshes, or at least that's my current guessing.

**Comment by xcode75** [comment]
Is not a bug,if you bought panel from me open a ticket on the site you paid on. I will reply you there.

**Comment by panthex-ray** [comment]
I'm using the free version for the test and will buy it later on when I'm sure the panel is working properly.

**Comment by panthex-ray** [comment]
> Is not a bug,if you bought panel from me open a ticket on the site you paid on. I will reply you there.

I'm using the free version for the test and will buy it later on when I'm sure the panel is working properly.

**Comment by xcode75** [comment]
use tls or disable sessions in config.php
