### ISSUE TITLE
aapanel restart issue

### ISSUE THREAD

**Issue by Artitrader** [xcode75/XManagerPlus#32]
hello sorry to take your time.

explantion: it seems whenever i reboot the server the aapanel disappears and i can't access it anymore i have tried with many servers and multiple IPs but still the problem remains idk if this is a small issue or not.
question:is there a fix to this problem?

**Comment by Artitrader** [comment]
it happens in centos stream 9 (in 7 & 8 it is ok)

**Comment by xcode75** [comment]
> it happens in centos stream 9 (in 7 & 8 it is ok)

as was stated in the installation doc, said use centos 7+ not centos 8 or 9
