### ISSUE TITLE
Fragment Feature

### ISSUE THREAD

**Issue by sinaf2000** [xcode75/XManagerPlus#320]
Hello, please add the fragment feature in the subscription without the need for the fragment tool, thank you

**Comment by zigan23** [comment]
The programs v2rayng themselves added this feature to the program

**Comment by sinaf2000** [comment]
> The programs v2rayng themselves added this feature to the program

Dear, I meant to add this feature in xmplus v1 panel

**Comment by aliafshany** [comment]
We need the fragment to be set up by the server side, not the client side.

**Comment by sinaf2000** [comment]
> We need the fragment to be set up by the server side, not the client side.

Yes , i mean and all automatic easy setup

**Comment by xcode75** [comment]
> We need the fragment to be set up by the server side, not the client side.

only required on client not server

**Comment by xcode75** [comment]
> Hello, please add the fragment feature in the subscription without the need for the fragment tool, thank you

until there are app that support it in subscription, will not be added yet
