### ISSUE TITLE
Custom Configs in Subscription links

### ISSUE THREAD

**Issue by Dev-l0p** [xcode75/XManagerPlus#321]
Hello Sir,
Please enable the ability to add custom config links in subscription. It is very useful and necessary.
Thanks

**Comment by Pouryjoon** [comment]
he means: as v2rayng and some other clients supports json custom config and custom config subscription link ,for now its the best way to integerate fragment in client remotly also editing allow insecure , mux , ..... .
more info : [https://github.com/2dust/v2rayNG/pull/2827](https://github.com/2dust/v2rayNG/pull/2827)
