### ISSUE TITLE
[BUG] You do not have the permission create or make changes.

### ISSUE THREAD

**Issue by Zo0oX** [xcode75/XManagerPlus#322]
**Environment**

OS:  centoes
  
PHP version: php 7.4
   
DB version:  
  
Panel Version:    v20231107

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

Describe the issue you run into.。

hello

after i click on swich for open users pannel i see this error

`You do not have the permission create or make changes.`

**Comment by EmadHeravi** [comment]
Facing same issue.

**Comment by EmadHeravi** [comment]
Ok in my case its not a bug, User group is missing the permission. you just need to allow permission for that user group to switch to user account.
