### ISSUE TITLE
[BUG] Total used traffic and expire date

### ISSUE THREAD

**Issue by ashyrz-pro** [xcode75/XManagerPlus#326]
Total used traffic and expire date disappeared from subscriptions after the update
**Environment**

OS:  
  
PHP version: 
   
DB version:  
  
Panel Version:    

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

Describe the issue you run into.。

**Comment by aliafshany** [comment]
Mine is fine
check the settings then

**Comment by ashyrz-pro** [comment]
Where in settings do you enable that for each users to see their total and date in their servers list?

**Comment by ashyrz-pro** [comment]
Oh I get it. On v2box it shows total and expire. But on streisand it doesn't. Earlier versions of xmplus showed. Could you check?

**Comment by HamrahVIP** [comment]
Same problem with Streisand After update to v20240713
