### ISSUE TITLE
Shadowsocks settings

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#329]
**Environment**

OS:  CENTos 9
  
PHP version: 7.4.33
   
DB version:  MySQL 5.7.43
  
Panel Version:    XMPlus 1.0 - v20240718

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

Describe the issue you run into.。after installing to the newest version of frontend and the backend to  v2.1.8 - XMPlus v1
my shadowsocks connections stopped working
here is my current setup that used to work:
Network Settings:
{
  "transport": "tcp",
  "acceptProxyProtocol": false,
  "header": {
    "type": "none"
  }
}

security settings
{
  "serverName": "mydomain.com",
  "rejectUnknownSni": true,
  "allowInsecure": false,
  "fingerprint": "chrome"
}

Encryption: chacha20-ietf-poly1305
security: None

has things changed in the new backend? if yes what is the new working setup?

here is the log of the backend

[Info] [4054903368] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: xx.xx.xx.xx:45094 > common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to read 50 bytes > EOF
Jul 21 19:00:35 xm-nl XMPlus[12888]: 2024/07/21 19:00:35 xx.xx.xx.xx:45094 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to read 50 bytes > EOF
Jul 21 19:00:35 xm-nl XMPlus[12888]: 2024/07/21 19:00:35 [Info] [7800996] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: xx.xx.xx.xx:45102 > common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to read 50 bytes > EOF
Jul 21 19:00:35 xm-nl XMPlus[12888]: 2024/07/21 19:00:35 xx.xx.xx.xx:45102 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to read 50 bytes > EOF

**Comment by amihos** [comment]
What does it mean when you close the issue without saying anything?

**Comment by aliafshany** [comment]
> What does it mean when you close the issue without saying anything?

There was a new update, in which the notes point out this fix.

**Comment by amihos** [comment]
I am having the issue with the latest update

**Comment by amihos** [comment]
Thank you. Just saw it, and it fixed the issue thank you @xcode75
