### ISSUE TITLE
problem in create admin account run command: php bin/console.php admin

### ISSUE THREAD

**Issue by arashAGH** [xcode75/XManagerPlus#33]
when i write this command after do evry thing in your guide sheet,
I get this errors :
plz guide me for solve this
tnx:

[root@76121 raaaanaa.xyz]#  php bin/console.php admin
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Style\SymfonyStyle::ask() must be of the type string or null, int given, called in /www/wwwroot/raaaanaa.xyz/app/Commands/AdminCommand.php on line 42 and defined in /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Style/SymfonyStyle.php:253
Stack trace:
#0 /www/wwwroot/raaaanaa.xyz/app/Commands/AdminCommand.php(42): Symfony\Component\Console\Style\SymfonyStyle->ask()
#1 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Command/Command.php(298): App\Commands\AdminCommand->execute()
#2 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /www/wwwroot/raaaanaa.xyz/bin/console.php(0): Symfony\Co in /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Style/SymfonyStyle.php on line 253

Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Style\SymfonyStyle::ask() must be of the type string or null, int given, called in /www/wwwroot/raaaanaa.xyz/app/Commands/AdminCommand.php on line 42 and defined in /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Style/SymfonyStyle.php:253
Stack trace:
#0 /www/wwwroot/raaaanaa.xyz/app/Commands/AdminCommand.php(42): Symfony\Component\Console\Style\SymfonyStyle->ask()
#1 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Command/Command.php(298): App\Commands\AdminCommand->execute()
#2 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /www/wwwroot/raaaanaa.xyz/bin/console.php(0): Symfony\Co in /www/wwwroot/raaaanaa.xyz/vendor/symfony/console/Style/SymfonyStyle.php on line 253
[root@76121 raaaanaa.xyz]#

**Comment by xcode75** [comment]
Issues fixed in latest update

https://github.com/xcode75/XManagerPlus/releases/tag/v20230211
