### ISSUE TITLE
what is inboundTag?

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#334]
Hello there, I would like to know how I can find the inbound tag for my node IDs.

I want to edit the outbound, but I can't find any inbound tag for it.

**Comment by aliafshany** [comment]
I would like to have a SOCKS5 and route everything through this SOCKS.

I already know how to write an outbound SOCKS5 bot, but how can I route everything through this?
@xcode75

**Comment by xcode75** [comment]
![Screenshot_20240807-124133_Chrome](https://github.com/user-attachments/assets/132c5f2c-ad89-47ab-a033-bfee77cf90f5)

**Comment by xcode75** [comment]
nodetype_nodeport_nodeid
