### ISSUE TITLE
[BUG]vless protocol

### ISSUE THREAD

**Issue by peter2186668355** [xcode75/XManagerPlus#338]
The vless protocol cannot use in meta client, but shadowrocket can connect.

**Comment by xcode75** [comment]
> The vless protocol cannot use in meta client, but shadowrocket can connect.

tested and have no issue

**Comment by peter2186668355** [comment]
please use this verge app
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.5
