### ISSUE TITLE
[BUG] Config Failure for Proxied Protocols (vless/trojan websocket) After Upgrade to v20240813

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#340]
Environment

OS: Centos 9
PHP version: 7.4.33
DB version: 5.7.43
Panel Version: v20240813
Debug Info: [Please enable debug in config.php and upload screenshot]

Bug Info
After upgrading to the new version (v20240813), some configurations have stopped working. Specifically, protocols that use domains behind Cloudflare and are proxied via CDN, such as vless websocket and trojan websocket, are affected. Other nodes that connect directly to the backend (e.g., shadowsocks, QUIC, or KCP) continue to function normally.
Additional Information

A separate panel running an older version (v20240722) connects to the same backend and servers with all configs working correctly.
The backend has been updated to the latest version (v2.2.0) with no effect on the issue.

Steps to Reproduce

Upgrade panel to version v20240813
Attempt to connect using vless websocket or trojan websocket protocols
Observe connection failure for these proxied protocols

Expected Behavior
All protocols, including those proxied via CDN (vless websocket, trojan websocket), should connect and function correctly after the upgrade.
Actual Behavior
Proxied protocols (vless websocket, trojan websocket) fail to connect, while direct connection protocols (shadowsocks, QUIC, KCP) work as expected.
Additional Notes
The issue appears to be specific to the new panel version, as the older version (v20240722) works correctly with the same backend and configurations.

**Comment by xcode75** [comment]
https://github.com/XMPlusDev/XMPlusv1/blob/main/README.md
