### ISSUE TITLE
[BUG]little bugs

### ISSUE THREAD

**Issue by peter2186668355** [xcode75/XManagerPlus#341]
**There are the following bugs**

①In the verge software, the Taiwan node does not display the country logo.
②In the traffic reset email, the official website name is incorrectly displayed as %appName%.
③When the official website name is in Chinese, the subscription name exported by meta is garbled.

**Comment by xcode75** [comment]
1. has nothing to do with panel. App developer may have removed Taiwan's flag on purpose.
2 and 3 will be checked.
