### ISSUE TITLE
[BUG] Websocket problem on latest version

### ISSUE THREAD

**Issue by ashyrz-pro** [xcode75/XManagerPlus#342]
**Environment**

OS:  Ubuntu
  
PHP version: 
   
DB version:  
  
Panel Version:    Latest

Debug Info: enable debug in config.php and upload screenshot.

**Bug Info**

Describe the issue you run into.。

The network settings on the panel has changed 

{
  "transport": "ws",
  "acceptProxyProtocol": false,
  "path": "/xmplus?ed=2560",
  **"host": "hk1.xyz.com"
}

this is the new settings, if host is behind a cdn(in my case google middleware ws proxy) it doesnt allow traffic and nothing reaches the server.

but if I use the older network settings like this

{
  "transport": "ws",
  "acceptProxyProtocol": false,
  "path": "/xmplus?ed=2560",
  "headers": {
    "Host": "hk1.xyz.com"
  }
}

Traffic arrives the server and everything works fine but if client updates the subscription the host is empty. I updated both admin panels and nodes rebooted them and everything. Please check.

**Comment by ashyrz-pro** [comment]
GRPC and other protocols are working fine the problem only seems to occur with websocket

**Comment by ashyrz-pro** [comment]
if I can assist with any more info about the issue feel free to contact @yedyans telegram

**Comment by xcode75** [comment]
https://github.com/XTLS/Xray-core/issues/3222

just leave host empty

**Comment by ashyrz-pro** [comment]
If I leave host empty after updating subscription websocket host disappears

**Comment by ashyrz-pro** [comment]
If I keep like this there is no traffic <img width="1226" alt="image" src="https://github.com/user-attachments/assets/8fc15012-544f-4d1e-9efc-4e7aff32cf97">

**Comment by ashyrz-pro** [comment]
If I do like this traffic reaches the server but upon updating subsciption the ws host is empty
<img width="1373" alt="Screenshot 2024-08-16 at 04 32 18" src="https://github.com/user-attachments/assets/d06c6026-9785-435a-af16-1f2cc1e897f3">
