### ISSUE TITLE
If I keep like this there is no traffic <img width="1226" alt="image" src="https://github.com/user-attachments/assets/8fc15012-544f-4d1e-9efc-4e7aff32cf97">

### ISSUE THREAD

**Issue by ashyrz-pro** [xcode75/XManagerPlus#343]
If I keep like this there is no traffic <img width="1226" alt="image" src="https://github.com/user-attachments/assets/8fc15012-544f-4d1e-9efc-4e7aff32cf97">

_Originally posted by @ashyrz-pro in https://github.com/xcode75/XManagerPlus/issues/342#issuecomment-2293076246_

**Comment by xcode75** [comment]
host is the cdn host which point to the server the backend is installed on, not some random cdn host else leave host empty

**Comment by xcode75** [comment]
you cannot use a cdn host for host in panel host. Only server address can use a cdn host.
