### ISSUE TITLE
v20240817

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#344]
Hello there, can we use the previous network and security settings after updating to this version? I have v20240816, and everything is working fine right now.

i mean we still use this configuration:

{
	"transport" : "ws",
	"acceptProxyProtocol": false,
	"host": "x.tld.com",
	"path": "/xmplus?ed=2560"
}

{
	"serverName": "x.tld.com",
	"rejectUnknownSni": false,
	"allowInsecure": true,
	"fingerprint": "chrome",
	"sni" : "google.com"
}

**Comment by xcode75** [comment]
yes
