### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#345]
![سقثفثقفثف](https://github.com/user-attachments/assets/6128928f-a594-4082-8c43-b1eb9517a322)
![بیلبیلبل](https://github.com/user-attachments/assets/d1f931b8-0059-44c4-a537-e9bcdcdfd7ac)
Hi, please add the possibility that we can customize the attachment pages as html code

thanks

**Comment by xcode75** [comment]
that is not an attachment. is pure html code. you can edit by yourself.
