### ISSUE TITLE
XMPlus backend 2.2.1 bug

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#346]
Hello, I updated the panel to the latest version v20240820. Everything was working fine until I updated the backend to 2.2.1 as well.

I constantly get this error:

![CleanShot 2024-08-20 at 14 06 29](https://github.com/user-attachments/assets/5c3c81a5-81ad-4b84-81f3-4f29d45326fe)

I tried uninstalling and installing again, but still the same results.

**Comment by aliafshany** [comment]
I came back to v2.2.0, and it works fine again.

**Comment by xcode75** [comment]
> I came back to v2.2.0, and it works fine again.

/etc/systemd/system/XMPlus.service  

   `--config`

```
ExecStart=/usr/local/XMPlus/XMPlus -config /etc/XMPlus/config.yml

```

**Comment by aliafshany** [comment]
@xcode75 
it worked
is it gonna be fixed in the next version or i have to manually edit it with every update?

**Comment by aliafshany** [comment]
and also this command does not work
`xmplus warp`
![image](https://github.com/user-attachments/assets/96115b21-0972-48d1-b5e3-a54a25e88b2d)
