### ISSUE TITLE
xmplus warp and  x25519 does not work

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#347]
and also this command does not work
`xmplus warp`
`xmplus x25519`
![CleanShot 2024-08-20 at 14 32 53](https://github.com/user-attachments/assets/e2ec9e7c-1d0e-446d-aff6-9a613cbe4b5c)

![image](https://github.com/user-attachments/assets/96115b21-0972-48d1-b5e3-a54a25e88b2d)

_Originally posted by @aliafshany in https://github.com/xcode75/XManagerPlus/issues/346#issuecomment-2298629752_

**Comment by aliafshany** [comment]
xmplus version error

![CleanShot 2024-08-20 at 14 36 03](https://github.com/user-attachments/assets/c3644823-e9e6-480b-b25c-8aeaa2e54097)

**Comment by xcode75** [comment]
you better uninstall and reinstall backend

**Comment by xcode75** [comment]
wait a moment, i did not update the script

**Comment by xcode75** [comment]
> @xcode75 please fix -config issue too

you can update now

`xmplus update v2.2.1`

**Comment by aliafshany** [comment]
@xcode75 it works
thanks
