### ISSUE TITLE
[BUG] ip limit 

### ISSUE THREAD

**Issue by abolfazlhasanzadeh** [xcode75/XManagerPlus#348]
Hi
I have an issue with IP limit. 
When I set it in the panel, if the service is for a single user and the user pings all nodes in the client, the nodes get disconnected, and I have to change the subscription link.
There are 7 nodes, and even though I increased the IP limit in the panel by one and set it for two users, when the first user pings all nodes or switches between nodes quickly, the node disconnects.
Please tell me how to solve this issue. I would appreciate your help.

**Comment by sinaf2000** [comment]
I have the same problem, please reply if anyone knows the solution

**Comment by xcode75** [comment]
Such issue was resolved in [v20240818](https://github.com/xcode75/XManagerPlus/releases/tag/v20240818) . if you still have issue manually login to your database using phpmyadmin and empty onlineips table.
Done.

**Comment by sinaf2000** [comment]
The problem was solved by emptying the onlineips table, can this happen again? If it happens again, how can I prevent it from happening again?
