### ISSUE TITLE
Slim Application Error After Update v20240902

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#349]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Slim Application Error After Update v20240902

### Reproduction Method

![Screenshot 2024-09-04 at 14-19-03 Whoops! There was an error](https://github.com/user-attachments/assets/78aab169-e456-428c-9f89-40da36b05b52)

### Panel Version

<details><pre><code>

</code></pre></details>

### PHP version

<details><pre><code>

</code></pre></details>

### Panel config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Panel Error log

<details><pre><code>

</code></pre></details>

### Server Error log

<details><pre><code>

</code></pre></details>

### App or Client type(version)

<details><pre><code>

</code></pre></details>

**Comment by HamrahVIP** [comment]
solved by replace locationservice and iplimit php files

**Comment by aliafshany** [comment]
> solved by replace locationservice and iplimit php files

could you please tell me how exactly you solved this?
@HamrahVIP

**Comment by HamrahVIP** [comment]
[IPRange.zip](https://github.com/user-attachments/files/16917290/IPRange.zip)
[LocationService.zip](https://github.com/user-attachments/files/16917293/LocationService.zip)

Download And Extract iprang and location servcie files, replace them
iprange location is: /www/wwwroot/tld.com/app/Helpers/
locationservice location is : /www/wwwroot/tld.com/app/Services/

**Comment by aliafshany** [comment]
@HamrahVIP thank you
