### ISSUE TITLE
allowInsecure Does not work

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#351]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

In the latest version, which is v20240906, when you set allowInsecure to true, it doesn't take any effect on the client's app. I checked it on V2rayng and Streisand; unfortunately, the client should enable it by himself. 

Would you mind investigating this?

### Reproduction Method

set allowinsecure to true

### Panel Version

<details><pre><code>

</code></pre></details>

### PHP version

<details><pre><code>

</code></pre></details>

### Panel config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Panel Error log

<details><pre><code>

</code></pre></details>

### Server Error log

<details><pre><code>

</code></pre></details>

### App or Client type(version)

<details><pre><code>

</code></pre></details>

**Comment by xcode75** [comment]
It has nothing to do with the panel. The client does not accept allowinsecure from sublinks. Can only be enabled manually.
