### ISSUE TITLE
custom warp license adding

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#353]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

_Hello there,  
Is it possible to add a feature that allows changing the license to something else?  
I don't want to generate a new license; I would like to add my own license.  

Soon, the free warp is going to end, and you have to add your paid ones._

### Reproduction Method

None

### Panel Version

<details><pre><code>

</code></pre></details>

### PHP version

<details><pre><code>

</code></pre></details>

### Panel config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Panel Error log

<details><pre><code>

</code></pre></details>

### Server Error log

<details><pre><code>

</code></pre></details>

### App or Client type(version)

<details><pre><code>

</code></pre></details>

**Comment by xcode75** [comment]
There is no feature aaded for warp.  Warp uses wireguard as a client. Nothing special. You can use any warp license key You want. If it works fine. If it does not is, it has nothing to do with backend.
