### ISSUE TITLE
XMPlus may fail to start, please use XMPlus log to check the log information later

### ISSUE THREAD

**Issue by arashAGH** [xcode75/XManagerPlus#39]
i got this erors in XMPlus log after doeing any thing for confiq XMPlus 
and when i write Restart XMPlus:
XMPlus may fail to start, please use XMPlus log to check the log information later
plz help me again 
tank you
XMPlus log:
-- Logs begin at Sun 2023-02-12 00:18:35 IST. --
Feb 12 06:02:17 76121.AZARONLINE.COM systemd[1]: Stopped XMPlus Service.
Feb 12 06:02:17 76121.AZARONLINE.COM systemd[1]: Started XMPlus Service.
Feb 12 06:02:17 76121.AZARONLINE.COM XMPlus[9528]: XMPlus v2.1.0 (A custom version of XrayR)
Feb 12 06:02:17 76121.AZARONLINE.COM XMPlus[9528]: 2023/02/12 06:02:17 Starting XMPlus
Feb 12 06:02:17 76121.AZARONLINE.COM XMPlus[9528]: 2023/02/12 06:02:17 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
Feb 12 06:02:17 76121.AZARONLINE.COM XMPlus[9528]: 2023/02/12 06:02:17 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
Feb 12 06:02:17 76121.AZARONLINE.COM XMPlus[9528]: 2023/02/12 06:02:17 [Warning] core: Xray 1.7.3 started
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: 2023/02/12 06:02:18 Unsupported Node Type:
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: panic: Unsupported Node Type:
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: goroutine 1 [running]:
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: log.Panic({0xc0004e1ce8?, 0xc0002c6e00?, 0xc0004e1d40?})
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]:         log/log.go:384 +0x65
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc0002ce900)
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]:         github.com/xcode75/XMPlus/service/controller/controller.go:112 +0x658
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc000460fc0)
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]:         github.com/xcode75/XMPlus/panel/panel.go:184 +0x37d
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]: main.main()
Feb 12 06:02:18 76121.AZARONLINE.COM XMPlus[9528]:         github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 12 06:02:18 76121.AZARONLINE.COM systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 12 06:02:18 76121.AZARONLINE.COM systemd[1]: XMPlus.service: Failed with result 'exit-code'.
Feb 12 06:02:28 76121.AZARONLINE.COM systemd[1]: XMPlus.service: Service RestartSec=10s expired, scheduling restart.
Feb 12 06:02:28 76121.AZARONLINE.COM systemd[1]: XMPlus.service: Scheduled restart job, restart counter is at 29.
Feb 12 06:02:28 76121.AZARONLINE.COM systemd[1]: Stopped XMPlus Service.
Feb 12 06:02:28 76121.AZARONLINE.COM systemd[1]: Started XMPlus Service.
Feb 12 06:02:28 76121.AZARONLINE.COM XMPlus[9535]: XMPlus v2.1.0 (A custom version of XrayR)
Feb 12 06:02:28 76121.AZARONLINE.COM XMPlus[9535]: 2023/02/12 06:02:28 Starting XMPlus
Feb 12 06:02:28 76121.AZARONLINE.COM XMPlus[9535]: 2023/02/12 06:02:28 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
Feb 12 06:02:28 76121.AZARONLINE.COM XMPlus[9535]: 2023/02/12 06:02:28 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
Feb 12 06:02:28 76121.AZARONLINE.COM XMPlus[9535]: 2023/02/12 06:02:28 [Warning] core: Xray 1.7.3 started
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: 2023/02/12 06:02:29 Unsupported Node Type:
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: panic: Unsupported Node Type:
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: goroutine 1 [running]:
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: log.Panic({0xc000a3dce8?, 0xc000392000?, 0xc000a3dd40?})
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]:         log/log.go:384 +0x65
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc000406900)
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]:         github.com/xcode75/XMPlus/service/controller/controller.go:112 +0x658
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0007e6cc0)
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]:         github.com/xcode75/XMPlus/panel/panel.go:184 +0x37d
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]: main.main()
Feb 12 06:02:29 76121.AZARONLINE.COM XMPlus[9535]:         github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 12 06:02:29 76121.AZARONLINE.COM systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by matador7495** [comment]
Add a # to DnsConfigPath: /etc/XMPlus/dns.json in the config.json file, the problem may be solved.
