### ISSUE TITLE
How to enable Alpn 

### ISSUE THREAD

**Issue by omiderfanmanesh** [xcode75/XManagerPlus#41]
according to [tlsobject](https://xtls.github.io/Xray-docs-next/config/transport.html#tlsobject), is it the right way to enable the alpn?
when I open V2rayNG, the alpn, and fingerprint (uTLS) are disabled. does Clash handle then automatically?

```
{
  "serverName": "mydomain.com",
  "rejectUnknownSni": true,
  "allowInsecure": false,
  "fingerprint": "chrome",
  "alpn": [
    "h2",
    "http/1.1"
  ]
}
```

**Comment by xcode75** [comment]
Only option stated in docs are valid, does not support subsctiption alpn
