### ISSUE TITLE
backend server : Problem on cdn.conf error nginx 

### ISSUE THREAD

**Issue by seniormmd1** [xcode75/XManagerPlus#44]
hi guys what's this error when start nginx command 

-- Unit nginx.service has begun starting up.
Feb 13 14:50:10  nginx[10341]: nginx: [emerg] invalid number of arguments in "grpc_pass" directive in /etc/nginx/conf.d/cdn.conf:54
Feb 13 14:50:10  nginx[10341]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 13 14:50:10  systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 13 14:50:10  systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by xcode75** [comment]
> 

grpc_pass" directive in /etc/nginx/conf.d/cdn.conf:54
This is nginx isuse, you can google how to fix that
