### ISSUE TITLE
add server error

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#45]
Version of XMPlus frontend
v20230211

Version of XMPlus/XrayR backend
v2.1.0

Describtion : 
I can no longer add new servers after recent updates
![Screenshot (46)](https://user-images.githubusercontent.com/124066783/218565496-a8a0d112-de22-4602-aa75-6200c2d6a231.png)
![Screenshot (47)](https://user-images.githubusercontent.com/124066783/218565502-c14c9a68-7351-4e38-b36d-28e9457b2df1.png)

**Comment by xcode75** [comment]
You missed some old updates, you have to manually change network structure to type to text and default null in database for server table

**Comment by shadow-vpn** [comment]
How can i do it ?

**Comment by shadow-vpn** [comment]
Which option should I change to text?
![Uploading Untitled.jpg…]()

**Comment by shadow-vpn** [comment]
Thank you, the problem is solved
