### ISSUE TITLE
XMPlus 2.0.8 better than 2.1.0

### ISSUE THREAD

**Issue by subzero9319** [xcode75/XManagerPlus#46]
In XMPlus 2.0.8 my config is vmess+ws+tls ping is 600-700 in v2rayng

![22222222222222222222222222](https://user-images.githubusercontent.com/117565604/218672918-d005ae78-a084-48b3-96f7-385659f79a85.png)

----------------
But in XMPlus 2.1.0 my config is same but ping is 5000

![11111111111](https://user-images.githubusercontent.com/117565604/218673103-5352d667-2355-4546-b6b3-38257f43cb3d.png)

what is wrong?

**Comment by subzero9319** [comment]
this problem solved

unfortunately my ip banned from MTN Irancell
and i changed my ip 
now it's ok

**Comment by xcode75** [comment]
I have not made any changes, i only update thr official xray-core. If have any issue may be from the core of which i am not responsible for.
