### ISSUE TITLE
XMPlus.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by ArashPersian** [xcode75/XManagerPlus#48]
hello my friend .
When I want to add my new server and complete its node and restart xmplus, I get an XMPlus may fail to start, please use XMPlus log to check the log information later, and then when I log, it shows me this 
Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Scheduled restart job, restart counter is at 893.
Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: Stopped XMPlus Service.
Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: Started XMPlus Service.
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: XMPlus v2.1.0 (A custom version of XrayR)
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: 2023/02/15 12:17:17 Starting XMPlus
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: 2023/02/15 12:17:17 Failed to unmarshal DNS config: /etc/XMPlus/dns.json
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: panic: Failed to unmarshal DNS config: /etc/XMPlus/dns.json
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: goroutine 1 [running]:
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: log.Panicf({0x3123e70?, 0x14?}, {0xc000723be8?, 0x2881280?, 0xc0004d4f50?})
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]:         log/log.go:391 +0x67
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel.(*Panel).loadCore(0xc000723e68?, 0xc0004de150)
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]:         github.com/xcode75/XMPlus/panel/panel.go:60 +0x245
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004b4280)
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]:         github.com/xcode75/XMPlus/panel/panel.go:158 +0xe9
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: main.main()
Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]:         github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Failed with result 'exit-code'.

Please explain to me as a beginner, thank you.

**Comment by matador7495** [comment]
Add a # to DnsConfigPath: /etc/XMPlus/dns.json in the config.json file, the problem may be solved.

**Comment by xcode75** [comment]
> hello my friend . When I want to add my new server and complete its node and restart xmplus, I get an XMPlus may fail to start, please use XMPlus log to check the log information later, and then when I log, it shows me this Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Scheduled restart job, restart counter is at 893. Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: Stopped XMPlus Service. Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: Started XMPlus Service. Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: XMPlus v2.1.0 (A custom version of XrayR) Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: 2023/02/15 12:17:17 Starting XMPlus Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: 2023/02/15 12:17:17 Failed to unmarshal DNS config: /etc/XMPlus/dns.json Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: panic: Failed to unmarshal DNS config: /etc/XMPlus/dns.json Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: goroutine 1 [running]: Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: log.Panicf({0x3123e70?, 0x14?}, {0xc000723be8?, 0x2881280?, 0xc0004d4f50?}) Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: log/log.go:391 +0x67 Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel.(*Panel).loadCore(0xc000723e68?, 0xc0004de150) Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel/panel.go:60 +0x245 Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004b4280) Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/panel/panel.go:158 +0xe9 Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: main.main() Feb 15 12:17:17 fi-2gb-hel1-1 XMPlus[63776]: github.com/xcode75/XMPlus/main/main.go:93 +0x2bf Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT Feb 15 12:17:17 fi-2gb-hel1-1 systemd[1]: XMPlus.service: Failed with result 'exit-code'.
> 
> Please explain to me as a beginner, thank you.

You edited dns.json and caused an error to the file. This is not backend issue but your doing.
