### ISSUE TITLE
How to Use custom SNI when using cdn

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#49]
hi. i want to use cloudflare cdn with custom sni. for example Vless-WS-CDN. 
server name: cpanel.com
request host: sub.mydomain.com (proxy on)
sni: sub.mydomain.com
when i use this setting it's work. but when i change sni to random sub domain ex: xxxaaaa.mydomai.com
it's not work. but when i change sni manualy in client app it works too
i changed rejectUnknownSni to false and allowInsecure to true not work

**Comment by xcode75** [comment]
Have no idea about that and never tried. You can google and see
