### ISSUE TITLE
how to use another domain for subscription links

### ISSUE THREAD

**Issue by HamrahVIP** [xcode75/XManagerPlus#50]
hi, because of risk to bann domain ;
how we can chnage subscription domain.
i want to use another domain or an internal host for subscription links

**Comment by xcode75** [comment]
![Screenshot_20230216-224831_Chrome](https://user-images.githubusercontent.com/87862554/219505047-4f012e0a-7d89-444d-acf0-5248fb964128.jpg)
Add the other domain to the same site nginx conf in aapanel for that site

**Comment by HamrahVIP** [comment]
bro my currect domain is: domain.com
and i want to use domain.net for subscription
so with aapanel we can use same domain not another domain
any other solution?

**Comment by xcode75** [comment]
> bro my currect domain is: domain.com and i want to use domain.net for subscription so with aapanel we can use same domain not another domain any other solution?

i showed you how to  add other domain to the site Conf in aapanel, just replace your SubUrl in admin setings of panel with ne domain

**Comment by HamrahVIP** [comment]
![1](https://user-images.githubusercontent.com/122527892/219705644-c728bfd5-ff34-4815-8b5f-62798b721be1.jpg)
![3](https://user-images.githubusercontent.com/122527892/219706467-808e0314-928e-4295-83cf-bd14cbeabbb8.jpg)
![2](https://user-images.githubusercontent.com/122527892/219705659-efb47a85-c1eb-4aa5-b7af-4810bafe1f4d.jpg)

the .com domain is domain that i installed xmplus. and the .xyz is my secundry domain.
any thing wron?

**Comment by HamrahVIP** [comment]
The problem solved by Delete website from aapanel and add again both website together.
But Just a bug !
When we use the second domain for subscription, when we add the subscription on the client, the domain name is displayed instead of the subscription name.

**Comment by xcode75** [comment]
Okay, will close issue now
