### ISSUE TITLE
XMPlus.service: main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by RealNavid** [xcode75/XManagerPlus#51]
Feb 16 22:37:51 centos-2gb-fsn1-2 systemd[1]: XMPlus.service failed.
Feb 16 22:38:01 centos-2gb-fsn1-2 systemd[1]: XMPlus.service holdoff time over, scheduling restart.
Feb 16 22:38:01 centos-2gb-fsn1-2 systemd[1]: Stopped XMPlus Service.
Feb 16 22:38:01 centos-2gb-fsn1-2 systemd[1]: Started XMPlus Service.
Feb 16 22:38:01 centos-2gb-fsn1-2 XMPlus[1058]: XMPlus v2.1.0 (A custom version of XrayR)
Feb 16 22:38:01 centos-2gb-fsn1-2 XMPlus[1058]: 2023/02/16 22:38:01 Starting XMPlus
Feb 16 22:38:01 centos-2gb-fsn1-2 XMPlus[1058]: 2023/02/16 22:38:01 [Info] app/dns: DNS: created localhost client
Feb 16 22:38:01 centos-2gb-fsn1-2 XMPlus[1058]: 2023/02/16 22:38:01 [Warning] core: Xray 1.7.3 started
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2442368]
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: goroutine 1 [running]:
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/api/xmplus.(*APIClient).parseNodeResponse(0xc0000abb00, 0xc0008e5000)
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/api/xmplus/xmplus.go:352 +0x288
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/api/xmplus.(*APIClient).GetNodeInfo(0xc0000abb00)
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/api/xmplus/xmplus.go:111 +0x337
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc0008d6700)
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/service/controller/controller.go:72 +0xdb
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004ac280)
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/panel/panel.go:184 +0x37d
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: main.main()
Feb 16 22:38:02 centos-2gb-fsn1-2 XMPlus[1058]: github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 16 22:38:02 centos-2gb-fsn1-2 systemd[1]: XMPlus.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 16 22:38:02 centos-2gb-fsn1-2 systemd[1]: Unit XMPlus.service entered failed state.

**Comment by xcode75** [comment]
Follow the issue template instruction

**Comment by xcode75** [comment]
I cannot read from that, send a screenshot
