### ISSUE TITLE
XMPlus.service: main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by RealNavid** [xcode75/XManagerPlus#52]
Hi, I faced this problem with XMPlus (Backend) and my backend server is different from frontend:

![bandicam 2023-02-17 02-18-35-367](https://user-images.githubusercontent.com/62522790/219504978-61ad77e2-65d4-4426-b5bc-ba04ae98bae4.jpg)

**Comment by xcode75** [comment]
Your server config is wrong, check and fix in panel
