### ISSUE TITLE
a little bug ifor change config link

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#54]
hello
sir for example i share my link for my friend and now i not like my friend use my vpn change link is work but my friend also connected in my vpn 
![ijj](https://user-images.githubusercontent.com/123809903/219705880-94a73c69-3b44-4875-b088-1f078a4de992.png)

![sdasd](https://user-images.githubusercontent.com/123809903/219706031-1c316dfa-501e-4a64-9c52-9e7ae8b907a1.png)

**Comment by xcode75** [comment]
Is not a bug, if you just reset config link, he can still connect. You have to reset connection password and after 2 minutes he cannot connect
