### ISSUE TITLE
Bug website on mobile web

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#55]
The site does not display well on mobile web, it often freezes and stays on the side window
Language: FA
Fix it if possible

![Screenshot_20230218-022554](https://user-images.githubusercontent.com/38170923/219814015-18dbb39c-e6bd-4f74-b540-3656843fab25.png)

**Comment by xcode75** [comment]
Need more info, what browser?

**Comment by sh1375** [comment]
> Need more info, what browser?
Chrome
Safari
default Android browser

In general, there is a problem in Persian (FA) on mobile

**Comment by matador7495** [comment]
> > Need more info, what browser?
> > Chrome
> > Safari
> > default Android browser
> 
> In general, there is a problem in Persian (FA) on mobile

This problem mostly occurs when your internet speed is low
