### ISSUE TITLE
Nginx + CDN [ WS(TLS) / GRPC (TLS) ]

### ISSUE THREAD

**Issue by ArashPersian** [xcode75/XManagerPlus#56]
Hello dear friends
Please explain the Nginx + CDN [ WS(TLS) / GRPC (TLS) ]
 part in more detail and tell which parts of this node should be changed. It would be great if there is a video tutorial for making it. 
 
![image](https://user-images.githubusercontent.com/119868315/219868893-ae0bd5c0-b9af-4d74-bd3f-48d3365145e8.png)

**Comment by xcode75** [comment]
Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port

**Comment by ArashPersian** [comment]
thank you dear
I will try now

> Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port

**Comment by seniormmd1** [comment]
> Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port

sir need chang "grpc pass 127.0.0.1:your listening port" port in cdn.conf file ?

**Comment by ArashPersian** [comment]
Please upload a photo of an edited node as an example, because I edited the file but still got the error.

![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)

**Comment by xcode75** [comment]
> > Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port
> 
> sir need chang "grpc pass 127.0.0.1:your listening port" port in cdn.conf file ?

yes

**Comment by xcode75** [comment]
> Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> 
> ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)

this has nothing to do with server config, your nginx conf has an issue use journalctl -xeu to check or systemctl status nginx

**Comment by seniormmd1** [comment]
> > > Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port
> > 
> > 
> > sir need chang "grpc pass 127.0.0.1:your listening port" port in cdn.conf file ?
> 
> yes

if we have multi config with grpc and different port .. how to set another port in cdn.conf file ?

**Comment by seniormmd1** [comment]
> > > > > Change domain to yours, the grpc service name to wha to what you used in your config, and grpc pass is 127.0.0.1:your listening port
> > > > 
> > > > 
> > > > sir need chang "grpc pass 127.0.0.1:your listening port" port in cdn.conf file ?
> > > 
> > > 
> > > yes
> > 
> > 
> > if we have multi config with grpc and different port .. how to set another port in cdn.conf file ?
> 
> add new duplicate the location

Which part of the code should be copied?

**Comment by seniormmd1** [comment]
I copied all the location code, but nginx gave an error that the code was repeated

**Comment by ArashPersian** [comment]
> 
I got this error and I think it's cdn.conf related right?
If it is related to cdn.conf, please make an example of it with specifications and send it so that I can get help from it. Thank You


![image](https://user-images.githubusercontent.com/119868315/220324827-ea89c698-d81a-47e1-8229-c5a2d21c0cdf.png)

**Comment by subzero9319** [comment]
> Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> 
> ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)

![2023-02-21 15_49_55-Clipboard](https://user-images.githubusercontent.com/117565604/220344076-2ce6e5aa-f3e2-4036-90c4-6647b411e688.png)

**Comment by subzero9319** [comment]
> I copied all the location code, but nginx gave an error that the code was repeated

copy like this 
![2023-02-21 15_54_49-_C__Users_Hajat_AppData_Local_Temp_tmp-6652-h2M7gs1o66lc_cdn conf - Notepad++](https://user-images.githubusercontent.com/117565604/220344441-18fbc23f-c4c6-4b3d-9ea4-3619d55743c9.png)

**Comment by subzero9319** [comment]
> > 
> 
> I got this error and I think it's cdn.conf related right? If it is related to cdn.conf, please make an example of it with specifications and send it so that I can get help from it. Thank You
> 
> ![image](https://user-images.githubusercontent.com/119868315/220324827-ea89c698-d81a-47e1-8229-c5a2d21c0cdf.png)

maybe your certificate address isn't correct

check it

**Comment by seniormmd1** [comment]
> > I copied all the location code, but nginx gave an error that the code was repeated
> 
> copy like this ![2023-02-21 15_54_49-_C__Users_Hajat_AppData_Local_Temp_tmp-6652-h2M7gs1o66lc_cdn conf - Notepad++](https://user-images.githubusercontent.com/117565604/220344441-18fbc23f-c4c6-4b3d-9ea4-3619d55743c9.png)

I copied like you, but it gives this error
nginx: [emerg] duplicate location "/grpc/Tun" in /etc/nginx/conf.d/cdn.conf:57

**Comment by xcode75** [comment]
> 

it says you have an error on line 57

**Comment by ArashPersian** [comment]
> > Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> > ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)
> 
> ![2023-02-21 15_49_55-Clipboard](https://user-images.githubusercontent.com/117565604/220344076-2ce6e5aa-f3e2-4036-90c4-6647b411e688.png)

tnx dear .
i will try

**Comment by Zo0oX** [comment]
> > Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> > ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)
> 
> ![2023-02-21 15_49_55-Clipboard](https://user-images.githubusercontent.com/117565604/220344076-2ce6e5aa-f3e2-4036-90c4-6647b411e688.png)

my problem is certificate, i cant see key and cert file

**Comment by subzero9319** [comment]
> > > Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> > > ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)
> > 
> > 
> > ![2023-02-21 15_49_55-Clipboard](https://user-images.githubusercontent.com/117565604/220344076-2ce6e5aa-f3e2-4036-90c4-6647b411e688.png)
> 
> my problem is certificate, i cant see key and cert file

Go to this location:
/etc/XMPlus/cert/certificates

**Comment by Zo0oX** [comment]
> 
my problem too, this folder is empty

**Comment by subzero9319** [comment]
> > 
> 
> my problem too, this folder is empty

first of all you must add server 
after that set security configuration then set cert mode to HTTP

![image](https://user-images.githubusercontent.com/117565604/221417261-d8a409cd-73ca-4e57-9ef4-38948db9322d.png)

**Comment by Zo0oX** [comment]
i do but service not runing, this is my log

`Feb 26 14:41:34 space14-1 XMPlus[34092]: XMPlus v2.1.0 (A custom version of XrayR)
Feb 26 14:41:34 space14-1 XMPlus[34092]: 2023/02/26 14:41:34 Starting XMPlus
Feb 26 14:41:34 space14-1 XMPlus[34092]: 2023/02/26 14:41:34 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
Feb 26 14:41:34 space14-1 XMPlus[34092]: 2023/02/26 14:41:34 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
Feb 26 14:41:34 space14-1 XMPlus[34092]: 2023/02/26 14:41:34 [Warning] core: Xray 1.7.3 started
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] [space14.bestspace.space] acme: Obtaining bundled SAN certificate
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] [space14.bestspace.space] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/206576637157
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] [space14.bestspace.space] acme: Could not find solver for: tls-alpn-01
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] [space14.bestspace.space] acme: use http-01 solver
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] [space14.bestspace.space] acme: Trying to solve HTTP-01
Feb 26 14:41:35 space14-1 XMPlus[34092]: 2023/02/26 14:41:35 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/206576637157
Feb 26 14:41:36 space14-1 XMPlus[34092]: 2023/02/26 14:41:36 Could not obtain certificates:
Feb 26 14:41:36 space14-1 XMPlus[34092]:         error: one or more domains had a problem:
Feb 26 14:41:36 space14-1 XMPlus[34092]: [MY-DOMAIN] [MY-DOMAIN] acme: error presenting token: could not start HTTP server for challenge: listen tcp :80: bind: address already in use
Feb 26 14:41:36 space14-1 XMPlus[34092]: 2023/02/26 14:41:36 Could not obtain certificates:
Feb 26 14:41:36 space14-1 XMPlus[34092]:         error: one or more domains had a problem:
Feb 26 14:41:36 space14-1 XMPlus[34092]: [MY-DOMAIN] [MY-DOMAIN] acme: error presenting token: could not start HTTP server for challenge: listen tcp :80: bind: address already in use
Feb 26 14:41:36 space14-1 XMPlus[34092]: panic: Could not obtain certificates:
Feb 26 14:41:36 space14-1 XMPlus[34092]:         error: one or more domains had a problem:
Feb 26 14:41:36 space14-1 XMPlus[34092]: [MY-DOMAIN] [MY-DOMAIN] acme: error presenting token: could not start HTTP server for challenge: listen tcp :80: bind: address already in use
Feb 26 14:41:36 space14-1 XMPlus[34092]: goroutine 1 [running]:
Feb 26 14:41:36 space14-1 XMPlus[34092]: log.Panic({0xc000b9fce8?, 0xc0008dc000?, 0xc000b9fd40?})
Feb 26 14:41:36 space14-1 XMPlus[34092]:         log/log.go:384 +0x65
Feb 26 14:41:36 space14-1 XMPlus[34092]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc0008e8800)
Feb 26 14:41:36 space14-1 XMPlus[34092]:         github.com/xcode75/XMPlus/service/controller/controller.go:112 +0x658
Feb 26 14:41:36 space14-1 XMPlus[34092]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004b4240)
Feb 26 14:41:36 space14-1 XMPlus[34092]:         github.com/xcode75/XMPlus/panel/panel.go:184 +0x37d
Feb 26 14:41:36 space14-1 XMPlus[34092]: main.main()
Feb 26 14:41:36 space14-1 XMPlus[34092]:         github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 26 14:41:36 space14-1 systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 26 14:41:36 space14-1 systemd[1]: XMPlus.service: Failed with result 'exit-code'`

**Comment by subzero9319** [comment]
there isn't any host
![image](https://user-images.githubusercontent.com/117565604/221417663-8439750f-69d5-4800-9a88-cdbca673f6bd.png)

**Comment by seniormmd1** [comment]
I went through all the steps according to the tutorial.... Enjinx is working properly and xmplus It doesn't give any error, but the config doesn't work and it gives error 503... Can anyone help me?

**Comment by matador7495** [comment]
دوستان برای استفاده از Nginx cdn  مراحل رو به این ترتیب برید
بعد از اینکه سرور خام رو تحویل گرفتید و آپدیت زدید اگر میخواهید tls داشته باشید با cerbot فایل هاشو بگیرید
اگر نه ک از این مرحله بگذرید nginx رو نصب کنید دقیقا مراحل طبق مستندات در سایت xcode هست فایل کانفیگ رو ایجاد کنید تغییرات لازم رو در کد اعمال کنید که در اولین خط میشه دامنه شما در قسمت location هم همان path را می دهید که در پنل برای آن نود در حالت ws ایجاد کرده اید بعد یک پورت تعیین می کنید روبروی 127 در پنل هم باید بجای 0000 تغییر بدید به 127.0.0.1 و پورت پنل هم تغییر بدید به همان پورت ک در فایل cdn زدید بعد برید xmplus xray نصب کنید و کانفیگ رو انجام بدید و به راحتی می توانید استفاده کنید 

من بروی vmess ws cdn تست کردم و اوکی بوده.

**Comment by Zo0oX** [comment]
> 

از تنظیمات سمت پنل میتونی اسکرین شات بزاری ؟

**Comment by Zo0oX** [comment]
> دوستان برای استفاده از Nginx cdn مراحل رو به این ترتیب برید بعد از اینکه سرور خام رو تحویل گرفتید و آپدیت زدید اگر میخواهید tls داشته باشید با cerbot فایل هاشو بگیرید اگر نه ک از این مرحله بگذرید nginx رو نصب کنید دقیقا مراحل طبق مستندات در سایت xcode هست فایل کانفیگ رو ایجاد کنید تغییرات لازم رو در کد اعمال کنید که در اولین خط میشه دامنه شما در قسمت location هم همان path را می دهید که در پنل برای آن نود در حالت ws ایجاد کرده اید بعد یک پورت تعیین می کنید روبروی 127 در پنل هم باید بجای 0000 تغییر بدید به 127.0.0.1 و پورت پنل هم تغییر بدید به همان پورت ک در فایل cdn زدید بعد برید xmplus xray نصب کنید و کانفیگ رو انجام بدید و به راحتی می توانید استفاده کنید
> 
> من بروی vmess ws cdn تست کردم و اوکی بوده.

از تنظیمات سمت پنل میتونی اسکرین شات بزاری ؟

**Comment by matador7495** [comment]
![Screenshot 2023-02-28 233752](https://user-images.githubusercontent.com/30972110/221960743-5a0133f4-720e-4af5-beba-1480217b8fc4.jpg)

**Comment by Zo0oX** [comment]
تنظیمات شبکه و امنیت هم میزازی ؟

**Comment by Zo0oX** [comment]
> ![Screenshot 2023-02-28 233752](https://user-images.githubusercontent.com/30972110/221960743-5a0133f4-720e-4af5-beba-1480217b8fc4.jpg)

تنظیمات شبکه و امنیت هم میزازی ؟
منم همینا رو زدم وصل نمیشه

**Comment by HamrahVIP** [comment]
i have a problem with vless&vmess+WS. when i confix nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!

**Comment by subzero9319** [comment]
question 1: please send your nginx cdn.conf

question 2: yes, i use multiple cdn.conf

**Comment by subzero9319** [comment]
> i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> 
> vless&vmess+grpc work without problem.
> 
> and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?

question 1: please send your nginx cdn.conf

question 2: yes, i use multiple cdn.conf

**Comment by HamrahVIP** [comment]
> > i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> > vless&vmess+grpc work without problem.
> > and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?
> 
> question 1: please send your nginx cdn.conf
> 
> question 2: yes, i use multiple cdn.conf

here is nginx conf setting and xmplus server setting: (Only Works with Trojan+WS) not work with Vless And Vmess

![1](https://user-images.githubusercontent.com/122527892/229303722-74dde7f2-7e30-4aab-b0c5-0a4fe1e90582.jpg)

![2](https://user-images.githubusercontent.com/122527892/229303734-9f63834d-ecf5-4589-ac63-c3745cbf41c8.jpg)

**Comment by subzero9319** [comment]
> > > i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> > > vless&vmess+grpc work without problem.
> > > and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?
> > 
> > 
> > question 1: please send your nginx cdn.conf
> > question 2: yes, i use multiple cdn.conf
> 
> here is nginx conf setting and xmplus server setting: (Only Works with Trojan+WS) not work with Vless And Vmess
> 
> ![1](https://user-images.githubusercontent.com/122527892/229303722-74dde7f2-7e30-4aab-b0c5-0a4fe1e90582.jpg)
> 
> ![2](https://user-images.githubusercontent.com/122527892/229303734-9f63834d-ecf5-4589-ac63-c3745cbf41c8.jpg)

enable tls
![image](https://user-images.githubusercontent.com/117565604/229308632-19647c42-20ae-4d7e-9e94-ffd17ae99df8.png)

**Comment by HamrahVIP** [comment]
> > > > i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> > > > vless&vmess+grpc work without problem.
> > > > and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?
> > > 
> > > 
> > > question 1: please send your nginx cdn.conf
> > > question 2: yes, i use multiple cdn.conf
> > 
> > 
> > here is nginx conf setting and xmplus server setting: (Only Works with Trojan+WS) not work with Vless And Vmess
> > ![1](https://user-images.githubusercontent.com/122527892/229303722-74dde7f2-7e30-4aab-b0c5-0a4fe1e90582.jpg)
> > ![2](https://user-images.githubusercontent.com/122527892/229303734-9f63834d-ecf5-4589-ac63-c3745cbf41c8.jpg)
> 
> enable tls ![image](https://user-images.githubusercontent.com/117565604/229308632-19647c42-20ae-4d7e-9e94-ffd17ae99df8.png)

Thanks Bro. 
and how to use multiple cdn.conf or multiple domain in cdn config

**Comment by subzero9319** [comment]
> > > > > i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> > > > > vless&vmess+grpc work without problem.
> > > > > and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?
> > > > 
> > > > 
> > > > question 1: please send your nginx cdn.conf
> > > > question 2: yes, i use multiple cdn.conf
> > > 
> > > 
> > > here is nginx conf setting and xmplus server setting: (Only Works with Trojan+WS) not work with Vless And Vmess
> > > ![1](https://user-images.githubusercontent.com/122527892/229303722-74dde7f2-7e30-4aab-b0c5-0a4fe1e90582.jpg)
> > > ![2](https://user-images.githubusercontent.com/122527892/229303734-9f63834d-ecf5-4589-ac63-c3745cbf41c8.jpg)
> > 
> > 
> > enable tls ![image](https://user-images.githubusercontent.com/117565604/229308632-19647c42-20ae-4d7e-9e94-ffd17ae99df8.png)
> 
> Thanks Bro. and how to use multiple cdn.conf or multiple domain in cdn config

use this sample:

x.you.tk-2087.conf
z.you.tk-2096.conf

also you can run multiple connection on same port you need to add new duplicate the location

**Comment by HamrahVIP** [comment]
> > > > > > i have a problem with vless&vmess+WS TLS. when i config nginx for WS and add vless or vmess config in xmplus, the proxy not connect. but if i change Type to Trojan it works Well !!
> > > > > > vless&vmess+grpc work without problem.
> > > > > > and another question, can we use more than one domain or more than one cdn.conf for nginx+cdn?
> > > > > 
> > > > > 
> > > > > question 1: please send your nginx cdn.conf
> > > > > question 2: yes, i use multiple cdn.conf
> > > > 
> > > > 
> > > > here is nginx conf setting and xmplus server setting: (Only Works with Trojan+WS) not work with Vless And Vmess
> > > > ![1](https://user-images.githubusercontent.com/122527892/229303722-74dde7f2-7e30-4aab-b0c5-0a4fe1e90582.jpg)
> > > > ![2](https://user-images.githubusercontent.com/122527892/229303734-9f63834d-ecf5-4589-ac63-c3745cbf41c8.jpg)
> > > 
> > > 
> > > enable tls ![image](https://user-images.githubusercontent.com/117565604/229308632-19647c42-20ae-4d7e-9e94-ffd17ae99df8.png)
> > 
> > 
> > Thanks Bro. and how to use multiple cdn.conf or multiple domain in cdn config
> 
> use this sample:
> 
> x.you.tk-2087.conf z.you.tk-2096.conf
> 
> also you can run multiple connection on same port you need to add new duplicate the location

Thanks Bro

**Comment by HamrahVIP** [comment]
it's possible to use two domains with 443 port?

**Comment by ArashPersian** [comment]
Hello friends, I made many configurations in xmplus, which all work, now I also made them in nginx, fortunately, I did not encounter any errors and everything was successful, but unfortunately, the connection cannot be established, thank you for your help.

VLESS + WS+ TLS
With CF IP domain
![image](https://user-images.githubusercontent.com/119868315/235750386-483ed8d9-b186-420c-b070-996b47690737.png)

![image](https://user-images.githubusercontent.com/119868315/235751149-2eeab092-6dee-40d8-8cef-fa541fb7420f.png)

![image](https://user-images.githubusercontent.com/119868315/235752523-477cd51c-9df4-4022-a282-a741ecbed5d8.png)

**Comment by ArashPersian** [comment]
> > Please upload a photo of an edited node as an example, because I edited the file but still got the error.
> > ![image](https://user-images.githubusercontent.com/119868315/220129570-0f94e26c-a2cb-4c1e-8c0f-155ce4644dd3.png)
> 
> ![2023-02-21 15_49_55-Clipboard](https://user-images.githubusercontent.com/117565604/220344076-2ce6e5aa-f3e2-4036-90c4-6647b411e688.png)

hello my friend do u have telegram .?
And can I message you there, if yes, please send me your telegram ID, thanks.

**Comment by bahramini** [comment]
دوستان استفاده از nginx مزیتی برای شما داشته؟ نسبت به کانفیگ ws پشت کلادفلر فرقی میکنه؟

**Comment by payeh** [comment]
@ArashPersian 
سلام داش کانفیگ ریلیتی  آموزشش رو بزار تازه به آپدیت اضاف شده

**Comment by ArashPersian** [comment]
> @ArashPersian سلام داش کانفیگ ریلیتی آموزشش رو بزار تازه به آپدیت اضاف شده

سلام رفیق .
آموزشش رو بقیه دوستان بلد هستن همون اشخاصی که من رو ریپلی  و راهنمایی کردن ی تاپیک باز بکن به اسم ریلیتی و اونجا در خواست کن تا بزارن.

**Comment by aliafshany** [comment]
@subzero9319 @ArashPersian @xcode75 @HamrahVIP 
Hello there
Guys, can you help me get my config to work? The Nginx config is working fine, and the settings in the panel are correct.

but still i get this error:
![image](https://github.com/xcode75/XManagerPlus/assets/40741745/8ead9210-f641-4c72-adc6-b99b44976a1e)
![CleanShot 2024-02-09 at 00 38 57](https://github.com/xcode75/XManagerPlus/assets/40741745/5f1bf307-962f-4953-a824-d2f62a11935a)
![CleanShot 2024-02-09 at 00 41 18](https://github.com/xcode75/XManagerPlus/assets/40741745/183e8e5a-5bcd-43e4-9b99-92f1597e08b6)
