### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alibbz1** [xcode75/XManagerPlus#58]
hi  what is this error bro ?

● XMPlus.service - XMPlus Service
   Loaded: loaded (/etc/systemd/system/XMPlus.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2023-02-19 21:46:05 UTC; 8s ago
  Process: 2038 ExecStart=/usr/local/XMPlus/XMPlus -config /etc/XMPlus/config.yml (code=exited, status=2)
 Main PID: 2038 (code=exited, status=2)

Feb 19 21:46:05 ali XMPlus[2038]: log.Panic({0xc000bc5ce8?, 0xc0008cc000?, 0xc000bc5d40?})
Feb 19 21:46:05 ali XMPlus[2038]: log/log.go:384 +0x65
Feb 19 21:46:05 ali XMPlus[2038]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc0008da800)
Feb 19 21:46:05 ali XMPlus[2038]: github.com/xcode75/XMPlus/service/controller/controller.go:112 +0x658
Feb 19 21:46:05 ali XMPlus[2038]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004ac280)
Feb 19 21:46:05 ali XMPlus[2038]: github.com/xcode75/XMPlus/panel/panel.go:184 +0x37d
Feb 19 21:46:05 ali XMPlus[2038]: main.main()
Feb 19 21:46:05 ali XMPlus[2038]: github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Feb 19 21:46:05 ali systemd[1]: Unit XMPlus.service entered failed state.
Feb 19 21:46:05 ali systemd[1]: XMPlus.service failed.

**Comment by xcode75** [comment]
not enough details to know what your issue is.
