### ISSUE TITLE
Very important bug in Backend

### ISSUE THREAD

**Issue by matador7495** [xcode75/XManagerPlus#59]
When in the Config File Line
/etc/xmplus/route.json out of comment mode
The following error occurs. There is a problem in the file. Please fix it.
The file is original and without manipulation. The DNS and Outbound file checked is no problem and the service is properly started.
This problem is in the last version of V2.1.0.

![Screenshot 2023-02-20 155241](https://user-images.githubusercontent.com/30972110/220110323-69a09ea8-5fcb-46de-a7ed-674f1839c30e.jpg)

**Comment by xcode75** [comment]
your route.json have an issue you need to provide all options here before saying backend have a bug. Opening an issue with insufficient infomation helps no one.  dn.json, outbond.json and route.json

**Comment by matador7495** [comment]
As I said, everything is the same as default and I did not change anything. I have uploaded the files in zip mode for you to review.

And as I said before, I used your original files, but still route.json has a problem.

this link : https://github.com/xcode75/XManagerPlus/issues/34
I also used the instructions in this section, but it still gave me an error.

I even removed the (#) one by one for the route-dns-outbound lines and tested, but when I remove the (#) for the route.json line, the service crashes and does not start.

[json file.zip](https://github.com/xcode75/XManagerPlus/files/10786358/json.file.zip)

**Comment by xcode75** [comment]
remove the socks5 from the router.json file

```
{
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "outboundTag": "block",
      "protocol": [
        "bittorrent"
      ],
      "ip": [
        "geoip:private"
      ]
    },
    {
      "type": "field",
      "outboundTag": "IPv6_out",
      "domain": [
        "geosite:netflix"
      ]
    },
    {
      "type": "field",
      "outboundTag": "IPv4_out",
      "network": "udp,tcp"
    }
  ]
}
```

**Comment by shadow-vpn** [comment]
@matador7495  i find the right config for this
plz send msg to me on telegram https://t.me/My_Shadowvpn

**Comment by letmefind** [comment]
I see users struggling to block Iran IP/Domains (XRayr or Xmlpus does not make redirect access of client IP , only Block IP or Domains) .

Here are the Steps:

### **If backend running on **_Xmplus_** :**

1- Download dat files (geosite.dat, geoip.dat iran.dat) :

```
wget -O /etc/XMPlus/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
wget -O /etc/XMPlus/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
wget -O /etc/XMPlus/iran.dat https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
```


2- Edit `/etc/XMPlus/route.json` as follow:


```
{
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "domain": [
            "regexp:.*\\.ir$",
            "ext:iran.dat:ir",
            "ext:iran.dat:other",
            "geosite:category-ir",
            "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
        ],
        "type": "field"
      }
    ]
} 
```
3- Edit `/etc/XMPlus/outbound.json` as follow:

```
[
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
```

4- Remove `#` in `/etc/XMPlus/config.yml` as follow:
```
DnsConfigPath:  #/etc/XMPlus/dns.json
RouteConfigPath:  /etc/XMPlus/route.json
InboundConfigPath: # /etc/XMPlus/inbound.json
OutboundConfigPath:  /etc/XMPlus/outbound.json
```
5- xmplus restart 


=======================================

### If backend running **XrayR**  it the same way as Xmplus 

1- Download dat files (geosite.dat, geoip.dat iran.dat) :

```
wget -O /etc/XrayR/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
wget -O /etc/XrayR/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
wget -O /etc/XrayR/iran.dat https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
```


2- Edit `/etc/XrayR/route.json` as follow:


```
{
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "domain": [
            "regexp:.*\\.ir$",
            "ext:iran.dat:ir",
            "ext:iran.dat:other",
            "geosite:category-ir",
            "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
        ],
        "type": "field"
      }
    ]
} 
```
3- Edit `/etc/XrayR/custom_outbound.json` as follow:

```
[
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
```

4- Remove `#` in` /etc/XrayR/config.yml `as follow:
```
DnsConfigPath: # /etc/XrayR/dns.json
RouteConfigPath:  /etc/XrayR/route.json
InboundConfigPath: # /etc/XrayR/custom_inbound.json
OutboundConfigPath:  /etc/XrayR/custom_outbound.json
```
5- xrayr restart 


hope you find this information useful!
