### ISSUE TITLE
Unable to signup by yahoo.com

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#60]
When creating an account with Yahoo, an error is received, but for example, no error is received with Gmail
I didn't check others email services
browser: chrome pc
![Screenshot 2023-02-20 194031](https://user-images.githubusercontent.com/57295411/220156236-5a5b67b7-7232-4ec9-a631-46349e416466.jpg)

**Comment by xcode75** [comment]
Noted, disabled email restriction for now. will take a look

**Comment by ca3tiel** [comment]
thx @xcode75 
problem solved by your Note
i forgot to set @ before yahoo.com in restriction and problem solved after add @
thx so much
