### ISSUE TITLE
verifying email issue on the phone

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#61]
I enabled email verification and it works perfectly when the users registers via PC.

But if the user wants to register through the phone, after receiving the email and clicking on the activation option, his account will not be activated and he will be redirected to the registration page and his account will not be activated.

device: Samsung S20 + chrome and i using Mail app to click on active Button (also i copy Button link and open that's in browser but same results)

(It is very important because 90% of users use mobile phones)

Unfortunately, there is no picture of the error that occurs to show, and this should be checked.

**Comment by xcode75** [comment]
Okay, i will take a look

**Comment by hiva005** [comment]
Hello, I encountered this error during the installation, can you help me?
Feb 20 23:46:26 ubuntu-2gb-nbg1-1 systemd[1]: XMPlus.service: Failed with result 'exit-code

**Comment by xcode75** [comment]
closing issue, will be fix in next update

**Comment by ca3tiel** [comment]
hi @xcode75 
Thanks for fixing this issue
I tested on the phone and this issue on the phone has been solved, but there are still 2 small bugs.
1- After creating an account and receiving the activation code on the phone, the received codes must be entered from right to left (RTL) to be confirmed (I testing on Persian language and i don't know English ) and this is while In Persian like English, numbers should be entered from left to right(LTR). 
for example if you receive 12345 code in email you should enter 54321 in panel to active your accunt. 
2- In the phone version, the squares where the verification code is entered are small and the entered characters are not visible.
