### ISSUE TITLE
More detailed reviews of site errors on mobile phones

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#62]
Most of the problems that I and others mentioned about the mobile web seem to be related to the speed of loading the site on mobile
I have provided screenshots of the speed test by cloudflare which I hope will help you to improve the bugs

Mobile:
![1](https://user-images.githubusercontent.com/38170923/220216266-efcd1fb2-d625-4ac1-a66c-4e3b2e185fd6.png)

Desktop:
![2](https://user-images.githubusercontent.com/38170923/220216341-7f52334d-b2ae-4c61-b98c-9604f63453a2.png)

**Comment by xcode75** [comment]
okay

**Comment by atbax** [comment]
In the latest update, even the efficiency in mobile has decreased, which is a critical problem as most of the users use mobile phones, they cannot open the user panel easily.
