### ISSUE TITLE
time 

### ISSUE THREAD

**Issue by mohammadoaaakd** [xcode75/XManagerPlus#64]
hello sir 
when i change time zone to tehran time expire is deleted

![sadsad](https://user-images.githubusercontent.com/123809903/220411306-1fc8d3da-cd12-4eaa-b92f-346e4b438963.png)

![rerr](https://user-images.githubusercontent.com/123809903/220411335-a74f3edf-b636-4f2c-8f5b-af003a2eab4b.png)

**Comment by matador7495** [comment]
firefox not support

**Comment by mohammadoaaakd** [comment]
ty
