### ISSUE TITLE
Question: There is no router option in the user dashboard for me!

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#67]
I saw a screenshot of XMPLUS on YouTube, after installation, there was a router option in the user dashboard, but i dont have this  option after installation. Please help me to active router option.
![Screenshot 2023-02-20 202839](https://user-images.githubusercontent.com/57295411/220769639-d83af9f8-69f8-461b-bbad-c13cc496fd27.jpg)

**Comment by xcode75** [comment]
you have to add in applications
