### ISSUE TITLE
XMPlus backend problem

### ISSUE THREAD

**Issue by payeh** [xcode75/XManagerPlus#69]
![image_2023-02-23_05-04-30](https://user-images.githubusercontent.com/28225346/220894718-33d05f2d-f57c-4186-b660-4dc4829d1335.png)
help me

**Comment by xcode75** [comment]
you need to set your tls certificate domain in server Security Settings -> serverName

```
{
  "serverName": "svr.xmplus.dev",
  "rejectUnknownSni": false,
  "allowInsecure": false,
  "fingerprint": "chrome"
}
```

**Comment by payeh** [comment]
> 

I did this but it didn't work
![Uploading fgg.jpg…]()

**Comment by payeh** [comment]
![fgg](https://user-images.githubusercontent.com/28225346/220896658-18bd3db7-a443-4fe6-92e7-7440d301b1fa.jpg)

**Comment by xcode75** [comment]
is the domain name resolving?

**Comment by xcode75** [comment]
okay
