### ISSUE TITLE
Where can I get the installation MPlus file?

### ISSUE THREAD

**Issue by certifiedtruecopy** [xcode75/XManagerPlus#7]
执行命令安装MPlus
cd /www/wwwroot/你的站点域名
**unzip XMPlus.zip**
chmod +x install.sh
./install.sh

**Comment by xcode75** [comment]
> 执行命令安装MPlus cd /www/wwwroot/你的站点域名 **unzip XMPlus.zip** chmod +x install.sh ./install.sh

will upload soon

**Comment by certifiedtruecopy** [comment]
Thanks

**Comment by xcode75** [comment]
> Thanks

follow the installation steps, is a freemium. for free version it is limited t 20 users
