### ISSUE TITLE
get an error when adding a new

### ISSUE THREAD

**Issue by mimuala** [xcode75/XManagerPlus#71]
I get an error when adding a new user from the admin account

![Screenshot 2023-02-23 154200](https://user-images.githubusercontent.com/23650020/220902220-52b9a9f0-4730-402e-8659-674e1e7f264a.png)
![Screenshot 2023-02-23 154312](https://user-images.githubusercontent.com/23650020/220902326-8722871d-78f4-4c05-b42c-e33876fac8e7.png)

**Comment by mimuala** [comment]
i use v20230211

**Comment by xcode75** [comment]
because that issue was fixed, manually download full package and unzip to site directory nd see if will be fixed

**Comment by mimuala** [comment]
solved
