### ISSUE TITLE
problem with TLS

### ISSUE THREAD

**Issue by Zo0oX** [xcode75/XManagerPlus#72]
hello

i make vmess(http+tcp+tls) , when i set TLS server see green in pannel, i reboot the xmplus in putty and sems running
but when i export vmess key tls is not on and key not work, how can i fix this ?

thanks

**Comment by xcode75** [comment]
Tls is not recommended for tcp+http, you can check official v2ray core non-recommended configuration. https://guide.v2fly.org/en_US/advanced/not_recommend.html
