### ISSUE TITLE
session expire time not working

### ISSUE THREAD

**Issue by mehtiamgh** [xcode75/XManagerPlus#73]
Hi
i have set session expire to 1 year (8760 hours) in config.php but not working and after 24 hours, says this error and it will go to the login page

bind ip : disable

![photo_2023-02-16_00-16-02](https://user-images.githubusercontent.com/74556168/221122015-3e5eb953-034a-42c6-81d5-cd11079e0fea.jpg)

**Comment by xcode75** [comment]
> Hi i have set session expire to 1 year (8760 hours) in config.php but not working and after 24 hours, says this error and it will go to the login page
> 
> bind ip : disable
> 
> ![photo_2023-02-16_00-16-02](https://user-images.githubusercontent.com/74556168/221122015-3e5eb953-034a-42c6-81d5-cd11079e0fea.jpg)

noted

**Comment by xcode75** [comment]
fixed in latest version
