### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#76]
Is it possible to implement routing? If yes how? In xray configuration there is a section for routing with which one can define which which traffic should not pass server. It's explained here:

https://xtls.github.io/config/routing.html#routingobject

Like this:

routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },

**Comment by amihos** [comment]
Update: I found out that there is line in config.yml file that refers to 

RouteConfigPath:  /etc/XMPlus/route.json


but as soon as I un comment it to activate it I get this panic error message: (please note that i did not change anything inside that file and its as default.)


Feb 27 10:55:31 US XMPlus[82140]: 2023/02/27 10:55:31 Starting XMPlus
Feb 27 10:55:32 US XMPlus[82140]: 2023/02/27 10:55:32 failed to create instance: app/router: this rule has no effective fields
Feb 27 10:55:32 US XMPlus[82140]: panic: failed to create instance: app/router: this rule has no effective fields
Feb 27 10:55:32 US XMPlus[82140]: goroutine 10 [running]:
Feb 27 10:55:32 US XMPlus[82140]: log.Panicf({0x3113238?, 0xc00127e960?}, {0xc000ce5b68?, 0x296ee00?, 0xc0015623c0?})
Feb 27 10:55:32 US XMPlus[82140]:         log/log.go:391 +0x67
Feb 27 10:55:32 US XMPlus[82140]: github.com/xcode75/XMPlus/panel.(*Panel).loadCore(0xc000b5dde8?, 0xc0001081c0)
Feb 27 10:55:32 US XMPlus[82140]:         github.com/xcode75/XMPlus/panel/panel.go:145 +0xc45
Feb 27 10:55:32 US XMPlus[82140]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc00081d740)
Feb 27 10:55:32 US XMPlus[82140]:         github.com/xcode75/XMPlus/panel/panel.go:158 +0xe9
Feb 27 10:55:32 US XMPlus[82140]: main.main.func1({{0xc000dc1ec0?, 0x16?}, 0x0?})
Feb 27 10:55:32 US XMPlus[82140]:         github.com/xcode75/XMPlus/main/main.go:91 +0x1cf
Feb 27 10:55:32 US XMPlus[82140]: github.com/spf13/viper.(*Viper).WatchConfig.func1.1()
Feb 27 10:55:32 US XMPlus[82140]:         github.com/spf13/viper@v1.14.0/viper.go:475 +0x2c6
Feb 27 10:55:32 US XMPlus[82140]: created by github.com/spf13/viper.(*Viper).WatchConfig.func1
Feb 27 10:55:32 US XMPlus[82140]:         github.com/spf13/viper@v1.14.0/viper.go:454 +0x2d1
Feb 27 10:55:32 US systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 27 10:55:32 US systemd[1]: XMPlus.service: Failed with result 'exit-code'.
Feb 27 10:55:32 US systemd[1]: XMPlus.service: Consumed 1d 22h 47min 55.661s CPU time.
Feb 27 10:55:35 US systemd[1]: Stopped XMPlus Service.
Feb 27 10:55:35 US systemd[1]: XMPlus.service: Consumed 1d 22h 47min 55.661s CPU time.
Feb 27 10:55:35 US systemd[1]: Started XMPlus Service.
Feb 27 10:55:36 US XMPlus[163954]: XMPlus v2.0.9 (A custom version of XrayR)
Feb 27 10:55:36 US XMPlus[163954]: 2023/02/27 10:55:36 Starting XMPlus
Feb 27 10:55:36 US XMPlus[163954]: 2023/02/27 10:55:36 failed to create instance: app/router: this rule has no effective fields
Feb 27 10:55:36 US XMPlus[163954]: panic: failed to create instance: app/router: this rule has no effective fields
Feb 27 10:55:36 US XMPlus[163954]: goroutine 1 [running]:
Feb 27 10:55:36 US XMPlus[163954]: log.Panicf({0x3113238?, 0xc0004db7a0?}, {0xc000ef1be8?, 0x296ee00?, 0xc0000b9ea0?})
Feb 27 10:55:36 US XMPlus[163954]:         log/log.go:391 +0x67
Feb 27 10:55:36 US XMPlus[163954]: github.com/xcode75/XMPlus/panel.(*Panel).loadCore(0xc00090fe68?, 0xc0001081c0)
Feb 27 10:55:36 US XMPlus[163954]:         github.com/xcode75/XMPlus/panel/panel.go:145 +0xc45
Feb 27 10:55:36 US XMPlus[163954]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0007fd740)
Feb 27 10:55:36 US XMPlus[163954]:         github.com/xcode75/XMPlus/panel/panel.go:158 +0xe9
Feb 27 10:55:36 US XMPlus[163954]: main. Main()
Feb 27 10:55:36 US XMPlus[163954]:         github.com/xcode75/XMPlus/main/main.go:95 +0x2bf
Feb 27 10:55:36 US systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 27 10:55:36 US systemd[1]: XMPlus.service: Failed with result 'exit-code'.

**Comment by xcode75** [comment]
https://github.com/xcode75/XManagerPlus/issues/34

https://github.com/xcode75/XManagerPlus/issues/63
