### ISSUE TITLE
Online user counter column disappeared after update

### ISSUE THREAD

**Issue by EmadHeravi** [xcode75/XManagerPlus#78]
ISSUE TEMPLATE
Descirption:

losing online column and active user counters after upgrade to v20230228

Version of XMPlus frontend
v20230228

Version of PHP
PHP7.4

Version of XMPlus/XrayR backend
v2.1.0

![New server view](https://user-images.githubusercontent.com/10885338/221811646-f5f538cc-8090-4af7-ae31-f129f6fe2fe4.png)
![old version](https://user-images.githubusercontent.com/10885338/221811651-f3598c1b-f6ad-4fe1-97f6-ba7845c69bc4.png)

**Comment by Zo0oX** [comment]
for me too, disappeared after update

**Comment by xcode75** [comment]
removed in current version
