### ISSUE TITLE
no listener port for various network protocols

### ISSUE THREAD

**Issue by EmadHeravi** [xcode75/XManagerPlus#80]
ISSUE TEMPLATE

Multiple protocols are not starting the listener ports on the back-end server. 
Protocols impacted: gRPC, H2, guic, kcp
Version of XMPlus frontend
v20230228)

Version of PHP

    PHP7.4

Version of XMPlus/XrayR backend

    v2.1.0
![bug listener](https://user-images.githubusercontent.com/10885338/221842356-f89cb881-ea37-4373-b906-08d1823a458b.png)

**Comment by xcode75** [comment]
> ISSUE TEMPLATE
> 
> Multiple protocols are not starting the listener ports on the back-end server. Protocols impacted: gRPC, H2, guic, kcp Version of XMPlus frontend v20230228)
> 
> Version of PHP
> 
> ```
> PHP7.4
> ```
> 
> Version of XMPlus/XrayR backend
> 
> ```
> v2.1.0
> ```
> 
> ![bug listener](https://user-images.githubusercontent.com/10885338/221842356-f89cb881-ea37-4373-b906-08d1823a458b.png)

Nothing wrong with that, once is connected is enough

**Comment by EmadHeravi** [comment]
there is no port to connect to. what do u mean once is connected?
