### ISSUE TITLE
 Negative volume of subscribers

### ISSUE THREAD

**Issue by kanganpishgaman** [xcode75/XManagerPlus#81]
Hello
After the new update, the volume of some users was reset and their daily usage became negative, and also in the server part, it no longer shows how many people are connected. Also, I installed the new update, but there was no change.
![dfdf](https://user-images.githubusercontent.com/126580383/221872729-80f855ba-855f-4997-a4b7-0d2cefc5970a.jpg)
![ttt](https://user-images.githubusercontent.com/126580383/221872740-1950a3c8-cdc7-405e-939e-73b1d6365a8c.jpg)

**Comment by Zo0oX** [comment]
this problem happend to me, i hope fixed soon
