### ISSUE TITLE
confirm user email update

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#83]
Hello, if possible, put a button in the users section in the admin panel to confirm the users' email
Now we have to confirm the email of the users through the database

**Comment by xcode75** [comment]
i do not know what you mean, post a screenshot

**Comment by shadow-vpn** [comment]
@xcode75 that s not an issue and not have screen shot but i explain it again

i need one button on admin panel to confirm user email verification because some users cannot verify their email i want one button on admin panel for verify user email manually

**Comment by xcode75** [comment]
noted
