### ISSUE TITLE
After updating the v20230301

### ISSUE THREAD

**Issue by sh1375** [xcode75/XManagerPlus#86]
Thanks for fixing the bug
Most of the bugs have been fixed with this update
I will post the remaining and seen bugs for you

1) I got the following error while paying with USDT:
{"error":{"type":"Whoops\Exception\ErrorException","message":"bcmul(): bcmath function argument is not well-formed","code":2,"file":"/www/wwwroot/tld.com/app/Repository/Payments/USDT.php","line":0,"trace":[{"file":"/www/wwwroot/tld.com/app/Repository/Payments/USDT.php","line":0,"function":null,"class":"Whoops\Exception\ErrorException","args":["bcmul(): bcmath function argument is not well-formed"]},{"file":"/www/wwwroot/tld.com/app/Repository/Payments/USDT.php","line":0,"function":"handleError","class":"Whoops\Run","args":[]},{"file":"/www/wwwroot/tld.com/app/Services/PaymentService.php","line":0,"function":"pay","class":"App\Repository\Payments\USDT","args":[]},{"file":"/www/wwwroot/tld.com/app/Http/Controllers/User/OrderController.php","line":0,"function":"pay","class":"App\Services\PaymentService","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php","line":43,"function":"checkout","class":"App\Http\Controllers\User\OrderController","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Routing/Route.php","line":384,"function":"__invoke","class":"Slim\Handlers\Strategies\RequestResponse","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":81,"function":"handle","class":"Slim\Routing\Route","args":[]},{"file":"/www/wwwroot/tld.com/app/Http/Middleware/UserAuth.php","line":53,"function":"handle","class":"Slim\MiddlewareDispatcher","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"App\Http\Middleware\UserAuth","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:294$15fc5","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Routing/Route.php","line":341,"function":"handle","class":"Slim\MiddlewareDispatcher","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Routing/RouteRunner.php","line":84,"function":"run","class":"Slim\Routing\Route","args":[]},{"file":"/www/wwwroot/tld.com/vendor/bryanjhv/slim-session/src/Slim/Middleware/Session.php","line":82,"function":"handle","class":"Slim\Routing\RouteRunner","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":313,"function":"__invoke","class":"Slim\Middleware\Session","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php","line":68,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:294$15fc5","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\Middleware\BodyParsingMiddleware","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":59,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$15fc3","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\Middleware\RoutingMiddleware","args":[]},{"file":"/www/wwwroot/tld.com/vendor/selective/basepath/src/BasePathMiddleware.php","line":52,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$15fc3","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":209,"function":"process","class":"Selective\BasePath\BasePathMiddleware","args":[]},{"file":"/www/wwwroot/tld.com/vendor/middlewares/whoops/src/Whoops.php","line":104,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$15fc4","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":147,"function":"process","class":"Middlewares\Whoops","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php","line":107,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$15fc3","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":147,"function":"process","class":"Slim\Middleware\ErrorMiddleware","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php","line":81,"function":"handle","class":"class@anonymous\u0000/www/wwwroot/tld.com/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$15fc3","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/App.php","line":215,"function":"handle","class":"Slim\MiddlewareDispatcher","args":[]},{"file":"/www/wwwroot/tld.com/vendor/slim/slim/Slim/App.php","line":199,"function":"handle","class":"Slim\App","args":[]},{"file":"/www/wwwroot/tld.com/public/index.php","line":0,"function":"run","class":"Slim\App","args":[]}]}}

2) Regarding the error of displaying the remaining time of the subscription that different users announced about Iran's time zone.
With instructions https://www.php.net/manual/en/timezones.php
Asia/Tehran
Iran
It has serious problem for +3:30 GMT time zone
I fixed the problem by setting Etc/GMT-3 with a difference of 30 minutes

![Bug 3](https://user-images.githubusercontent.com/38170923/222215020-0cc8b4ba-8e39-48fa-a372-5692385faf9a.png)

Also I set time settings in aapanel to +3:30 GMT time zone and Iran and Tehran

![Bug 4](https://user-images.githubusercontent.com/38170923/222215035-3329009a-32fe-4a73-9a8f-b51d0d43abdd.png)

This problem did not exist in v20230131 and earlier updates
If possible, put an option to receive the time from the aapanel

**Comment by xcode75** [comment]
i have checked and USDT works fine, the time issue will be fix in php on next update

**Comment by sh1375** [comment]
> i have checked and USDT works fine, the time issue will be fix in php on next update

Thanks for looking into the problem USDT
I checked and realized that the problem is related to Setting --> Default Currency
This problem occurs when I change this part to Iran

![Bug 5](https://user-images.githubusercontent.com/38170923/222587179-e3aa0451-3b5c-4dca-a411-55b60f7affd8.png)

Thanks for the updates
