### ISSUE TITLE
user access Denied

### ISSUE THREAD

**Issue by Zo0oX** [xcode75/XManagerPlus#87]
after update to last version and replace 

`LoginController.php
PasswordController.php
RegisterController.php
`
user can't login and see access Denied

-----------

after upload new composer.json and runing php composer.phar update -n

i see this code

`Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if yo                    u want to allow plugins to run as root/super user.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
62 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> php -r  "file_exists('smarty_internal_resource_file.php') && copy('smarty_internal_resource_file.php', 'vendor/sma                    rty/smarty/libs/sysplugins/smarty_internal_resource_file.php');"

In Process.php line 146:

  The Process class relies on proc_open, which is not available on your PHP i
  nstallation.

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-d                    ev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progre                    ss] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--cla                    ssmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IG                    NORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--                    ] [<packages>...]
`

**Comment by xcode75** [comment]
access Denied means a user account is trying to login using admin login path. Aside that composer error shows your php does not have proc_open. Check php disabled_fucntions and remove if exist or google how to fix proc_open issue
