### ISSUE TITLE
empty backup in Telegram bot

### ISSUE THREAD

**Issue by mimuala** [xcode75/XManagerPlus#88]
After update to v20230301
I received an empty backup in Telegram bot
![image_2023-03-02_16-40-18](https://user-images.githubusercontent.com/23650020/222438596-4bef8118-981b-400e-826b-f5455495f34c.jpg)

**Comment by sh1375** [comment]
I checked and there was no problem
You definitely did not have a complete update
I suggest you do the following commands for a better update:

sudo yum update
cd /www/wwwroot/tld.com
rm XMPlus.zip*

Then delete all the old update files by typing    y
Then do the following commands to download and update to the latest version:

wget https://github.com/xcode75/XManagerPlus/releases/download/v20230301/XMPlus.zip
unzip XMPlus.zip
php composer.phar update -n
php bin/console.php update version v20230301

**Comment by amihos** [comment]
@mimuala  When I open it with windows I see nothing either. However when I open the file with 7zip. The file is there hidden inside many folders

\www\wwwroot\tld.com\bin\..\\storage\backup\XMPlus_2023_03_03_17_30_01\

**Comment by mimuala** [comment]
> @mimuala When I open it with windows I see nothing either. However when I open the file with 7zip. The file is there hidden inside many folders
> 
> \www\wwwroot\tld.com\bin..\storage\backup\XMPlus_2023_03_03_17_30_01\

yes i see

**Comment by xcode75** [comment]
Will make changes to the zip directory in future update
