### ISSUE TITLE
Confusing way to verify email

### ISSUE THREAD

**Issue by ca3tiel** [xcode75/XManagerPlus#89]
After creating an account and receiving the activation code on the phone, the received codes must be entered from right to left (RTL) to be confirmed and this is while numbers should be entered from left to right(LTR) in all languages.

for example : if you receive 12345 code in email, You must enter the code in reverse order from right to left like 54321 in website to able active your account and this make confusing users.
i test this in PC and phone

another related issue to verify email : In the phone, the squares where the verification code is entered are small and the entered characters are not visible.

**Comment by shadow-vpn** [comment]
This problem also exists for Google Authenticator in RTL Language

**Comment by xcode75** [comment]
> After creating an account and receiving the activation code on the phone, the received codes must be entered from right to left (RTL) to be confirmed and this is while numbers should be entered from left to right(LTR) in all languages.
> 
> for example : if you receive 12345 code in email, You must enter the code in reverse order from right to left like 54321 in website to able active your account and this make confusing users. i test this in PC and phone
> 
> another related issue to verify email : In the phone, the squares where the verification code is entered are small and the entered characters are not visible.

noted
