### ISSUE TITLE
verification email not send

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#91]
After the v20230301 update, a large number of users have reported that the activation email is not sent to them.
Please check this problem in the next update

**Comment by xcode75** [comment]
either your email limit is exceeded or check settings again because sending email works fine

**Comment by shadow-vpn** [comment]
now when i want to send email via admin panel to any users , panel has note "invalid_grant"
so how can i solve it?

**Comment by ca3tiel** [comment]
@shadow-vpn 
I have tested the e -mail sending and it's work fine
set all config again ..maybe thats solve your issue

**Comment by shadow-vpn** [comment]
@ca3tiel  tnx i install xmplus again and problem is solved
