### ISSUE TITLE
user email confirm

### ISSUE THREAD

**Issue by shadow-vpn** [xcode75/XManagerPlus#98]
hi dear
In update "v20230301" you say "Email verification is fixed with email verification enabled when an admin creates a new account."
Now that my user can't verify his email because he doesn't have access to emails or something
How can I verify their email in the admin panel?

**Comment by ca3tiel** [comment]
look at here [#97](https://github.com/xcode75/XManagerPlus/issues/97) 
i was explain how to fix this and dear @xcode75 answered
email verification working whiteout any issue ..plz fallow this instruction :
https://xcode75.github.io/XMPlusDocs/usage/google.html
that's all you need
ask about any steps you have issue and i try to help you
