### ISSUE TITLE
Each user can buy multiple orders at the same time

### ISSUE THREAD

**Issue by Dev-l0p** [xcode75/XManagerPlus#99]
Hello Sir.
Special Thanks for your panel.
It's Great and powerful.
But it lacks one feature and that feature is very basic and practical:

In the panel, each user can only have one active order and use it. If he wants to order another config, he must register once again with other details. This is very time consuming and will involve a lot of resources.
In addition, one user may need 100 separate configurations, and this means creating 100 separate users.
In your panel, we can see attractive features that may be useful for us in the future. But this feature is very useful and necessary for the panel.

Thank you for your attention

**Comment by Saman1835** [comment]
Yes

**Comment by xcode75** [comment]
Maybe will support in the future.
